namespace IW4.Assets.Assets.Weapon;

public sealed class WeaponPrimarySoundFields
{
    public WeaponSoundAliasField PickupSound { get; init; } = new();
    public WeaponSoundAliasField PickupSoundPlayer { get; init; } = new();
    public WeaponSoundAliasField AmmoPickupSound { get; init; } = new();
    public WeaponSoundAliasField AmmoPickupSoundPlayer { get; init; } = new();
    public WeaponSoundAliasField ProjectileSound { get; init; } = new();
    public WeaponSoundAliasField PullbackSound { get; init; } = new();
    public WeaponSoundAliasField PullbackSoundPlayer { get; init; } = new();
    public WeaponSoundAliasField FireSound { get; init; } = new();
    public WeaponSoundAliasField FireSoundPlayer { get; init; } = new();
    public WeaponSoundAliasField FireSoundPlayerAkimbo { get; init; } = new();
    public WeaponSoundAliasField FireLoopSound { get; init; } = new();
    public WeaponSoundAliasField FireLoopSoundPlayer { get; init; } = new();
    public WeaponSoundAliasField FireStopSound { get; init; } = new();
    public WeaponSoundAliasField FireStopSoundPlayer { get; init; } = new();
    public WeaponSoundAliasField FireLastSound { get; init; } = new();
    public WeaponSoundAliasField FireLastSoundPlayer { get; init; } = new();
    public WeaponSoundAliasField EmptyFireSound { get; init; } = new();
    public WeaponSoundAliasField EmptyFireSoundPlayer { get; init; } = new();
    public WeaponSoundAliasField MeleeSwipeSound { get; init; } = new();
    public WeaponSoundAliasField MeleeSwipeSoundPlayer { get; init; } = new();
    public WeaponSoundAliasField MeleeHitSound { get; init; } = new();
    public WeaponSoundAliasField MeleeMissSound { get; init; } = new();
    public WeaponSoundAliasField RechamberSound { get; init; } = new();
    public WeaponSoundAliasField RechamberSoundPlayer { get; init; } = new();
    public WeaponSoundAliasField ReloadSound { get; init; } = new();
    public WeaponSoundAliasField ReloadSoundPlayer { get; init; } = new();
    public WeaponSoundAliasField ReloadEmptySound { get; init; } = new();
    public WeaponSoundAliasField ReloadEmptySoundPlayer { get; init; } = new();
    public WeaponSoundAliasField ReloadStartSound { get; init; } = new();
    public WeaponSoundAliasField ReloadStartSoundPlayer { get; init; } = new();
    public WeaponSoundAliasField ReloadEndSound { get; init; } = new();
    public WeaponSoundAliasField ReloadEndSoundPlayer { get; init; } = new();
    public WeaponSoundAliasField DetonateSound { get; init; } = new();
    public WeaponSoundAliasField DetonateSoundPlayer { get; init; } = new();
    public WeaponSoundAliasField NightVisionWearSound { get; init; } = new();
    public WeaponSoundAliasField NightVisionWearSoundPlayer { get; init; } = new();
    public WeaponSoundAliasField NightVisionRemoveSound { get; init; } = new();
    public WeaponSoundAliasField NightVisionRemoveSoundPlayer { get; init; } = new();
    public WeaponSoundAliasField AltSwitchSound { get; init; } = new();
    public WeaponSoundAliasField AltSwitchSoundPlayer { get; init; } = new();
    public WeaponSoundAliasField RaiseSound { get; init; } = new();
    public WeaponSoundAliasField RaiseSoundPlayer { get; init; } = new();
    public WeaponSoundAliasField FirstRaiseSound { get; init; } = new();
    public WeaponSoundAliasField FirstRaiseSoundPlayer { get; init; } = new();
    public WeaponSoundAliasField PutawaySound { get; init; } = new();
    public WeaponSoundAliasField PutawaySoundPlayer { get; init; } = new();
    public WeaponSoundAliasField ScanSound { get; init; } = new();

    public WeaponSoundAliasField Get(WeaponPrimarySoundSlot slot) => slot switch
    {
        WeaponPrimarySoundSlot.PickupSound => PickupSound,
        WeaponPrimarySoundSlot.PickupSoundPlayer => PickupSoundPlayer,
        WeaponPrimarySoundSlot.AmmoPickupSound => AmmoPickupSound,
        WeaponPrimarySoundSlot.AmmoPickupSoundPlayer => AmmoPickupSoundPlayer,
        WeaponPrimarySoundSlot.ProjectileSound => ProjectileSound,
        WeaponPrimarySoundSlot.PullbackSound => PullbackSound,
        WeaponPrimarySoundSlot.PullbackSoundPlayer => PullbackSoundPlayer,
        WeaponPrimarySoundSlot.FireSound => FireSound,
        WeaponPrimarySoundSlot.FireSoundPlayer => FireSoundPlayer,
        WeaponPrimarySoundSlot.FireSoundPlayerAkimbo => FireSoundPlayerAkimbo,
        WeaponPrimarySoundSlot.FireLoopSound => FireLoopSound,
        WeaponPrimarySoundSlot.FireLoopSoundPlayer => FireLoopSoundPlayer,
        WeaponPrimarySoundSlot.FireStopSound => FireStopSound,
        WeaponPrimarySoundSlot.FireStopSoundPlayer => FireStopSoundPlayer,
        WeaponPrimarySoundSlot.FireLastSound => FireLastSound,
        WeaponPrimarySoundSlot.FireLastSoundPlayer => FireLastSoundPlayer,
        WeaponPrimarySoundSlot.EmptyFireSound => EmptyFireSound,
        WeaponPrimarySoundSlot.EmptyFireSoundPlayer => EmptyFireSoundPlayer,
        WeaponPrimarySoundSlot.MeleeSwipeSound => MeleeSwipeSound,
        WeaponPrimarySoundSlot.MeleeSwipeSoundPlayer => MeleeSwipeSoundPlayer,
        WeaponPrimarySoundSlot.MeleeHitSound => MeleeHitSound,
        WeaponPrimarySoundSlot.MeleeMissSound => MeleeMissSound,
        WeaponPrimarySoundSlot.RechamberSound => RechamberSound,
        WeaponPrimarySoundSlot.RechamberSoundPlayer => RechamberSoundPlayer,
        WeaponPrimarySoundSlot.ReloadSound => ReloadSound,
        WeaponPrimarySoundSlot.ReloadSoundPlayer => ReloadSoundPlayer,
        WeaponPrimarySoundSlot.ReloadEmptySound => ReloadEmptySound,
        WeaponPrimarySoundSlot.ReloadEmptySoundPlayer => ReloadEmptySoundPlayer,
        WeaponPrimarySoundSlot.ReloadStartSound => ReloadStartSound,
        WeaponPrimarySoundSlot.ReloadStartSoundPlayer => ReloadStartSoundPlayer,
        WeaponPrimarySoundSlot.ReloadEndSound => ReloadEndSound,
        WeaponPrimarySoundSlot.ReloadEndSoundPlayer => ReloadEndSoundPlayer,
        WeaponPrimarySoundSlot.DetonateSound => DetonateSound,
        WeaponPrimarySoundSlot.DetonateSoundPlayer => DetonateSoundPlayer,
        WeaponPrimarySoundSlot.NightVisionWearSound => NightVisionWearSound,
        WeaponPrimarySoundSlot.NightVisionWearSoundPlayer => NightVisionWearSoundPlayer,
        WeaponPrimarySoundSlot.NightVisionRemoveSound => NightVisionRemoveSound,
        WeaponPrimarySoundSlot.NightVisionRemoveSoundPlayer => NightVisionRemoveSoundPlayer,
        WeaponPrimarySoundSlot.AltSwitchSound => AltSwitchSound,
        WeaponPrimarySoundSlot.AltSwitchSoundPlayer => AltSwitchSoundPlayer,
        WeaponPrimarySoundSlot.RaiseSound => RaiseSound,
        WeaponPrimarySoundSlot.RaiseSoundPlayer => RaiseSoundPlayer,
        WeaponPrimarySoundSlot.FirstRaiseSound => FirstRaiseSound,
        WeaponPrimarySoundSlot.FirstRaiseSoundPlayer => FirstRaiseSoundPlayer,
        WeaponPrimarySoundSlot.PutawaySound => PutawaySound,
        WeaponPrimarySoundSlot.PutawaySoundPlayer => PutawaySoundPlayer,
        WeaponPrimarySoundSlot.ScanSound => ScanSound,
        _ => throw new ArgumentOutOfRangeException(nameof(slot), slot, null)
    };
}
