namespace IW4.Assets.Assets.Weapon;

public enum WeaponAnimationSlot
{
    Root = 0,
    Idle = 1,
    EmptyIdle = 2,
    Fire = 3,
    HoldFire = 4,
    LastShot = 5,
    Rechamber = 6,
    Melee = 7,
    MeleeCharge = 8,
    Reload = 9,
    ReloadEmpty = 10,
    ReloadStart = 11,
    ReloadEnd = 12,
    Raise = 13,
    FirstRaise = 14,
    BreachRaise = 15,
    Drop = 16,
    AltRaise = 17,
    AltDrop = 18,
    QuickRaise = 19,
    QuickDrop = 20,
    EmptyRaise = 21,
    EmptyDrop = 22,
    SprintIn = 23,
    SprintLoop = 24,
    SprintOut = 25,
    StunnedStart = 26,
    StunnedLoop = 27,
    StunnedEnd = 28,
    Detonate = 29,
    NightVisionWear = 30,
    NightVisionRemove = 31,
    AdsFire = 32,
    AdsLastShot = 33,
    AdsRechamber = 34,
    AdsUp = 35,
    AdsDown = 36,
    Count = 37
}
