#!/usr/bin/env ruby
# Deterministic generator for explicit, reflection-free WeaponDraft mutations.

default_root = File.expand_path('../..', __dir__)
root = File.expand_path(ARGV.fetch(0, default_root))
weapon_dir = File.join(root, 'src/IW4.Assets/Assets/Weapon')
output = File.join(root, 'src/IW4.Studio/Documents/WeaponEditing/WeaponDraft.GeneratedMutations.cs')

Property = Struct.new(:type, :name)
classes = {}
Dir[File.join(weapon_dir, 'Weapon*.cs')].sort.each do |path|
  text = File.read(path)
  match = text.match(/public sealed class (Weapon\w+)/)
  next unless match
  name = match[1]
  properties = text.scan(/^\s*public\s+(.+?)\s+(\w+)\s*\{\s*get;\s*init;\s*\}/).map do |type, prop|
    Property.new(type.strip, prop)
  end
  classes[name] = properties unless properties.empty?
end

def list_type(type)
  match = type.match(/IReadOnlyList<(.+)>/)
  match && match[1]
end

def semantic?(property, classes)
  name = property.name
  return false if name == 'Offset' || name == 'Definition' || name == 'InternalName'
  return false if name.include?('Pointer') || name.include?('Padding')
  return false if %w[
    AiVsAiAccuracyGraphKnotCount
    AiVsPlayerAccuracyGraphKnotCount
    OriginalAiVsAiGraphKnotCount
    OriginalAiVsPlayerGraphKnotCount
  ].include?(name)
  return false if classes.key?(property.type)
  element = list_type(property.type)
  return false if element&.include?('XPointer') || element == 'XString'
  true
end

def cs_type(type)
  type.gsub('Material.MaterialAsset', 'MaterialAsset')
      .gsub('Math.Vec2', 'Vec2')
      .gsub('Math.Vec3', 'Vec3')
end

def method_suffix(path)
  path.join
end

def emit_copy_method(lines, class_name, properties, target)
  suffix = target.name
  lines << "    private static #{class_name} Copy#{class_name}#{suffix}(#{class_name} source, #{cs_type(target.type)} value) => new()"
  lines << '    {'
  properties.each do |property|
    rhs = property.name == target.name ? 'value' : "source.#{property.name}"
    lines << "        #{property.name} = #{rhs},"
  end
  lines << '    };'
  lines << ''
end

def emit_list_copy(lines, element_type)
  key = cs_type(element_type).gsub(/[^A-Za-z0-9]/, '')
  lines << "    private static IReadOnlyList<#{cs_type(element_type)}> Replace#{key}Item(IReadOnlyList<#{cs_type(element_type)}> source, int index, #{cs_type(element_type)} value)"
  lines << '    {'
  lines << '        ArgumentOutOfRangeException.ThrowIfNegative(index);'
  lines << '        if (index >= source.Count) throw new ArgumentOutOfRangeException(nameof(index));'
  lines << '        var result = source.ToArray();'
  lines << '        result[index] = value;'
  lines << '        return Array.AsReadOnly(result);'
  lines << '    }'
  lines << ''
end

variant = classes.fetch('WeaponVariantDef')
definition = classes.fetch('WeaponDef')
lines = []
lines << '// <auto-generated by tools/WeaponGeneration/generate_weapon_draft_mutations.rb />'
lines << '#nullable enable'
lines << 'using FxEffectDefAsset = IW4.Assets.Assets.Fx.FxEffectDefAsset;'
lines << 'using IW4.Assets.Assets.Material;'
lines << 'using IW4.Assets.Assets.Physics;'
lines << 'using IW4.Assets.Assets.Tracer;'
lines << 'using IW4.Assets.Assets.Weapon;'
lines << 'using IW4.Assets.Assets.XModel;'
lines << 'using Vec2 = IW4.Assets.Math.Vec2;'
lines << 'using Vec3 = IW4.Assets.Math.Vec3;'
lines << 'using IW4.FastFiles.Strings;'
lines << ''
lines << 'namespace IW4.Studio.Documents;'
lines << ''
lines << 'public sealed partial class WeaponDraft'
lines << '{'

copy_methods = {}
list_elements = {}

walk = lambda do |root_name, class_name, path, assignment_chain|
  properties = classes.fetch(class_name)
  properties.each do |property|
    if classes.key?(property.type)
      walk.call(root_name, property.type, path + [property.name], assignment_chain + [[class_name, property]])
      next
    end
    next unless semantic?(property, classes)
    element = list_type(property.type)
    method_name = "Set#{root_name}#{method_suffix(path + [property.name])}"
    value_type = element ? cs_type(element) : cs_type(property.type)
    params = element ? "int index, #{value_type} value" : "#{value_type} value"
    lines << "    public void #{method_name}(#{params})"
    lines << '    {'
    source = root_name == 'Variant' ? '_asset.Variant' : 'RequireDefinition()'
    current_expr = ([source] + path).join('.')
    replacement = if element
      list_elements[element] = true
      "Replace#{value_type.gsub(/[^A-Za-z0-9]/, '')}Item(#{current_expr}.#{property.name}, index, value)"
    else
      "value"
    end
    target_class = class_name
    target_key = [target_class, property.name]
    copy_methods[target_key] = [properties, property]
    expression = "Copy#{target_class}#{property.name}(#{current_expr}, #{replacement})"
    assignment_chain.reverse_each do |parent_class, parent_property|
      parent_path = path[0...path.index(parent_property.name)]
      parent_source = ([source] + parent_path).join('.')
      key = [parent_class, parent_property.name]
      copy_methods[key] = [classes.fetch(parent_class), parent_property]
      expression = "Copy#{parent_class}#{parent_property.name}(#{parent_source}, #{expression})"
    end
    if root_name == 'Variant'
      lines << "        SetVariantValues(#{expression});"
    else
      lines << "        SetDefinitionValues(#{expression});"
    end
    lines << '    }'
    lines << ''
  end
end

walk.call('Variant', 'WeaponVariantDef', [], [])
walk.call('Definition', 'WeaponDef', [], [])

list_elements.keys.sort.each { |element| emit_list_copy(lines, element) }
copy_methods.keys.sort.each do |class_name, property_name|
  properties, property = copy_methods[[class_name, property_name]]
  emit_copy_method(lines, class_name, properties, property)
end

lines << '}'
File.write(output, lines.join("\n") + "\n")
puts "generated #{output}: #{lines.length} lines, #{copy_methods.length} copy methods"
