using IW4.Assets.Assets.XAnim;
using IW4.FastFiles.Zone;
using IW4.FastFiles.Emitters.Assets;

namespace IW4.Studio.Documents;

/// <summary>Detached XAnim authoring state.  The snapshot includes every
/// packed stream and delta frame payload, never loader pointer cells.</summary>
public sealed class XAnimAuthoredSnapshot : ITargetZoneDetachedSemanticSnapshot
{
    internal XAnimAuthoredSnapshot(XAnimBuildData data) => Data = data.Copy();
    internal XAnimBuildData Data { get; }
    public XAssetType AssetType => XAssetType.XAnim;
    internal static XAnimAuthoredSnapshot Import(TargetZoneRowSource source) => source.AuthoredDefinition?.SemanticSnapshot is XAnimAuthoredSnapshot snapshot
        ? snapshot : throw new InvalidDataException("XAnim editing requires a capture-time detached semantic snapshot because nested data pointers may be aliases.");
    internal static XAnimAuthoredSnapshot FromLoaded(XAnimPartsAsset asset) => new(new XAnimBuildData(asset.Name, asset.DataByteCount, asset.DataShortCount, asset.DataIntCount, asset.RandomDataByteCount, asset.RandomDataIntCount, asset.NumFrames, asset.Flags, asset.DeltaFlags, asset.BoneCounts, asset.BoneNameCount, asset.NotifyCount, asset.AssetType, asset.Pad1F, asset.RandomDataShortCount, asset.IndexCount, asset.Framerate, asset.Frequency, asset.Names, asset.PackedDataStreams.QuantizedBytes, asset.PackedDataStreams.QuantizedShorts, asset.PackedDataStreams.QuantizedInts, asset.PackedDataStreams.RandomizedQuantizedShorts, asset.PackedDataStreams.RandomizedQuantizedBytes, asset.PackedDataStreams.RandomizedQuantizedInts, asset.Indices.FrameIndices, asset.Notify.Select(value => new XAnimNotifyBuildData(value.Name, value.Time)), Delta(asset.DeltaPart)));
    private static XAnimDeltaBuildData? Delta(XAnimDeltaPart? value) => value is null ? null : new(Trans(value.Trans), Quat2(value.Quat2), Quat(value.Quat));
    private static XAnimPartTransBuildData? Trans(XAnimPartTrans? value) { if (value is null) return null; if (value.Size == 0) return new(value.Size, value.SmallTrans, value.Pad3, value.Frame0 is { } frame ? Vector(frame.X, frame.Y, frame.Z) : null, null); XAnimPartTransFrames frames = value.Frames ?? throw new InvalidDataException("Dynamic XAnim translation lacks its frame data."); return new(value.Size, value.SmallTrans, value.Pad3, null, new XAnimTransFramesBuildData(Vector(frames.Mins.X, frames.Mins.Y, frames.Mins.Z), Vector(frames.Size.X, frames.Size.Y, frames.Size.Z), frames.DynamicFrames.FrameIndices, frames.FramePayload is SmallXAnimTransFramePayload small ? small.Frames.Select(entry => new XAnimSmallTransFrameBuildData(entry.X, entry.Y, entry.Z)).ToArray() : null, frames.FramePayload is LargeXAnimTransFramePayload large ? large.Frames.Select(entry => new XAnimLargeTransFrameBuildData(entry.X, entry.Y, entry.Z)).ToArray() : null)); }
    private static XAnimQuat2PartBuildData? Quat2(XAnimDeltaPartQuat2? value) => value is null ? null : value.Size == 0 ? new(value.Size, value.Pad2, value.Pad3, value.Frame0 is { } frame ? new XAnimQuat2BuildData(frame.Value0, frame.Value1) : null, null) : new(value.Size, value.Pad2, value.Pad3, null, new XAnimQuat2FramesBuildData(value.Frames!.DynamicFrames.FrameIndices, value.Frames.Frames.Select(entry => new XAnimQuat2BuildData(entry.Value0, entry.Value1)).ToArray()));
    private static XAnimQuatPartBuildData? Quat(XAnimDeltaPartQuat? value) => value is null ? null : value.Size == 0 ? new(value.Size, value.Pad2, value.Pad3, value.Frame0 is { } frame ? new XAnimQuatBuildData(frame.Value0, frame.Value1, frame.Value2, frame.Value3) : null, null) : new(value.Size, value.Pad2, value.Pad3, null, new XAnimQuatFramesBuildData(value.Frames!.DynamicFrames.FrameIndices, value.Frames.Frames.Select(entry => new XAnimQuatBuildData(entry.Value0, entry.Value1, entry.Value2, entry.Value3)).ToArray()));
    private static Float3BuildData Vector(float x, float y, float z) => new(x, y, z);
}

public sealed class XAnimBuildData : IXAnimBuildData
{
    private readonly byte[] _boneCounts, _dataBytes, _randomDataBytes; private readonly ushort[] _names, _indices; private readonly short[] _dataShorts, _randomDataShorts; private readonly int[] _dataInts, _randomDataInts; private readonly XAnimNotifyBuildData[] _notify;
    internal XAnimBuildData(string? name, ushort dataByteCount, ushort dataShortCount, ushort dataIntCount, ushort randomDataByteCount, ushort randomDataIntCount, ushort numFrames, byte flags, byte deltaFlags, IEnumerable<byte> boneCounts, byte boneNameCount, byte notifyCount, byte assetTypeValue, byte pad1F, int randomDataShortCount, int indexCount, float framerate, float frequency, IEnumerable<ushort> names, IEnumerable<byte> dataBytes, IEnumerable<short> dataShorts, IEnumerable<int> dataInts, IEnumerable<short> randomDataShorts, IEnumerable<byte> randomDataBytes, IEnumerable<int> randomDataInts, IEnumerable<ushort> indices, IEnumerable<XAnimNotifyBuildData> notify, XAnimDeltaBuildData? delta)
    { Name = name; DataByteCount = dataByteCount; DataShortCount = dataShortCount; DataIntCount = dataIntCount; RandomDataByteCount = randomDataByteCount; RandomDataIntCount = randomDataIntCount; NumFrames = numFrames; Flags = flags; DeltaFlags = deltaFlags; _boneCounts = boneCounts.ToArray(); BoneNameCount = boneNameCount; NotifyCount = notifyCount; AssetTypeValue = assetTypeValue; Pad1F = pad1F; RandomDataShortCount = randomDataShortCount; IndexCount = indexCount; Framerate = framerate; Frequency = frequency; _names = names.ToArray(); _dataBytes = dataBytes.ToArray(); _dataShorts = dataShorts.ToArray(); _dataInts = dataInts.ToArray(); _randomDataShorts = randomDataShorts.ToArray(); _randomDataBytes = randomDataBytes.ToArray(); _randomDataInts = randomDataInts.ToArray(); _indices = indices.ToArray(); _notify = notify.ToArray(); Delta = Clone(delta); }
    public XAssetType AssetType => XAssetType.XAnim; public string? Name { get; } public ushort DataByteCount { get; } public ushort DataShortCount { get; } public ushort DataIntCount { get; } public ushort RandomDataByteCount { get; } public ushort RandomDataIntCount { get; } public ushort NumFrames { get; } public byte Flags { get; } public byte DeltaFlags { get; } public IReadOnlyList<byte> BoneCounts => Array.AsReadOnly(_boneCounts); public byte BoneNameCount { get; } public byte NotifyCount { get; } public byte AssetTypeValue { get; } public byte Pad1F { get; } public int RandomDataShortCount { get; } public int IndexCount { get; } public float Framerate { get; } public float Frequency { get; } public IReadOnlyList<ushort> Names => Array.AsReadOnly(_names); public IReadOnlyList<byte> DataBytes => Array.AsReadOnly(_dataBytes); public IReadOnlyList<short> DataShorts => Array.AsReadOnly(_dataShorts); public IReadOnlyList<int> DataInts => Array.AsReadOnly(_dataInts); public IReadOnlyList<short> RandomDataShorts => Array.AsReadOnly(_randomDataShorts); public IReadOnlyList<byte> RandomDataBytes => Array.AsReadOnly(_randomDataBytes); public IReadOnlyList<int> RandomDataInts => Array.AsReadOnly(_randomDataInts); public IReadOnlyList<ushort> Indices => Array.AsReadOnly(_indices); public IReadOnlyList<XAnimNotifyBuildData> Notify => Array.AsReadOnly(_notify); public XAnimDeltaBuildData? Delta { get; }
    internal XAnimBuildData Copy() => new(Name, DataByteCount, DataShortCount, DataIntCount, RandomDataByteCount, RandomDataIntCount, NumFrames, Flags, DeltaFlags, _boneCounts, BoneNameCount, NotifyCount, AssetTypeValue, Pad1F, RandomDataShortCount, IndexCount, Framerate, Frequency, _names, _dataBytes, _dataShorts, _dataInts, _randomDataShorts, _randomDataBytes, _randomDataInts, _indices, _notify, Delta);
    internal static XAnimDeltaBuildData? Clone(XAnimDeltaBuildData? value) => value is null ? null : new(Clone(value.Trans), Clone(value.Quat2), Clone(value.Quat));
    private static XAnimPartTransBuildData? Clone(XAnimPartTransBuildData? value) => value is null ? null : new(value.Size, value.SmallTrans, value.Pad3, value.Frame0, value.Frames is null ? null : new XAnimTransFramesBuildData(value.Frames.Mins, value.Frames.Size, value.Frames.DynamicFrames, value.Frames.SmallFrames, value.Frames.LargeFrames));
    private static XAnimQuat2PartBuildData? Clone(XAnimQuat2PartBuildData? value) => value is null ? null : new(value.Size, value.Pad2, value.Pad3, value.Frame0, value.Frames is null ? null : new XAnimQuat2FramesBuildData(value.Frames.DynamicFrames, value.Frames.Frames));
    private static XAnimQuatPartBuildData? Clone(XAnimQuatPartBuildData? value) => value is null ? null : new(value.Size, value.Pad2, value.Pad3, value.Frame0, value.Frames is null ? null : new XAnimQuatFramesBuildData(value.Frames.DynamicFrames, value.Frames.Frames));
}

public sealed class XAnimDraft
{
    private XAnimBuildData _data; internal XAnimDraft(XAnimBuildData data) => _data = data.Copy(); public XAnimBuildData Data => _data.Copy();
    public void SetRates(float framerate, float frequency) => _data = Replace(framerate: framerate, frequency: frequency);
    public void ReplaceDelta(XAnimDeltaBuildData? delta) => _data = Replace(delta: delta, replaceDelta: true);
    public void ReplaceStreams(IEnumerable<byte> dataBytes, IEnumerable<short> dataShorts, IEnumerable<int> dataInts, IEnumerable<short> randomDataShorts, IEnumerable<byte> randomDataBytes, IEnumerable<int> randomDataInts, IEnumerable<ushort> indices) { ArgumentNullException.ThrowIfNull(dataBytes); ArgumentNullException.ThrowIfNull(dataShorts); ArgumentNullException.ThrowIfNull(dataInts); ArgumentNullException.ThrowIfNull(randomDataShorts); ArgumentNullException.ThrowIfNull(randomDataBytes); ArgumentNullException.ThrowIfNull(randomDataInts); ArgumentNullException.ThrowIfNull(indices); _data = Replace(dataBytes: dataBytes, dataShorts: dataShorts, dataInts: dataInts, randomDataShorts: randomDataShorts, randomDataBytes: randomDataBytes, randomDataInts: randomDataInts, indices: indices, countsFromStreams: true); }
    internal XAnimDraft Clone() => new(_data);
    private XAnimBuildData Replace(float? framerate = null, float? frequency = null, XAnimDeltaBuildData? delta = null, IEnumerable<byte>? dataBytes = null, IEnumerable<short>? dataShorts = null, IEnumerable<int>? dataInts = null, IEnumerable<short>? randomDataShorts = null, IEnumerable<byte>? randomDataBytes = null, IEnumerable<int>? randomDataInts = null, IEnumerable<ushort>? indices = null, bool countsFromStreams = false, bool replaceDelta = false)
    { byte[] db = (dataBytes ?? _data.DataBytes).ToArray(); short[] ds = (dataShorts ?? _data.DataShorts).ToArray(); int[] di = (dataInts ?? _data.DataInts).ToArray(); short[] rds = (randomDataShorts ?? _data.RandomDataShorts).ToArray(); byte[] rdb = (randomDataBytes ?? _data.RandomDataBytes).ToArray(); int[] rdi = (randomDataInts ?? _data.RandomDataInts).ToArray(); ushort[] ix = (indices ?? _data.Indices).ToArray(); return new XAnimBuildData(_data.Name, countsFromStreams ? checked((ushort)db.Length) : _data.DataByteCount, countsFromStreams ? checked((ushort)ds.Length) : _data.DataShortCount, countsFromStreams ? checked((ushort)di.Length) : _data.DataIntCount, countsFromStreams ? checked((ushort)rdb.Length) : _data.RandomDataByteCount, countsFromStreams ? checked((ushort)rdi.Length) : _data.RandomDataIntCount, _data.NumFrames, _data.Flags, _data.DeltaFlags, _data.BoneCounts, _data.BoneNameCount, _data.NotifyCount, _data.AssetTypeValue, _data.Pad1F, countsFromStreams ? rds.Length : _data.RandomDataShortCount, countsFromStreams ? ix.Length : _data.IndexCount, framerate ?? _data.Framerate, frequency ?? _data.Frequency, _data.Names, db, ds, di, rds, rdb, rdi, ix, _data.Notify, replaceDelta ? delta : _data.Delta); }
}

public sealed class XAnimAuthoringAdapter : AssetAuthoringAdapter<XAnimAuthoredSnapshot, XAnimDraft, XAnimBuildData>
{
    private static readonly XAnimBodyEmitter Validator = new(); public override XAssetType AssetType => XAssetType.XAnim; public override XAnimAuthoredSnapshot ImportAuthoredSnapshot(TargetZoneRowSource source) => XAnimAuthoredSnapshot.Import(source); public override XAnimDraft CreateDraft(XAnimAuthoredSnapshot snapshot) => new(snapshot.Data); public override XAnimDraft CloneDraft(XAnimDraft draft) => draft.Clone(); public override IReadOnlyList<AssetValidationIssue> ValidateDraft(XAnimDraft draft) => Validator.Validate(draft.Data).Select(value => new AssetValidationIssue(value.Path, value.Message, AssetValidationSeverity.Error)).ToArray(); public override bool SemanticallyEquals(XAnimDraft left, XAnimDraft right) => Same(left.Data, right.Data); public override XAnimBuildData ExportBuildData(XAnimDraft draft) { XAnimBuildData data = draft.Data; if (Validator.Validate(data).Count != 0) throw new InvalidOperationException("XAnim draft has validation errors and cannot produce build data."); return data; }
    private static bool Same(XAnimBuildData left, XAnimBuildData right) => left.Name == right.Name && left.DataByteCount == right.DataByteCount && left.DataShortCount == right.DataShortCount && left.DataIntCount == right.DataIntCount && left.RandomDataByteCount == right.RandomDataByteCount && left.RandomDataIntCount == right.RandomDataIntCount && left.NumFrames == right.NumFrames && left.Flags == right.Flags && left.DeltaFlags == right.DeltaFlags && left.BoneCounts.SequenceEqual(right.BoneCounts) && left.BoneNameCount == right.BoneNameCount && left.NotifyCount == right.NotifyCount && left.AssetTypeValue == right.AssetTypeValue && left.Pad1F == right.Pad1F && left.RandomDataShortCount == right.RandomDataShortCount && left.IndexCount == right.IndexCount && Bits(left.Framerate, right.Framerate) && Bits(left.Frequency, right.Frequency) && left.Names.SequenceEqual(right.Names) && left.DataBytes.SequenceEqual(right.DataBytes) && left.DataShorts.SequenceEqual(right.DataShorts) && left.DataInts.SequenceEqual(right.DataInts) && left.RandomDataShorts.SequenceEqual(right.RandomDataShorts) && left.RandomDataBytes.SequenceEqual(right.RandomDataBytes) && left.RandomDataInts.SequenceEqual(right.RandomDataInts) && left.Indices.SequenceEqual(right.Indices) && left.Notify.SequenceEqual(right.Notify) && Same(left.Delta, right.Delta);
    private static bool Same(XAnimDeltaBuildData? left, XAnimDeltaBuildData? right) => (left is null && right is null) || (left is { } a && right is { } b && Same(a.Trans, b.Trans) && Same(a.Quat2, b.Quat2) && Same(a.Quat, b.Quat));
    private static bool Same(XAnimPartTransBuildData? left, XAnimPartTransBuildData? right) => (left is null && right is null) || (left is { } a && right is { } b && a.Size == b.Size && a.SmallTrans == b.SmallTrans && a.Pad3 == b.Pad3 && Same(a.Frame0, b.Frame0) && ((a.Frames is null && b.Frames is null) || (a.Frames is { } af && b.Frames is { } bf && Same(af.Mins, bf.Mins) && Same(af.Size, bf.Size) && af.DynamicFrames.SequenceEqual(bf.DynamicFrames) && SameList(af.SmallFrames, bf.SmallFrames) && SameList(af.LargeFrames, bf.LargeFrames))));
    private static bool Same(XAnimQuat2PartBuildData? left, XAnimQuat2PartBuildData? right) => (left is null && right is null) || (left is { } a && right is { } b && a.Size == b.Size && a.Pad2 == b.Pad2 && a.Pad3 == b.Pad3 && a.Frame0 == b.Frame0 && ((a.Frames is null && b.Frames is null) || (a.Frames is { } af && b.Frames is { } bf && af.DynamicFrames.SequenceEqual(bf.DynamicFrames) && af.Frames.SequenceEqual(bf.Frames))));
    private static bool Same(XAnimQuatPartBuildData? left, XAnimQuatPartBuildData? right) => (left is null && right is null) || (left is { } a && right is { } b && a.Size == b.Size && a.Pad2 == b.Pad2 && a.Pad3 == b.Pad3 && a.Frame0 == b.Frame0 && ((a.Frames is null && b.Frames is null) || (a.Frames is { } af && b.Frames is { } bf && af.DynamicFrames.SequenceEqual(bf.DynamicFrames) && af.Frames.SequenceEqual(bf.Frames))));
    private static bool Same(Float3BuildData? left, Float3BuildData? right) => (left is null && right is null) || (left is { } a && right is { } b && Same(a, b)); private static bool Same(Float3BuildData left, Float3BuildData right) => Bits(left.X, right.X) && Bits(left.Y, right.Y) && Bits(left.Z, right.Z); private static bool SameList<T>(IReadOnlyList<T>? left, IReadOnlyList<T>? right) => left is null ? right is null : right is not null && left.SequenceEqual(right); private static bool Bits(float left, float right) => BitConverter.SingleToInt32Bits(left) == BitConverter.SingleToInt32Bits(right);
}
