namespace IW4.Gsc.BuiltIns;

public static partial class Iw4GscBuiltInCatalog
{
    private static partial IReadOnlyList<RegistrationGroup>
        GetRegistrationGroups() =>
        [
            new(
                "Global functions",
                Iw4GscBuiltInKind.Function,
                Iw4GscBuiltInReceiver.None,
                GlobalFunctions),
            new(
                "Generic entity methods",
                Iw4GscBuiltInKind.Method,
                Iw4GscBuiltInReceiver.Entity,
                GenericMethods),
            new(
                "Player methods",
                Iw4GscBuiltInKind.Method,
                Iw4GscBuiltInReceiver.Player,
                PlayerMethods),
            new(
                "Script entity/mover methods",
                Iw4GscBuiltInKind.Method,
                Iw4GscBuiltInReceiver.ScriptEntity,
                ScriptEntityMethods),
            new(
                "HUD element methods",
                Iw4GscBuiltInKind.Method,
                Iw4GscBuiltInReceiver.HudElement,
                HudElementMethods),
            new(
                "Helicopter methods",
                Iw4GscBuiltInKind.Method,
                Iw4GscBuiltInReceiver.Helicopter,
                HelicopterMethods),
            new(
                "Compiler/VM intrinsics",
                Iw4GscBuiltInKind.VmIntrinsic,
                Iw4GscBuiltInReceiver.None,
                VmIntrinsics)
        ];

    private static readonly Registration[] GlobalFunctions =
    [
        new("createprintchannel", "GScr_CreatePrintChannel", true),
        new("setprintchannel", "GScr_printChannelSet", true),
        new("print", "print", true),
        new("println", "println", true),
        new("iprintln", "iprintln", false),
        new("iprintlnbold", "iprintlnbold", false),
        new("print3d", "GScr_print3d", true),
        new("line", "GScr_line", true),
        new("logstring", "NULLSUB", false),
        new("getent", "Scr_GetEnt", false),
        new("getentarray", "Scr_GetEntArray", false),
        new("spawn", "GScr_Spawn", false),
        new("spawnplane", "GScr_SpawnPlane", false),
        new("spawnturret", "GScr_SpawnTurret", false),
        new("precacheturret", "GScr_PrecacheTurret", false),
        new("spawnstruct", "Scr_AddStruct", false),
        new("spawnhelicopter", "GScr_SpawnHelicopter", false),
        new("assert", "assertCmd", true),
        new("assertex", "assertexCmd", true),
        new("assertmsg", "assertmsgCmd", true),
        new("isdefined", "GScr_IsDefined", false),
        new("isstring", "GScr_IsString", false),
        new("isalive", "GScr_IsAlive", false),
        new("getdvar", "GScr_GetDvar", false),
        new("getdvarint", "GScr_GetDvarInt", false),
        new("getdvarfloat", "GScr_GetDvarFloat", false),
        new("setdvar", "GScr_SetDvar", false),
        new("gettime", "GScr_GetTime", false),
        new("getentbynum", "Scr_GetEntByNum", true),
        new("getweaponmodel", "Scr_GetWeaponModel", false),
        new("getanimlength", "GScr_GetAnimLength", false),
        new("animhasnotetrack", "GScr_AnimHasNotetrack", false),
        new("getnotetracktimes", "GScr_GetNotetrackTimes", false),
        new("getbrushmodelcenter", "GScr_GetBrushModelCenter", false),
        new("objective_add", "Scr_Objective_Add", false),
        new("objective_delete", "Scr_Objective_Delete", false),
        new("objective_state", "Scr_Objective_State", false),
        new("objective_icon", "Scr_Objective_Icon", false),
        new("objective_position", "Scr_Objective_Position", false),
        new("objective_onentity", "Scr_Objective_OnEntity", false),
        new("objective_current", "Scr_Objective_Current", false),
        new("missile_createattractorent", "Scr_MissileCreateAttractorEnt", false),
        new("missile_createattractororigin", "Scr_MissileCreateAttractorOrigin", false),
        new("missile_createrepulsorent", "Scr_MissileCreateRepulsorEnt", false),
        new("missile_createrepulsororigin", "Scr_MissileCreateRepulsorOrigin", false),
        new("missile_deleteattractor", "Scr_MissileDeleteAttractor", false),
        new("bullettrace", "Scr_BulletTrace", false),
        new("bullettracepassed", "Scr_BulletTracePassed", false),
        new("sighttracepassed", "Scr_SightTracePassed", false),
        new("physicstrace", "Scr_PhysicsTrace", false),
        new("playerphysicstrace", "Scr_PlayerPhysicsTrace", false),
        new("getmovedelta", "GScr_GetMoveDelta", false),
        new("getangledelta", "GScr_GetAngleDelta", false),
        new("getnorthyaw", "GScr_GetNorthYaw", false),
        new("randomint", "Scr_RandomInt", false),
        new("randomfloat", "Scr_RandomFloat", false),
        new("randomintrange", "Scr_RandomIntRange", false),
        new("randomfloatrange", "Scr_RandomFloatRange", false),
        new("sin", "GScr_sin", false),
        new("cos", "GScr_cos", false),
        new("tan", "GScr_tan", false),
        new("asin", "GScr_asin", false),
        new("acos", "GScr_acos", false),
        new("atan", "GScr_atan", false),
        new("int", "GScr_CastInt", false),
        new("abs", "GScr_abs", false),
        new("min", "GScr_min", false),
        new("max", "GScr_max", false),
        new("floor", "GScr_floor", false),
        new("ceil", "GScr_ceil", false),
        new("sqrt", "GScr_sqrt", false),
        new("vectorfromlinetopoint", "GScr_VectorFromLineToPoint", false),
        new("pointonsegmentnearesttopoint", "GScr_PointOnSegmentNearestToPoint", false),
        new("distance", "Scr_Distance", false),
        new("distance2d", "Scr_Distance2D", false),
        new("distancesquared", "Scr_DistanceSquared", false),
        new("length", "Scr_Length", false),
        new("lengthsquared", "Scr_LengthSquared", false),
        new("closer", "Scr_Closer", false),
        new("vectordot", "Scr_VectorDot", false),
        new("vectornormalize", "Scr_VectorNormalize", false),
        new("vectortoangles", "Scr_VectorToAngles", false),
        new("vectorlerp", "Scr_VectorLerp", false),
        new("anglestoup", "Scr_AnglesToUp", false),
        new("anglestoright", "Scr_AnglesToRight", false),
        new("anglestoforward", "Scr_AnglesToForward", false),
        new("combineangles", "Scr_CombineAngles", false),
        new("issubstr", "Scr_IsSubStr", false),
        new("getsubstr", "Scr_GetSubStr", false),
        new("tolower", "Scr_ToLower", false),
        new("strtok", "Scr_StrTok", false),
        new("musicplay", "Scr_MusicPlay", false),
        new("musicstop", "Scr_MusicStop", false),
        new("soundfade", "Scr_SoundFade", false),
        new("ambientplay", "Scr_AmbientPlay", false),
        new("ambientstop", "Scr_AmbientStop", false),
        new("precachemodel", "Scr_PrecacheModel", false),
        new("precacheshellshock", "Scr_PrecacheShellShock", false),
        new("precacheitem", "Scr_PrecacheItem", false),
        new("precacheshader", "Scr_PrecacheShader", false),
        new("precachestring", "Scr_PrecacheString", false),
        new("precacherumble", "NULLSUB", false),
        new("loadfx", "Scr_LoadFX", false),
        new("playfx", "Scr_PlayFX", false),
        new("playfxontag", "Scr_PlayFXOnTag", false),
        new("playloopedfx", "Scr_PlayLoopedFX", false),
        new("spawnfx", "Scr_SpawnFX", false),
        new("triggerfx", "Scr_TriggerFX", false),
        new("physicsexplosionsphere", "Scr_PhysicsExplosionSphere", false),
        new("physicsexplosioncylinder", "Scr_PhysicsExplosionCylinder", false),
        new("physicsjolt", "Scr_PhysicsRadiusJolt", false),
        new("physicsjitter", "Scr_PhysicsRadiusJitter", false),
        new("setexpfog", "Scr_SetExponentialFog", false),
        new("grenadeexplosioneffect", "Scr_GrenadeExplosionEffect", false),
        new("radiusdamage", "GScr_RadiusDamage", false),
        new("setplayerignoreradiusdamage", "GScr_SetPlayerIgnoreRadiusDamage", false),
        new("getnumparts", "GScr_GetNumParts", false),
        new("getpartname", "GScr_GetPartName", false),
        new("earthquake", "GScr_Earthquake", false),
        new("newhudelem", "GScr_NewHudElem", false),
        new("newclienthudelem", "GScr_NewClientHudElem", false),
        new("newteamhudelem", "GScr_NewTeamHudElem", false),
        new("resettimeout", "Scr_ResetTimeout", false),
        new("weaponfiretime", "GScr_WeaponFireTime", false),
        new("isweaponcliponly", "GScr_IsWeaponClipOnly", false),
        new("isweapondetonationtimed", "GScr_IsWeaponDetonationTimed", false),
        new("weaponclipsize", "GScr_WeaponClipSize", false),
        new("weaponissemiauto", "GScr_WeaponIsSemiAuto", false),
        new("weaponisboltaction", "GScr_WeaponIsBoltAction", false),
        new("weapontype", "GScr_WeaponType", false),
        new("weaponclass", "GScr_WeaponClass", false),
        new("weaponinventorytype", "GScr_WeaponInventoryType", false),
        new("weaponstartammo", "GScr_WeaponStartAmmo", false),
        new("weaponmaxammo", "GScr_WeaponMaxAmmo", false),
        new("weaponaltweaponname", "GScr_WeaponAltWeaponName", false),
        new("isplayer", "GScr_IsPlayer", false),
        new("isplayernumber", "GScr_IsPlayerNumber", false),
        new("setwinningplayer", "GScr_SetWinningPlayer", false),
        new("setwinningteam", "GScr_SetWinningTeam", false),
        new("announcement", "GScr_Announcement", false),
        new("clientannouncement", "GScr_ClientAnnouncement", false),
        new("getteamscore", "GScr_GetTeamScore", false),
        new("setteamscore", "GScr_SetTeamScore", false),
        new("setclientnamemode", "GScr_SetClientNameMode", false),
        new("updateclientnames", "GScr_UpdateClientNames", false),
        new("getteamplayersalive", "GScr_GetTeamPlayersAlive", false),
        new("objective_team", "GScr_Objective_Team", false),
        new("logprint", "GScr_LogPrint", false),
        new("worldentnumber", "GScr_WorldEntNumber", false),
        new("obituary", "GScr_Obituary", false),
        new("positionwouldtelefrag", "GScr_positionWouldTelefrag", false),
        new("getstarttime", "GScr_getStartTime", false),
        new("precachemenu", "GScr_PrecacheMenu", false),
        new("precachestatusicon", "GScr_PrecacheStatusIcon", false),
        new("precacheheadicon", "GScr_PrecacheHeadIcon", false),
        new("precachelocationselector", "GScr_PrecacheLocationSelector", false),
        new("map_restart", "GScr_MapRestart", false),
        new("exitlevel", "GScr_ExitLevel", false),
        new("addtestclient", "GScr_AddTestClient", false),
        new("makedvarserverinfo", "GScr_MakeDvarServerInfo", false),
        new("setarchive", "NULLSUB", false),
        new("allclientsprint", "GScr_AllClientsPrint", false),
        new("clientprint", "GScr_ClientPrint", false),
        new("mapexists", "GScr_MapExists", false),
        new("isvalidgametype", "GScr_IsValidGameType", false),
        new("matchend", "NULLSUB", false),
        new("setplayerteamrank", "NULLSUB", false),
        new("sendranks", "NULLSUB", false),
        new("endparty", "NULLSUB", false),
        new("setteamradar", "GScr_SetTeamRadar", false),
        new("getteamradar", "GScr_GetTeamRadar", false),
        new("getassignedteam", "PlayerCmd_buttonPressedDEVONLY", false),
        new("setvotestring", "GScr_SetVoteString", false),
        new("setvotetime", "GScr_SetVoteTime", false),
        new("setvoteyescount", "GScr_SetVoteYesCount", false),
        new("setvotenocount", "GScr_SetVoteNoCount", false),
        new("openfile", "GScr_OpenFile", true),
        new("closefile", "GScr_CloseFile", true),
        new("fprintln", "GScr_FPrintln", true),
        new("fprintfields", "GScr_FPrintFields", true),
        new("freadln", "GScr_FReadLn", true),
        new("fgetarg", "GScr_FGetArg", true),
        new("kick", "GScr_KickPlayer", false),
        new("ban", "GScr_BanPlayer", false),
        new("map", "GScr_LoadMap", false),
        new("playrumbleonposition", "NULLSUB", false),
        new("playrumblelooponposition", "NULLSUB", false),
        new("stopallrumbles", "NULLSUB", false),
        new("soundexists", "ScrCmd_SoundExists", false),
        new("issplitscreen", "PlayerCmd_buttonPressedDEVONLY", false),
        new("setminimap", "GScr_SetMiniMap", false),
        new("setmapcenter", "GScr_SetMapCenter", false),
        new("setgameendtime", "GScr_SetGameEndTime", false),
        new("getarraykeys", "GScr_GetArrayKeys", false),
        new("searchforonlinegames", "NULLSUB", false),
        new("quitlobby", "NULLSUB", false),
        new("quitparty", "NULLSUB", false),
        new("startparty", "NULLSUB", false),
        new("startprivatematch", "NULLSUB", false),
        new("visionsetnaked", "Scr_VisionSetNaked", false),
        new("visionsetnight", "Scr_VisionSetNight", false),
        new("tablelookup", "Scr_TableLookup", false),
        new("tablelookupistring", "Scr_TableLookupIString", false),
        new("endlobby", "NULLSUB", false),
    ];

    private static readonly Registration[] GenericMethods =
    [
        new("attach", "ScrCmd_attach", false),
        new("detach", "ScrCmd_detach", false),
        new("detachall", "ScrCmd_detachAll", false),
        new("getattachsize", "ScrCmd_GetAttachSize", false),
        new("getattachmodelname", "ScrCmd_GetAttachModelName", false),
        new("getattachtagname", "ScrCmd_GetAttachTagName", false),
        new("getattachignorecollision", "ScrCmd_GetAttachIgnoreCollision", false),
        new("getammocount", "GScr_GetAmmoCount", false),
        new("getclanid", "ScrCmd_GetClanId", false),
        new("getclanname", "ScrCmd_GetClanName", false),
        new("hidepart", "ScrCmd_hidepart", false),
        new("showpart", "ScrCmd_showpart", false),
        new("showallparts", "ScrCmd_showallparts", false),
        new("linkto", "ScrCmd_LinkTo", false),
        new("unlink", "ScrCmd_Unlink", false),
        new("enablelinkto", "ScrCmd_EnableLinkTo", false),
        new("getorigin", "ScrCmd_GetOrigin", false),
        new("geteye", "ScrCmd_GetEye", false),
        new("useby", "ScrCmd_UseBy", false),
        new("setstablemissile", "Scr_SetStableMissile", false),
        new("istouching", "ScrCmd_IsTouching", false),
        new("playsound", "ScrCmd_PlaySound", false),
        new("playsoundasmaster", "ScrCmd_PlaySoundAsMaster", false),
        new("playsoundtoteam", "ScrCmd_PlaySoundToTeam", false),
        new("playsoundtoplayer", "ScrCmd_PlaySoundToPlayer", false),
        new("playloopsound", "ScrCmd_PlayLoopSound", false),
        new("stoploopsound", "ScrCmd_StopLoopSound", false),
        new("playrumbleonentity", "ScrCmd_NULLSUB", false),
        new("playrumblelooponentity", "ScrCmd_NULLSUB", false),
        new("stoprumble", "ScrCmd_NULLSUB", false),
        new("delete", "ScrCmd_Delete", false),
        new("setmodel", "ScrCmd_SetModel", false),
        new("getnormalhealth", "ScrCmd_GetNormalHealth", false),
        new("setnormalhealth", "ScrCmd_SetNormalHealth", false),
        new("show", "ScrCmd_Show", false),
        new("hide", "ScrCmd_Hide", false),
        new("laseron", "ScrCmd_LaserOn", false),
        new("laseroff", "ScrCmd_LaserOff", false),
        new("showtoplayer", "ScrCmd_ShowToPlayer", false),
        new("setcontents", "ScrCmd_SetContents", false),
        new("getstance", "ScrCmd_GetStance", false),
        new("setcursorhint", "GScr_SetCursorHint", false),
        new("sethintstring", "GScr_SetHintString", false),
        new("usetriggerrequirelookat", "GScr_UseTriggerRequireLookAt", false),
        new("shellshock", "GScr_ShellShock", false),
        new("gettagorigin", "GScr_GetTagOrigin", false),
        new("gettagangles", "GScr_GetTagAngles", false),
        new("stopshellshock", "GScr_StopShellShock", false),
        new("setdepthoffield", "GScr_SetDepthOfField", false),
        new("setviewmodeldepthoffield", "GScr_SetViewModelDepthOfField", false),
        new("viewkick", "GScr_ViewKick", false),
        new("localtoworldcoords", "GScr_LocalToWorldCoords", false),
        new("setrightarc", "GScr_SetRightArc", false),
        new("setleftarc", "GScr_SetLeftArc", false),
        new("settoparc", "GScr_SetTopArc", false),
        new("setbottomarc", "GScr_SetBottomArc", false),
        new("radiusdamage", "GScr_EntityRadiusDamage", false),
        new("detonate", "GScr_Detonate", false),
        new("damageconetrace", "GScr_DamageConeTrace", false),
        new("sightconetrace", "GScr_SightConeTrace", false),
        new("getentitynumber", "GScr_GetEntityNumber", false),
        new("enablegrenadetouchdamage", "GScr_EnableGrenadeTouchDamage", false),
        new("disablegrenadetouchdamage", "GScr_DisableGrenadeTouchDamage", false),
        new("enableaimassist", "GScr_EnableAimAssist", false),
        new("disableaimassist", "GScr_DisableAimAssist", false),
        new("placespawnpoint", "GScr_PlaceSpawnPoint", false),
        new("setteamfortrigger", "GScr_SetTeamForTrigger", false),
        new("clientclaimtrigger", "GScr_ClientClaimTrigger", false),
        new("clientreleasetrigger", "GScr_ClientReleaseTrigger", false),
        new("releaseclaimedtrigger", "GScr_ReleaseClaimedTrigger", false),
        new("getstat", "GScr_GetStat", false),
        new("setstat", "GScr_SetStat", false),
        new("sendleaderboards", "ScrCmd_NULLSUB", false),
        new("setmovespeedscale", "ScrCmd_SetMoveSpeedScale", false),
        new("logstring", "ScrCmd_NULLSUB", false),
        new("missile_settarget", "GScr_MissileSetTarget", false),
        new("isonladder", "GScr_IsOnLadder", false),
        new("ismantling", "GScr_IsMantling", false),
        new("startragdoll", "GScr_StartRagdoll", false),
        new("isragdoll", "GScr_IsRagdoll", false),
        new("getcorpseanim", "GScr_GetCorpseAnim", false),
        new("itemweaponsetammo", "ScrCmd_ItemWeaponSetAmmo", false),
    ];

    private static readonly Registration[] PlayerMethods =
    [
        new("giveweapon", "PlayerCmd_giveWeapon", false),
        new("takeweapon", "PlayerCmd_takeWeapon", false),
        new("takeallweapons", "PlayerCmd_takeAllWeapons", false),
        new("getcurrentweapon", "PlayerCmd_getCurrentWeapon", false),
        new("getcurrentoffhand", "PlayerCmd_getCurrentOffhand", false),
        new("hasweapon", "PlayerCmd_hasWeapon", false),
        new("switchtoweapon", "PlayerCmd_switchToWeapon", false),
        new("switchtooffhand", "PlayerCmd_switchToOffhand", false),
        new("givestartammo", "PlayerCmd_giveStartAmmo", false),
        new("givemaxammo", "PlayerCmd_giveMaxAmmo", false),
        new("getfractionstartammo", "PlayerCmd_getFractionStartAmmo", false),
        new("getfractionmaxammo", "PlayerCmd_getFractionMaxAmmo", false),
        new("setorigin", "PlayerCmd_setOrigin", false),
        new("getvelocity", "PlayerCmd_GetVelocity", false),
        new("setplayerangles", "PlayerCmd_setAngles", false),
        new("getplayerangles", "PlayerCmd_getAngles", false),
        new("usebuttonpressed", "PlayerCmd_useButtonPressed", false),
        new("attackbuttonpressed", "PlayerCmd_attackButtonPressed", false),
        new("adsbuttonpressed", "PlayerCmd_adsButtonPressed", false),
        new("meleebuttonpressed", "PlayerCmd_meleeButtonPressed", false),
        new("fragbuttonpressed", "PlayerCmd_fragButtonPressed", false),
        new("secondaryoffhandbuttonpressed", "PlayerCmd_secondaryOffhandButtonPressed", false),
        new("playerads", "PlayerCmd_playerADS", false),
        new("isonground", "PlayerCmd_isOnGround", false),
        new("pingplayer", "PlayerCmd_pingPlayer", false),
        new("setviewmodel", "PlayerCmd_SetViewmodel", false),
        new("getviewmodel", "PlayerCmd_GetViewmodel", false),
        new("setoffhandsecondaryclass", "PlayerCmd_setOffhandSecondaryClass", false),
        new("getoffhandsecondaryclass", "PlayerCmd_getOffhandSecondaryClass", false),
        new("beginlocationselection", "PlayerCmd_BeginLocationSelection", false),
        new("endlocationselection", "PlayerCmd_EndLocationSelection", false),
        new("buttonpressed", "PlayerCmd_buttonPressedDEVONLY", false),
        new("sayall", "PlayerCmd_SayAll", false),
        new("sayteam", "PlayerCmd_SayTeam", false),
        new("showscoreboard", "PlayerCmd_showScoreboard", false),
        new("setspawnweapon", "PlayerCmd_setSpawnWeapon", false),
        new("dropitem", "PlayerCmd_dropItem", false),
        new("finishplayerdamage", "PlayerCmd_finishPlayerDamage", false),
        new("suicide", "PlayerCmd_Suicide", false),
        new("openmenu", "PlayerCmd_OpenMenu", false),
        new("openmenunomouse", "PlayerCmd_OpenMenuNoMouse", false),
        new("closemenu", "PlayerCmd_CloseMenu", false),
        new("closeingamemenu", "PlayerCmd_CloseInGameMenu", false),
        new("freezecontrols", "PlayerCmd_FreezeControls", false),
        new("disableweapons", "PlayerCmd_DisableWeapons", false),
        new("enableweapons", "PlayerCmd_EnableWeapons", false),
        new("setreverb", "PlayerCmd_SetReverb", false),
        new("deactivatereverb", "PlayerCmd_DeactivateReverb", false),
        new("setchannelvolumes", "PlayerCmd_SetChannelVolumes", false),
        new("deactivatechannelvolumes", "PlayerCmd_DeactivateChannelVolumes", false),
        new("setweaponammoclip", "PlayerCmd_SetWeaponAmmoClip", false),
        new("setweaponammostock", "PlayerCmd_SetWeaponAmmoStock", false),
        new("getweaponammoclip", "PlayerCmd_GetWeaponAmmoClip", false),
        new("getweaponammostock", "PlayerCmd_GetWeaponAmmoStock", false),
        new("anyammoforweaponmodes", "PlayerCmd_AnyAmmoForWeaponModes", false),
        new("iprintln", "iclientprintln", false),
        new("iprintlnbold", "iclientprintlnbold", false),
        new("spawn", "PlayerCmd_spawn", false),
        new("setentertime", "PlayerCmd_setEnterTime", false),
        new("cloneplayer", "PlayerCmd_ClonePlayer", false),
        new("setclientdvar", "PlayerCmd_SetClientDvar", false),
        new("setclientdvars", "PlayerCmd_SetClientDvars", false),
        new("playlocalsound", "ScrCmd_PlayLocalSound", false),
        new("stoplocalsound", "ScrCmd_StopLocalSound", false),
        new("istalking", "PlayerCmd_IsTalking", false),
        new("allowspectateteam", "PlayerCmd_AllowSpectateTeam", false),
        new("getguid", "PlayerCmd_GetGuid", false),
        new("getxuid", "PlayerCmd_GetXuid", false),
        new("allowads", "PlayerCmd_AllowADS", false),
        new("allowjump", "PlayerCmd_AllowJump", false),
        new("allowsprint", "PlayerCmd_AllowSprint", false),
        new("setspreadoverride", "PlayerCmd_SetSpreadOverride", false),
        new("resetspreadoverride", "PlayerCmd_ResetSpreadOverride", false),
        new("setactionslot", "PlayerCmd_SetActionSlot", false),
        new("getweaponslist", "PlayerCmd_GetWeaponsList", false),
        new("getweaponslistprimaries", "PlayerCmd_GetWeaponsListPrimaries", false),
        new("setperk", "PlayerCmd_SetPerk", false),
        new("hasperk", "PlayerCmd_HasPerk", false),
        new("clearperks", "PlayerCmd_ClearPerks", false),
        new("unsetperk", "PlayerCmd_UnsetPerk", false),
        new("updatescores", "PlayerCmd_UpdateScores", false),
        new("updatedmscores", "PlayerCmd_UpdateDMScores", false),
        new("setrank", "PlayerCmd_SetRank", false),
    ];

    private static readonly Registration[] ScriptEntityMethods =
    [
        new("moveto", "ScriptEntCmd_MoveTo", false),
        new("movex", "ScriptEntCmd_MoveX", false),
        new("movey", "ScriptEntCmd_MoveY", false),
        new("movez", "ScriptEntCmd_MoveZ", false),
        new("movegravity", "ScriptEntCmd_GravityMove", false),
        new("rotateto", "ScriptEntCmd_RotateTo", false),
        new("rotatepitch", "ScriptEntCmd_RotatePitch", false),
        new("rotateyaw", "ScriptEntCmd_RotateYaw", false),
        new("rotateroll", "ScriptEntCmd_RotateRoll", false),
        new("devaddpitch", "ScriptEntCmd_DevAddPitch", true),
        new("devaddyaw", "ScriptEntCmd_DevAddYaw", true),
        new("devaddroll", "ScriptEntCmd_DevAddRoll", true),
        new("vibrate", "ScriptEntCmd_Vibrate", false),
        new("rotatevelocity", "ScriptEntCmd_RotateVelocity", false),
        new("solid", "ScriptEntCmd_Solid", false),
        new("notsolid", "ScriptEntCmd_NotSolid", false),
        new("setcandamage", "ScriptEntCmd_SetCanDamage", false),
        new("physicslaunch", "ScriptEntCmd_PhysicsLaunch", false),
    ];

    private static readonly Registration[] HudElementMethods =
    [
        new("settext", "HECmd_SetText", false),
        new("clearalltextafterhudelem", "HECmd_ClearAllTextAfterHudElem", false),
        new("setshader", "HECmd_SetMaterial", false),
        new("settargetent", "HECmd_SetTargetEnt", false),
        new("cleartargetent", "HECmd_ClearTargetEnt", false),
        new("settimer", "HECmd_SetTimer", false),
        new("settimerup", "HECmd_SetTimerUp", false),
        new("settenthstimer", "HECmd_SetTenthsTimer", false),
        new("settenthstimerup", "HECmd_SetTenthsTimerUp", false),
        new("setclock", "HECmd_SetClock", false),
        new("setclockup", "HECmd_SetClockUp", false),
        new("setvalue", "HECmd_SetValue", false),
        new("setwaypoint", "HECmd_SetWaypoint", false),
        new("fadeovertime", "HECmd_FadeOverTime", false),
        new("scaleovertime", "HECmd_ScaleOverTime", false),
        new("moveovertime", "HECmd_MoveOverTime", false),
        new("reset", "HECmd_Reset", false),
        new("destroy", "HECmd_Destroy", false),
        new("setpulsefx", "HECmd_SetPulseFX", false),
        new("changefontscaleovertime", "HECmd_ChangeFontScaleOverTime", false),
    ];

    private static readonly Registration[] HelicopterMethods =
    [
        new("freehelicopter", "CMD_Heli_FreeHelicopter", false),
        new("setspeed", "CMD_VEH_SetSpeed", false),
        new("getspeed", "CMD_VEH_GetSpeed", false),
        new("getspeedmph", "CMD_VEH_GetSpeedMPH", false),
        new("resumespeed", "CMD_VEH_ResumeSpeed", false),
        new("setyawspeed", "CMD_VEH_SetYawSpeed", false),
        new("setmaxpitchroll", "CMD_VEH_SetMaxPitchRoll", false),
        new("setturningability", "CMD_VEH_SetTurningAbility", false),
        new("setairresistance", "CMD_VEH_SetAirResitance", false),
        new("sethoverparams", "CMD_VEH_SetHoverParams", false),
        new("setneargoalnotifydist", "CMD_VEH_NearGoalNotifyDist", false),
        new("setvehgoalpos", "CMD_VEH_SetGoalPos", false),
        new("setgoalyaw", "CMD_VEH_SetGoalYaw", false),
        new("cleargoalyaw", "CMD_VEH_ClearGoalYaw", false),
        new("settargetyaw", "CMD_VEH_SetTargetYaw", false),
        new("cleartargetyaw", "CMD_VEH_ClearTargetYaw", false),
        new("setlookatent", "CMD_VEH_SetLookAtEnt", false),
        new("clearlookatent", "CMD_VEH_ClearLookAtEnt", false),
        new("setvehweapon", "CMD_VEH_SetWeapon", false),
        new("fireweapon", "CMD_VEH_FireWeapon", false),
        new("setturrettargetvec", "CMD_VEH_SetTurretTargetVec", false),
        new("setturrettargetent", "CMD_VEH_SetTurretTargetEnt", false),
        new("clearturrettarget", "CMD_VEH_ClearTurretTargetEnt", false),
        new("setvehicleteam", "CMD_VEH_SetVehicleTeam", false),
        new("setdamagestage", "CMD_Heli_SetDamageStage", false),
    ];

    private static readonly Registration[] VmIntrinsics =
    [
        new("wait", "OP_wait", false),
        new("waittillframeend", "OP_waittillFrameEnd", false),
        new("waittill", "OP_waittill", false),
        new("waittillmatch", "OP_waittillmatch", false),
        new("notify", "OP_notify", false),
        new("endon", "OP_endon", false),
    ];
}
