namespace IW4.Assets.Assets.TechniqueSet;

public enum MaterialWorldVertexFormat : byte
{
    MTL_WORLDVERT_TEX_1_NRM_1 = 0x0,
    MTL_WORLDVERT_TEX_2_NRM_1 = 0x1,
    MTL_WORLDVERT_TEX_2_NRM_2 = 0x2,
    MTL_WORLDVERT_TEX_3_NRM_1 = 0x3,
    MTL_WORLDVERT_TEX_3_NRM_2 = 0x4,
    MTL_WORLDVERT_TEX_3_NRM_3 = 0x5,
    MTL_WORLDVERT_TEX_4_NRM_1 = 0x6,
    MTL_WORLDVERT_TEX_4_NRM_2 = 0x7,
    MTL_WORLDVERT_TEX_4_NRM_3 = 0x8,
    MTL_WORLDVERT_TEX_5_NRM_1 = 0x9,
    MTL_WORLDVERT_TEX_5_NRM_2 = 0xA,
    MTL_WORLDVERT_TEX_5_NRM_3 = 0xB
}