using System.Buffers.Binary;
using IW4.Assets.Assets.GfxMap;
using IW4.Assets.Assets.Image;

namespace MapConverter.Game.IW3.PC.Images;

/// <summary>
/// Preserves authored IW3 lighting atlases and lookup pixels in native PS3 layout,
/// without resizing them into v22 lightmap tiles or changing their brightness.
/// </summary>
internal static class Iw3Iwi6LightingCompiler
{
    private const int HeaderSize = 0x1c;
    private const byte Version = 6;
    private const byte IwiRgba = 0x01;
    private const byte IwiLuminance = 0x04;
    private const byte NoMipMaps = 0x02;

    internal static IReadOnlyList<GfxLightmapArray> CompileDirectory(
        string imageDirectory,
        int expectedAtlasCount)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(imageDirectory);
        if (expectedAtlasCount is < 0 or > 31)
            throw new ArgumentOutOfRangeException(nameof(expectedAtlasCount), "IW4 supports at most 31 lightmap arrays.");
        string fullDirectory = Path.GetFullPath(imageDirectory);
        if (!Directory.Exists(fullDirectory))
            throw new DirectoryNotFoundException($"The IW3 lighting image directory '{fullDirectory}' does not exist.");

        var expectedNames = new HashSet<string>(StringComparer.Ordinal);
        for (int index = 0; index < expectedAtlasCount; index++)
        {
            expectedNames.Add($"_lightmap{index}_primary.iwi");
            expectedNames.Add($"_lightmap{index}_secondary.iwi");
        }
        foreach (string imagePath in Directory.EnumerateFiles(fullDirectory, "_lightmap*.iwi"))
        {
            if (!expectedNames.Contains(Path.GetFileName(imagePath)))
                throw new InvalidDataException($"Unexpected IW3 lightmap image '{imagePath}' for {expectedAtlasCount} atlas arrays.");
        }
        foreach (string name in expectedNames)
        {
            if (!File.Exists(Path.Combine(fullDirectory, name)))
                throw new InvalidDataException($"The IW3 lighting image directory is missing '{name}'.");
        }

        var lightmaps = new GfxLightmapArray[expectedAtlasCount];
        for (int index = 0; index < expectedAtlasCount; index++)
        {
            GfxImageAsset primary = CompileImage(
                Path.Combine(fullDirectory, $"_lightmap{index}_primary.iwi"),
                $"*lightmap{index}_primary", IwiLuminance, GfxImageBaseFormat.B8,
                textureControl1: 0x0001a9ff, bytesPerPixel: 1, category: ImageCategory.Lightmap);
            GfxImageAsset secondary = CompileImage(
                Path.Combine(fullDirectory, $"_lightmap{index}_secondary.iwi"),
                $"*lightmap{index}_secondary", IwiRgba, GfxImageBaseFormat.A8R8G8B8,
                textureControl1: 0x0001aae4, bytesPerPixel: 4, category: ImageCategory.Lightmap);
            if (secondary.Width * 2 != primary.Width || secondary.Height != primary.Height)
                throw new InvalidDataException($"IW3 lightmap {index} requires primary and secondary atlases with a 2:1 horizontal size relationship.");
            lightmaps[index] = new GfxLightmapArray { Primary = primary, Secondary = secondary };
        }
        return Array.AsReadOnly(lightmaps);
    }

    internal static GfxImageAsset CompileOutdoor(string path) =>
        CompileImage(path, "$outdoor", IwiLuminance, GfxImageBaseFormat.B8,
            textureControl1: 0x0001a9ff, bytesPerPixel: 1, category: ImageCategory.AutoGenerated);

    private static GfxImageAsset CompileImage(
        string path,
        string name,
        byte expectedIwiFormat,
        GfxImageBaseFormat outputFormat,
        uint textureControl1,
        int bytesPerPixel,
        ImageCategory category)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(path);
        string fullPath = Path.GetFullPath(path);
        using FileStream stream = File.OpenRead(fullPath);
        if (stream.Length < HeaderSize)
            throw new InvalidDataException($"IW3 lighting image '{fullPath}' is shorter than its IWI6 header.");
        Span<byte> header = stackalloc byte[HeaderSize];
        stream.ReadExactly(header);
        if (header[0] != 'I' || header[1] != 'W' || header[2] != 'i' || header[3] != Version)
            throw new InvalidDataException($"IW3 lighting image '{fullPath}' is not an IWI6 image.");
        if (header[4] != expectedIwiFormat || header[5] != NoMipMaps)
            throw new NotSupportedException($"IW3 lighting image '{fullPath}' has format 0x{header[4]:X2}, flags 0x{header[5]:X2}; the authored non-mipmapped atlas profile is required.");
        ushort width = ReadDimension(header, 0x06, fullPath, "width");
        ushort height = ReadDimension(header, 0x08, fullPath, "height");
        ushort depth = ReadDimension(header, 0x0a, fullPath, "depth");
        if (depth != 1)
            throw new NotSupportedException($"IW3 lighting image '{fullPath}' has depth {depth}; expected 1.");
        int payloadByteCount = checked(width * height * bytesPerPixel);
        int expectedFileByteCount = checked(HeaderSize + payloadByteCount);
        uint declaredFileByteCount = BinaryPrimitives.ReadUInt32LittleEndian(header.Slice(0x0c, sizeof(uint)));
        if (stream.Length != expectedFileByteCount || declaredFileByteCount != expectedFileByteCount)
            throw new InvalidDataException($"IW3 lighting image '{fullPath}' contains {stream.Length:N0} bytes and declares {declaredFileByteCount:N0}; expected {expectedFileByteCount:N0}.");

        var linear = new byte[payloadByteCount];
        stream.ReadExactly(linear);
        if (bytesPerPixel == 4)
            GfxImagePixelLayout.ReverseFourBytePixelOrder(linear);
        byte[] payload = GfxImagePixelLayout.SwizzleMorton2D(linear, width, height, bytesPerPixel);
        return new GfxImageAsset
        {
            Format = (byte)outputFormat,
            LevelCount = 1,
            DimensionCount = GfxImageDimension.TwoDimensional,
            TextureControl1 = textureControl1,
            Width = width,
            Height = height,
            Depth = 1,
            MemoryLocation = GfxImageMemoryLocation.Local,
            MapType = MapType.TwoDimensional,
            TextureSemantic = TextureSemantic.Function,
            Category = category,
            CardMemory = checked((uint)payload.Length),
            BaseWidth = width,
            BaseHeight = height,
            BaseDepth = 1,
            BaseLevelCount = 1,
            Cached = GfxImageCached.No,
            PayloadByteCount = payload.Length,
            PayloadBytes = payload,
            Name = name
        };
    }

    private static ushort ReadDimension(ReadOnlySpan<byte> header, int offset, string path, string fieldName)
    {
        ushort value = BinaryPrimitives.ReadUInt16LittleEndian(header.Slice(offset, sizeof(ushort)));
        return value != 0 ? value : throw new InvalidDataException($"IW3 lighting image '{path}' {fieldName} cannot be zero.");
    }
}
