using IW4.Assets.Assets.Image;

namespace MapConverter.Game.IW3.PC.Images;

/// <summary>
/// Authors the source-free PS3 backing image regenerated by the IW4 water
/// runtime. Its dimensions come from the source MaterialWater simulation.
/// </summary>
internal static class Iw3WaterImageCompiler
{
    private const byte WaterFormat =
        (byte)((byte)GfxImageBaseFormat.B8 | (byte)GfxImageFormatFlags.Linear);
    private const uint WaterTextureControl1 = 0x0001a9ff;

    internal static GfxImageAsset Compile(
        string imageName,
        int width,
        int height)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(imageName);
        if (imageName[0] == ',' || imageName.Contains('/') ||
            imageName.Contains('\\') || imageName.Contains('\0') ||
            !string.Equals(imageName, imageName.Trim(), StringComparison.Ordinal))
        {
            throw new ArgumentException(
                "A water image requires an owned unqualified wire name.",
                nameof(imageName));
        }
        if (width is < 1 or > ushort.MaxValue)
            throw new ArgumentOutOfRangeException(nameof(width));
        if (height is < 1 or > ushort.MaxValue)
            throw new ArgumentOutOfRangeException(nameof(height));
        if (!IsPowerOfTwo(width) || !IsPowerOfTwo(height))
        {
            throw new NotSupportedException(
                $"Water image '{imageName}' dimensions {width}x{height} are not power-of-two.");
        }

        byte levelCount = checked((byte)ComputeFullMipCount(width, height));
        ushort encodedWidth = checked((ushort)width);
        ushort encodedHeight = checked((ushort)height);
        int payloadByteCount = GfxImagePixelLayout.ComputePayloadByteCount(
            new GfxImageFormat(WaterFormat),
            levelCount,
            isCubemap: false,
            new GfxImageTextureRemap(WaterTextureControl1),
            encodedWidth,
            encodedHeight,
            depth: 1);
        if (payloadByteCount <= 0)
        {
            throw new InvalidDataException(
                $"Water image '{imageName}' has no proven PS3 payload layout.");
        }

        return new GfxImageAsset
        {
            Format = WaterFormat,
            LevelCount = levelCount,
            DimensionCount = GfxImageDimension.TwoDimensional,
            TextureControl1 = WaterTextureControl1,
            Width = encodedWidth,
            Height = encodedHeight,
            Depth = 1,
            MemoryLocation = GfxImageMemoryLocation.Main,
            RenderTargetPitch = checked((uint)width),
            MapType = MapType.TwoDimensional,
            TextureSemantic = TextureSemantic.WaterMap,
            Category = ImageCategory.Water,
            UseSrgbReads = 0,
            CardMemory = checked((uint)payloadByteCount),
            BaseWidth = encodedWidth,
            BaseHeight = encodedHeight,
            BaseDepth = 1,
            BaseLevelCount = levelCount,
            Cached = GfxImageCached.No,
            StreamData = [],
            PayloadByteCount = payloadByteCount,
            PayloadBytes = new byte[payloadByteCount],
            Name = imageName
        };
    }

    private static bool IsPowerOfTwo(int value) =>
        (value & (value - 1)) == 0;

    private static int ComputeFullMipCount(int width, int height)
    {
        int count = 1;
        while (width > 1 || height > 1)
        {
            width = Math.Max(1, width / 2);
            height = Math.Max(1, height / 2);
            count++;
        }
        return count;
    }
}
