<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\IW4.AssetExchange\IW4.AssetExchange.csproj" />
    <ProjectReference Include="..\IW4.Assets\IW4.Assets.csproj" />
    <ProjectReference Include="..\IW4.Runtime\IW4.Runtime.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
