namespace IW4.Assets.Assets.Image;

/// <summary>IW4 image ownership and lifetime category.</summary>
public enum ImageCategory : byte
{
    Unknown = 0,
    AutoGenerated = 1,
    Lightmap = 2,
    LoadFromFile = 3,
    Raw = 4,
    FirstUnmanaged = 5,
    Water = FirstUnmanaged,
    RenderTarget = 6,
    Temporary = 7
}
