<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\IW4.FastFiles\IW4.FastFiles.csproj" />
    <ProjectReference Include="..\IW4.Assets\IW4.Assets.csproj" />
    <ProjectReference Include="..\IW4.Runtime\IW4.Runtime.csproj" />
    <ProjectReference Include="..\IW4.FastFiles.Streaming\IW4.FastFiles.Streaming.csproj" />
    <ProjectReference Include="..\IW4.Linker\IW4.Linker.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
