using IW4.Game.Assets.Image;
using IW4.Game.Assets.Material;
using IW4.Game.Codecs.Image;
namespace IW4.Game.Codecs.GfxMap;

public static class GfxReflectionProbeCodec
{
    public const int ReflectionProbeEdgeLength = 64;
    public const int ReflectionProbeMipCount = 7;
    public const int ReflectionProbeFaceCount = 6;
    internal const int ReflectionProbeFacePixelByteCount = 21_844;
    internal const int ReflectionProbeFaceStride = 21_888;
    internal const int ReflectionProbeRuntimeByteCount = ReflectionProbeFaceCount * ReflectionProbeFaceStride;

    /// <summary>Creates the engine's default probe, including each face's native padding.</summary>
    public static GfxImageAsset CreateDefaultImage()
    {
        var payload = new byte[ReflectionProbeRuntimeByteCount];
        for (int face = 0; face < ReflectionProbeFaceCount; face++)
        for (int pixel = 0; pixel < ReflectionProbeFacePixelByteCount; pixel += 4)
        {
            int offset = face * ReflectionProbeFaceStride + pixel;
            payload[offset] = byte.MaxValue;
            payload[offset + 1] = byte.MaxValue;
        }
        return CreateImage(0, payload);
    }

    /// <summary>Encodes six linear RGBA faces per mip into the native padded, swizzled cubemap.</summary>
    public static GfxImageAsset CreateImage(int index, IReadOnlyList<ReadOnlyMemory<byte>> rgbaMips)
    {
        if (rgbaMips.Count != ReflectionProbeMipCount)
            throw new ArgumentException("A reflection probe requires all seven mip levels.");
        var payload = new byte[ReflectionProbeRuntimeByteCount];
        int faceMipOffset = 0;
        for (int mip = 0; mip < ReflectionProbeMipCount; mip++)
        {
            int edge = System.Math.Max(1, ReflectionProbeEdgeLength >> mip);
            int faceBytes = edge * edge * 4;
            if (rgbaMips[mip].Length != ReflectionProbeFaceCount * faceBytes)
                throw new ArgumentException($"Reflection-probe mip {mip} must contain six {edge}x{edge} RGBA faces.");
            for (int face = 0; face < ReflectionProbeFaceCount; face++)
            {
                byte[] linear = rgbaMips[mip].Slice(face * faceBytes, faceBytes).ToArray();
                GfxImageChannelCodec.RgbaToArgb(linear);
                GfxImagePixelLayout.SwizzleMorton2D(linear, edge, edge, 4)
                    .CopyTo(payload, face * ReflectionProbeFaceStride + faceMipOffset);
            }
            faceMipOffset += faceBytes;
        }
        return CreateImage(index, payload);
    }

    internal static GfxImageAsset CreateImage(
        int index,
        byte[] payload) => new()
    {
        Format = (byte)GfxImageBaseFormat.A8R8G8B8,
        LevelCount = ReflectionProbeMipCount,
        DimensionCount = GfxImageDimension.TwoDimensional,
        MultiFaceControl = 1,
        TextureControl1 = 0x0001AAE4,
        Width = ReflectionProbeEdgeLength,
        Height = ReflectionProbeEdgeLength,
        Depth = 1,
        MemoryLocation = GfxImageMemoryLocation.Local,
        MapType = MapType.Cube,
        TextureSemantic = TextureSemantic.Function,
        Category = ImageCategory.AutoGenerated,
        CardMemory = checked((uint)payload.Length),
        BaseWidth = ReflectionProbeEdgeLength,
        BaseHeight = ReflectionProbeEdgeLength,
        BaseDepth = 1,
        BaseLevelCount = ReflectionProbeMipCount,
        Cached = GfxImageCached.No,
        PayloadByteCount = payload.Length,
        PayloadBytes = payload,
        Name = $"*reflection_probe{index}"
    };
}
