namespace IW4.Gsc.Syntax;

internal static class GscTokenDisplay
{
    internal static string Describe(GscTokenKind token) => token switch
    {
        GscTokenKind.EndOfFile => "end of file",
        GscTokenKind.BadToken => "a valid token",
        GscTokenKind.Identifier => "an identifier",
        GscTokenKind.String => "a string",
        GscTokenKind.LocalizedString => "a localized string",
        GscTokenKind.Integer => "an integer",
        GscTokenKind.Float => "a number",
        GscTokenKind.Path => "a script path",
        GscTokenKind.OpenBrace => "'{'",
        GscTokenKind.CloseBrace => "'}'",
        GscTokenKind.OpenParenthesis => "'('",
        GscTokenKind.CloseParenthesis => "')'",
        GscTokenKind.OpenBracket => "'['",
        GscTokenKind.CloseBracket => "']'",
        GscTokenKind.LogicalOr => "'||'",
        GscTokenKind.LogicalAnd => "'&&'",
        GscTokenKind.BitwiseOr => "'|'",
        GscTokenKind.BitwiseXor => "'^'",
        GscTokenKind.BitwiseAnd => "'&'",
        GscTokenKind.Equals => "'=='",
        GscTokenKind.NotEquals => "'!='",
        GscTokenKind.LessThan => "'<'",
        GscTokenKind.GreaterThan => "'>'",
        GscTokenKind.LessThanOrEqual => "'<='",
        GscTokenKind.GreaterThanOrEqual => "'>='",
        GscTokenKind.ShiftLeft => "'<<'",
        GscTokenKind.ShiftRight => "'>>'",
        GscTokenKind.Plus => "'+'",
        GscTokenKind.Minus => "'-'",
        GscTokenKind.Multiply => "'*'",
        GscTokenKind.Divide => "'/'",
        GscTokenKind.Modulo => "'%'",
        GscTokenKind.LogicalNot => "'!'",
        GscTokenKind.BitwiseNot => "'~'",
        GscTokenKind.Dot => "'.'",
        GscTokenKind.Comma => "','",
        GscTokenKind.Colon => "':'",
        GscTokenKind.Semicolon => "';'",
        GscTokenKind.Assign => "'='",
        GscTokenKind.QuestionMark => "'?'",
        GscTokenKind.ReturnKeyword => "'return'",
        GscTokenKind.WaitKeyword => "'wait'",
        GscTokenKind.ThreadKeyword => "'thread'",
        GscTokenKind.ChildThreadKeyword => "'childthread'",
        GscTokenKind.CallKeyword => "'call'",
        GscTokenKind.UndefinedKeyword => "'undefined'",
        GscTokenKind.SelfKeyword => "'self'",
        GscTokenKind.ThisThreadKeyword => "'thisthread'",
        GscTokenKind.LevelKeyword => "'level'",
        GscTokenKind.GameKeyword => "'game'",
        GscTokenKind.AnimKeyword => "'anim'",
        GscTokenKind.IfKeyword => "'if'",
        GscTokenKind.ElseKeyword => "'else'",
        GscTokenKind.WhileKeyword => "'while'",
        GscTokenKind.ForKeyword => "'for'",
        GscTokenKind.ForeachKeyword => "'foreach'",
        GscTokenKind.InKeyword => "'in'",
        GscTokenKind.Increment => "'++'",
        GscTokenKind.Decrement => "'--'",
        GscTokenKind.OrAssign => "'|='",
        GscTokenKind.XorAssign => "'^='",
        GscTokenKind.AndAssign => "'&='",
        GscTokenKind.ShiftLeftAssign => "'<<='",
        GscTokenKind.ShiftRightAssign => "'>>='",
        GscTokenKind.AddAssign => "'+='",
        GscTokenKind.SubtractAssign => "'-='",
        GscTokenKind.MultiplyAssign => "'*='",
        GscTokenKind.DivideAssign => "'/='",
        GscTokenKind.ModuloAssign => "'%='",
        GscTokenKind.Size => "'.size'",
        GscTokenKind.UsingAnimTreeDirective => "'#using_animtree'",
        GscTokenKind.AnimTreeDirective => "'#animtree'",
        GscTokenKind.IncludeDirective => "'#include'",
        GscTokenKind.Scope => "'::'",
        GscTokenKind.WaitTillKeyword => "'waittill'",
        GscTokenKind.WaitTillMatchKeyword => "'waittillmatch'",
        GscTokenKind.WaitTillFrameEndKeyword => "'waittillframeend'",
        GscTokenKind.NotifyKeyword => "'notify'",
        GscTokenKind.SwitchKeyword => "'switch'",
        GscTokenKind.CaseKeyword => "'case'",
        GscTokenKind.DefaultKeyword => "'default'",
        GscTokenKind.BreakKeyword => "'break'",
        GscTokenKind.ContinueKeyword => "'continue'",
        GscTokenKind.EndOnKeyword => "'endon'",
        GscTokenKind.FalseKeyword => "'false'",
        GscTokenKind.TrueKeyword => "'true'",
        GscTokenKind.BreakpointKeyword => "'breakpoint'",
        GscTokenKind.ProfileBeginKeyword => "'prof_begin'",
        GscTokenKind.ProfileEndKeyword => "'prof_end'",
        GscTokenKind.DeveloperBlockOpen => "'/#'",
        GscTokenKind.DeveloperBlockClose => "'#/'",
        GscTokenKind.Dollar => "'$'",
        GscTokenKind.BreakOnKeyword => "'breakon'",
        _ => "a valid token"
    };
}
