<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\IW4.Assets\IW4.Assets.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Compile Remove="SourceFormat\ISourceExchange.cs" />
      <Compile Remove="SourceFormat\SourceExchange.cs" />
    </ItemGroup>

</Project>
