using System.Buffers.Binary;
using System.Text;
using IW4.Assets.Assets.ColMap;
using IW4.Assets.Assets.Physics;
using IW4.Assets.Math;

namespace IW4Map;

internal static class D3dbspCollisionCodec
{
    private const int DiskPlaneSize = 16;
    private const int DiskNodeSize = 36;
    private const int DiskBrushSize = 4;
    private const int DiskBrushSideSize = 8;
    private const int DiskLeafBrushSize = 4;
    private const int DiskLeafSurfaceSize = 4;
    private const int DiskCollisionVertSize = 12;
    private const int DiskCollisionIndexSize = 2;
    private const int DiskCollisionBorderSize = 28;
    private const int DiskCollisionAabbSize = 32;
    private const int DiskMaterialSize = 72;

    public static IReadOnlyList<CPlane> DecodePlanes(ReadOnlySpan<byte> data)
    {
        int count = GetElementCount(data, DiskPlaneSize, "collision plane");
        var planes = new CPlane[count];
        for (int index = 0; index < planes.Length; index++)
        {
            ReadOnlySpan<byte> row = data.Slice(index * DiskPlaneSize, DiskPlaneSize);
            Vec3 normal = ReadVec3(row, 0);
            planes[index] = new CPlane
            {
                Normal = normal,
                Dist = ReadSingle(row, 12),
                Type = normal.X == 1.0f
                    ? (byte)0
                    : normal.Y == 1.0f
                        ? (byte)1
                        : normal.Z == 1.0f
                            ? (byte)2
                            : (byte)3,
                // Stock IW4 map fastfiles serialize this byte as zero. It is not
                // the sign mask generated by the IW3 collision loader.
                SignBits = 0,
                Pad12 = new byte[2]
            };
        }

        return Array.AsReadOnly(planes);
    }

    public static IReadOnlyList<CNode> DecodeNodes(
        ReadOnlySpan<byte> data,
        IReadOnlyList<CPlane> planes)
    {
        ArgumentNullException.ThrowIfNull(planes);
        int count = GetElementCount(data, DiskNodeSize, "collision node");
        var nodes = new CNode[count];
        for (int index = 0; index < nodes.Length; index++)
        {
            ReadOnlySpan<byte> row = data.Slice(index * DiskNodeSize, DiskNodeSize);
            int planeIndex = BinaryPrimitives.ReadInt32LittleEndian(row);
            if ((uint)planeIndex >= (uint)planes.Count)
            {
                throw new InvalidDataException(
                    $"Collision node row {index} references plane {planeIndex}; the plane table has {planes.Count} rows.");
            }

            nodes[index] = new CNode
            {
                Plane = planes[planeIndex],
                Children = new[]
                {
                    ReadInt16Checked(row, 4, index, 0),
                    ReadInt16Checked(row, 8, index, 1)
                }
            };
        }

        return Array.AsReadOnly(nodes);
    }

    public static IReadOnlyList<ClipMaterial> DecodeMaterials(ReadOnlySpan<byte> data)
    {
        int count = GetElementCount(data, DiskMaterialSize, "collision material");
        var materials = new ClipMaterial[count];
        for (int index = 0; index < materials.Length; index++)
        {
            ReadOnlySpan<byte> row = data.Slice(index * DiskMaterialSize, DiskMaterialSize);
            int nameLength = row[..64].IndexOf((byte)0);
            if (nameLength < 0)
            {
                throw new InvalidDataException(
                    $"Collision material row {index} has no terminator in its 64-byte name field.");
            }

            materials[index] = new ClipMaterial
            {
                Name = Encoding.Latin1.GetString(row[..nameLength]),
                SurfaceFlags = BinaryPrimitives.ReadInt32LittleEndian(row[64..]),
                // IW4 retains the disk contents flags. The IW3 runtime loader's
                // 0xDFFFFFFB mask is not part of the IW4 linked asset graph.
                Contents = BinaryPrimitives.ReadInt32LittleEndian(row[68..])
            };
        }

        return Array.AsReadOnly(materials);
    }

    public static IReadOnlyList<byte> DecodeBrushEdges(ReadOnlySpan<byte> data) =>
        Array.AsReadOnly(data.ToArray());

    public static (
        IReadOnlyList<CBrushSide> BrushSides,
        IReadOnlyList<CBrush> Brushes,
        IReadOnlyList<Bounds> BrushBounds,
        IReadOnlyList<uint> BrushContents) DecodeBrushes(
            ReadOnlySpan<byte> diskBrushes,
            ReadOnlySpan<byte> diskBrushSides,
            ReadOnlySpan<byte> diskSideEdgeCounts,
            IReadOnlyList<byte> brushEdges,
            IReadOnlyList<CPlane> planes,
            IReadOnlyList<ClipMaterial> materials,
            IReadOnlyList<ushort> glassPieceIndices)
    {
        ArgumentNullException.ThrowIfNull(brushEdges);
        ArgumentNullException.ThrowIfNull(planes);
        ArgumentNullException.ThrowIfNull(materials);
        ArgumentNullException.ThrowIfNull(glassPieceIndices);

        int brushCount = GetElementCount(diskBrushes, DiskBrushSize, "collision brush");
        int diskSideCount = GetElementCount(
            diskBrushSides,
            DiskBrushSideSize,
            "collision brush side");
        int axialSideCount = checked(brushCount * 6);
        if (diskSideEdgeCounts.Length != diskSideCount)
        {
            throw new InvalidDataException(
                $"The brush-side table has {diskSideCount} rows, but the edge-count lump has {diskSideEdgeCounts.Length} bytes.");
        }
        if (diskSideCount < axialSideCount)
        {
            throw new InvalidDataException(
                $"The brush-side table has {diskSideCount} rows; {brushCount} brushes require at least {brushCount * 6} axial sides.");
        }
        if (glassPieceIndices.Count != brushCount)
        {
            throw new InvalidDataException(
                $"The glass-piece index table has {glassPieceIndices.Count} rows; expected {brushCount}.");
        }

        var rootSides = new CBrushSide[diskSideCount - axialSideCount];
        var brushes = new CBrush[brushCount];
        var bounds = new Bounds[brushCount];
        var contents = new uint[brushCount];
        int diskSideIndex = 0;
        int rootSideIndex = 0;
        int edgeIndex = 0;
        for (int brushIndex = 0; brushIndex < brushCount; brushIndex++)
        {
            ReadOnlySpan<byte> brushRow = diskBrushes.Slice(
                brushIndex * DiskBrushSize,
                DiskBrushSize);
            int diskNumSides = BinaryPrimitives.ReadInt16LittleEndian(brushRow);
            if (diskNumSides < 6 || diskSideIndex > diskSideCount - diskNumSides)
            {
                throw new InvalidDataException(
                    $"Collision brush row {brushIndex} declares invalid side count {diskNumSides}.");
            }

            int brushMaterial = BinaryPrimitives.ReadInt16LittleEndian(brushRow[2..]);
            ValidateMaterialIndex(brushMaterial, materials.Count, $"Collision brush row {brushIndex}");

            var mins = new float[3];
            var maxs = new float[3];
            var axialMaterials = new short[6];
            var axialOffsets = new byte[6];
            var axialEdgeCounts = new byte[6];
            int brushEdgeStart = edgeIndex;
            int brushEdgeOffset = 0;
            for (int axis = 0; axis < 3; axis++)
            {
                for (int direction = 0; direction < 2; direction++)
                {
                    ReadOnlySpan<byte> sideRow = diskBrushSides.Slice(
                        diskSideIndex * DiskBrushSideSize,
                        DiskBrushSideSize);
                    float bound = ReadSingle(sideRow, 0);
                    if (direction == 0)
                        mins[axis] = bound;
                    else
                        maxs[axis] = bound;

                    int materialIndex = BinaryPrimitives.ReadInt32LittleEndian(sideRow[4..]);
                    ValidateMaterialIndex(
                        materialIndex,
                        materials.Count,
                        $"Collision brush row {brushIndex} axial side {axis * 2 + direction}");
                    if (materialIndex > short.MaxValue)
                    {
                        throw new InvalidDataException(
                            $"Collision brush row {brushIndex} axial material {materialIndex} exceeds the IW4 short range.");
                    }

                    int outputIndex = axis + direction * 3;
                    axialMaterials[outputIndex] = (short)materialIndex;
                    axialOffsets[outputIndex] = ToByteOffset(
                        brushEdgeOffset,
                        brushIndex,
                        $"axial side {axis * 2 + direction}");
                    byte edgeCount = diskSideEdgeCounts[diskSideIndex];
                    axialEdgeCounts[outputIndex] = edgeCount;
                    AdvanceEdges(brushEdges.Count, edgeCount, brushIndex, ref edgeIndex, ref brushEdgeOffset);
                    diskSideIndex++;
                }
            }

            int numSides = diskNumSides - 6;
            var brushSides = new CBrushSide[numSides];
            for (int sideIndex = 0; sideIndex < brushSides.Length; sideIndex++)
            {
                ReadOnlySpan<byte> sideRow = diskBrushSides.Slice(
                    diskSideIndex * DiskBrushSideSize,
                    DiskBrushSideSize);
                int planeIndex = BinaryPrimitives.ReadInt32LittleEndian(sideRow);
                if ((uint)planeIndex >= (uint)planes.Count)
                {
                    throw new InvalidDataException(
                        $"Collision brush row {brushIndex} side {sideIndex} references plane {planeIndex}; the plane table has {planes.Count} rows.");
                }

                int materialIndex = BinaryPrimitives.ReadInt32LittleEndian(sideRow[4..]);
                ValidateMaterialIndex(
                    materialIndex,
                    materials.Count,
                    $"Collision brush row {brushIndex} side {sideIndex}");
                if (materialIndex > ushort.MaxValue)
                {
                    throw new InvalidDataException(
                        $"Collision brush row {brushIndex} side {sideIndex} material {materialIndex} exceeds the IW4 ushort range.");
                }

                byte edgeCount = diskSideEdgeCounts[diskSideIndex];
                var side = new CBrushSide
                {
                    Plane = planes[planeIndex],
                    MaterialNum = (ushort)materialIndex,
                    FirstAdjacentSideOffset = ToByteOffset(
                        brushEdgeOffset,
                        brushIndex,
                        $"side {sideIndex}"),
                    EdgeCount = edgeCount
                };
                brushSides[sideIndex] = side;
                rootSides[rootSideIndex++] = side;
                AdvanceEdges(brushEdges.Count, edgeCount, brushIndex, ref edgeIndex, ref brushEdgeOffset);
                diskSideIndex++;
            }

            var adjacentSides = new byte[brushEdgeOffset];
            for (int index = 0; index < adjacentSides.Length; index++)
                adjacentSides[index] = brushEdges[brushEdgeStart + index];

            if (numSides > ushort.MaxValue)
            {
                throw new InvalidDataException(
                    $"Collision brush row {brushIndex} has {numSides} non-axial sides; IW4 supports at most {ushort.MaxValue}.");
            }

            brushes[brushIndex] = new CBrush
            {
                NumSides = (ushort)numSides,
                GlassPieceIndex = glassPieceIndices[brushIndex],
                Sides = Array.AsReadOnly(brushSides),
                BaseAdjacentSide = Array.AsReadOnly(adjacentSides),
                AxialMaterialNum = Array.AsReadOnly(axialMaterials),
                FirstAdjacentSideOffsets = Array.AsReadOnly(axialOffsets),
                EdgeCount = Array.AsReadOnly(axialEdgeCounts)
            };
            bounds[brushIndex] = DecodeBounds(mins, maxs);
            contents[brushIndex] = unchecked((uint)materials[brushMaterial].Contents);
        }

        if (diskSideIndex != diskSideCount || rootSideIndex != rootSides.Length)
        {
            throw new InvalidDataException(
                $"Collision brushes consumed {diskSideIndex} of {diskSideCount} disk sides.");
        }
        if (edgeIndex != brushEdges.Count)
        {
            throw new InvalidDataException(
                $"Collision brushes consumed {edgeIndex} of {brushEdges.Count} adjacency bytes.");
        }

        return (
            Array.AsReadOnly(rootSides),
            Array.AsReadOnly(brushes),
            Array.AsReadOnly(bounds),
            Array.AsReadOnly(contents));
    }

    public static IReadOnlyList<ushort> DecodeLeafBrushes(ReadOnlySpan<byte> data)
    {
        int count = GetElementCount(data, DiskLeafBrushSize, "leaf brush");
        var leafBrushes = new ushort[count];
        for (int index = 0; index < leafBrushes.Length; index++)
        {
            uint brushIndex = BinaryPrimitives.ReadUInt32LittleEndian(
                data.Slice(index * DiskLeafBrushSize, DiskLeafBrushSize));
            if (brushIndex > ushort.MaxValue)
            {
                throw new InvalidDataException(
                    $"Leaf brush row {index} references brush {brushIndex}, which exceeds the IW4 ushort range.");
            }

            leafBrushes[index] = (ushort)brushIndex;
        }

        return Array.AsReadOnly(leafBrushes);
    }

    public static IReadOnlyList<uint> DecodeLeafSurfaces(ReadOnlySpan<byte> data)
    {
        int count = GetElementCount(data, DiskLeafSurfaceSize, "leaf surface");
        var leafSurfaces = new uint[count];
        for (int index = 0; index < leafSurfaces.Length; index++)
        {
            leafSurfaces[index] = BinaryPrimitives.ReadUInt32LittleEndian(
                data.Slice(index * DiskLeafSurfaceSize, DiskLeafSurfaceSize));
        }

        return Array.AsReadOnly(leafSurfaces);
    }

    public static IReadOnlyList<Vec3> DecodeCollisionVerts(ReadOnlySpan<byte> data)
    {
        int count = GetElementCount(data, DiskCollisionVertSize, "collision vertex");
        var verts = new Vec3[count];
        for (int index = 0; index < verts.Length; index++)
        {
            verts[index] = ReadVec3(
                data.Slice(index * DiskCollisionVertSize, DiskCollisionVertSize),
                0);
        }

        return Array.AsReadOnly(verts);
    }

    public static IReadOnlyList<ushort> DecodeCollisionTris(ReadOnlySpan<byte> data)
    {
        int count = GetElementCount(data, DiskCollisionIndexSize, "collision triangle index");
        if (count % 3 != 0)
        {
            throw new InvalidDataException(
                $"Collision triangle index count {count} is not divisible by 3.");
        }

        var triIndices = new ushort[count];
        for (int index = 0; index < triIndices.Length; index++)
        {
            triIndices[index] = BinaryPrimitives.ReadUInt16LittleEndian(
                data.Slice(index * DiskCollisionIndexSize, DiskCollisionIndexSize));
        }

        return Array.AsReadOnly(triIndices);
    }

    public static IReadOnlyList<byte> DecodeCollisionEdgeWalkable(ReadOnlySpan<byte> data) =>
        Array.AsReadOnly(data.ToArray());

    public static IReadOnlyList<CollisionBorder> DecodeCollisionBorders(ReadOnlySpan<byte> data)
    {
        int count = GetElementCount(data, DiskCollisionBorderSize, "collision border");
        var borders = new CollisionBorder[count];
        for (int index = 0; index < borders.Length; index++)
        {
            ReadOnlySpan<byte> row = data.Slice(
                index * DiskCollisionBorderSize,
                DiskCollisionBorderSize);
            borders[index] = new CollisionBorder
            {
                DistEq = new[]
                {
                    ReadSingle(row, 0),
                    ReadSingle(row, 4),
                    ReadSingle(row, 8)
                },
                ZBase = ReadSingle(row, 12),
                ZSlope = ReadSingle(row, 16),
                Start = ReadSingle(row, 20),
                Length = ReadSingle(row, 24)
            };
        }

        return Array.AsReadOnly(borders);
    }

    public static IReadOnlyList<CollisionAabbTree> DecodeCollisionAabbs(ReadOnlySpan<byte> data)
    {
        int count = GetElementCount(data, DiskCollisionAabbSize, "collision AABB");
        var aabbTrees = new CollisionAabbTree[count];
        for (int index = 0; index < aabbTrees.Length; index++)
        {
            ReadOnlySpan<byte> row = data.Slice(
                index * DiskCollisionAabbSize,
                DiskCollisionAabbSize);
            aabbTrees[index] = new CollisionAabbTree
            {
                Origin = ReadVec3(row, 0),
                HalfSize = ReadVec3(row, 12),
                MaterialIndex = BinaryPrimitives.ReadUInt16LittleEndian(row[24..]),
                ChildCount = BinaryPrimitives.ReadUInt16LittleEndian(row[26..]),
                FirstChildOrPartitionIndex = BinaryPrimitives.ReadInt32LittleEndian(row[28..])
            };
        }

        return Array.AsReadOnly(aabbTrees);
    }

    public static byte[] EncodePlanes(IReadOnlyList<CPlane> planes)
    {
        ArgumentNullException.ThrowIfNull(planes);
        var data = new byte[checked(planes.Count * DiskPlaneSize)];
        for (int index = 0; index < planes.Count; index++)
        {
            CPlane plane = planes[index] ??
                throw new InvalidDataException($"Collision plane row {index} is null.");
            Span<byte> row = data.AsSpan(index * DiskPlaneSize, DiskPlaneSize);
            WriteVec3(row, 0, plane.Normal);
            WriteSingle(row, 12, plane.Dist);
        }

        return data;
    }

    public static byte[] EncodeBrushEdges(IReadOnlyList<byte> brushEdges) =>
        EncodeBytes(brushEdges);

    public static byte[] EncodeBrushSideEdgeCounts(IReadOnlyList<CBrush> brushes)
    {
        ArgumentNullException.ThrowIfNull(brushes);
        int byteCount = 0;
        for (int brushIndex = 0; brushIndex < brushes.Count; brushIndex++)
        {
            CBrush brush = brushes[brushIndex] ??
                throw new InvalidDataException($"Collision brush row {brushIndex} is null.");
            if (brush.Sides.Count != brush.NumSides)
            {
                throw new InvalidDataException(
                    $"Collision brush row {brushIndex} has {brush.Sides.Count} non-axial sides; expected {brush.NumSides}.");
            }
            if (brush.EdgeCount.Count != 6)
            {
                throw new InvalidDataException(
                    $"Collision brush row {brushIndex} has {brush.EdgeCount.Count} axial edge counts; expected 6.");
            }

            byteCount = checked(byteCount + 6 + brush.NumSides);
        }

        var data = new byte[byteCount];
        int offset = 0;
        for (int brushIndex = 0; brushIndex < brushes.Count; brushIndex++)
        {
            CBrush brush = brushes[brushIndex];
            // The fastfile stores edgeCount[2][3] direction-major; the BSP lists both directions per axis.
            for (int axis = 0; axis < 3; axis++)
            {
                data[offset++] = brush.EdgeCount[axis];
                data[offset++] = brush.EdgeCount[axis + 3];
            }
            for (int sideIndex = 0; sideIndex < brush.Sides.Count; sideIndex++)
            {
                CBrushSide side = brush.Sides[sideIndex] ??
                    throw new InvalidDataException(
                        $"Collision brush row {brushIndex} side {sideIndex} is null.");
                data[offset++] = side.EdgeCount;
            }
        }

        return data;
    }

    public static byte[] EncodeLeafBrushes(IReadOnlyList<ushort> leafBrushes)
    {
        ArgumentNullException.ThrowIfNull(leafBrushes);
        var data = new byte[checked(leafBrushes.Count * DiskLeafBrushSize)];
        for (int index = 0; index < leafBrushes.Count; index++)
        {
            BinaryPrimitives.WriteUInt32LittleEndian(
                data.AsSpan(index * DiskLeafBrushSize, DiskLeafBrushSize),
                leafBrushes[index]);
        }

        return data;
    }

    public static byte[] EncodeLeafSurfaces(IReadOnlyList<uint> leafSurfaces)
    {
        ArgumentNullException.ThrowIfNull(leafSurfaces);
        var data = new byte[checked(leafSurfaces.Count * DiskLeafSurfaceSize)];
        for (int index = 0; index < leafSurfaces.Count; index++)
        {
            BinaryPrimitives.WriteUInt32LittleEndian(
                data.AsSpan(index * DiskLeafSurfaceSize, DiskLeafSurfaceSize),
                leafSurfaces[index]);
        }

        return data;
    }

    public static byte[] EncodeCollisionVerts(IReadOnlyList<Vec3> verts)
    {
        ArgumentNullException.ThrowIfNull(verts);
        var data = new byte[checked(verts.Count * DiskCollisionVertSize)];
        for (int index = 0; index < verts.Count; index++)
        {
            WriteVec3(
                data.AsSpan(index * DiskCollisionVertSize, DiskCollisionVertSize),
                0,
                verts[index]);
        }

        return data;
    }

    public static byte[] EncodeCollisionTris(IReadOnlyList<ushort> triIndices)
    {
        ArgumentNullException.ThrowIfNull(triIndices);
        if (triIndices.Count % 3 != 0)
        {
            throw new InvalidDataException(
                $"Collision triangle index count {triIndices.Count} is not divisible by 3.");
        }

        var data = new byte[checked(triIndices.Count * DiskCollisionIndexSize)];
        for (int index = 0; index < triIndices.Count; index++)
        {
            BinaryPrimitives.WriteUInt16LittleEndian(
                data.AsSpan(index * DiskCollisionIndexSize, DiskCollisionIndexSize),
                triIndices[index]);
        }

        return data;
    }

    public static byte[] EncodeCollisionEdgeWalkable(IReadOnlyList<byte> edgeWalkable) =>
        EncodeBytes(edgeWalkable);

    public static byte[] EncodeCollisionBorders(IReadOnlyList<CollisionBorder> borders)
    {
        ArgumentNullException.ThrowIfNull(borders);
        var data = new byte[checked(borders.Count * DiskCollisionBorderSize)];
        for (int index = 0; index < borders.Count; index++)
        {
            CollisionBorder border = borders[index] ??
                throw new InvalidDataException($"Collision border row {index} is null.");
            if (border.DistEq.Count != 3)
            {
                throw new InvalidDataException(
                    $"Collision border row {index} has {border.DistEq.Count} distance-equation values; expected 3.");
            }

            Span<byte> row = data.AsSpan(
                index * DiskCollisionBorderSize,
                DiskCollisionBorderSize);
            WriteSingle(row, 0, border.DistEq[0]);
            WriteSingle(row, 4, border.DistEq[1]);
            WriteSingle(row, 8, border.DistEq[2]);
            WriteSingle(row, 12, border.ZBase);
            WriteSingle(row, 16, border.ZSlope);
            WriteSingle(row, 20, border.Start);
            WriteSingle(row, 24, border.Length);
        }

        return data;
    }

    public static byte[] EncodeCollisionAabbs(IReadOnlyList<CollisionAabbTree> aabbTrees)
    {
        ArgumentNullException.ThrowIfNull(aabbTrees);
        var data = new byte[checked(aabbTrees.Count * DiskCollisionAabbSize)];
        for (int index = 0; index < aabbTrees.Count; index++)
        {
            CollisionAabbTree tree = aabbTrees[index] ??
                throw new InvalidDataException($"Collision AABB row {index} is null.");
            Span<byte> row = data.AsSpan(
                index * DiskCollisionAabbSize,
                DiskCollisionAabbSize);
            WriteVec3(row, 0, tree.Origin);
            WriteVec3(row, 12, tree.HalfSize);
            BinaryPrimitives.WriteUInt16LittleEndian(row[24..], tree.MaterialIndex);
            BinaryPrimitives.WriteUInt16LittleEndian(row[26..], tree.ChildCount);
            BinaryPrimitives.WriteInt32LittleEndian(row[28..], tree.FirstChildOrPartitionIndex);
        }

        return data;
    }

    private static byte[] EncodeBytes(IReadOnlyList<byte> values)
    {
        ArgumentNullException.ThrowIfNull(values);
        var data = new byte[values.Count];
        for (int index = 0; index < values.Count; index++)
            data[index] = values[index];

        return data;
    }

    private static int GetElementCount(ReadOnlySpan<byte> data, int elementSize, string description)
    {
        if (data.Length % elementSize != 0)
        {
            throw new InvalidDataException(
                $"The {description} lump length {data.Length} is not divisible by {elementSize}.");
        }

        return data.Length / elementSize;
    }

    private static short ReadInt16Checked(
        ReadOnlySpan<byte> row,
        int offset,
        int nodeIndex,
        int childIndex)
    {
        int value = BinaryPrimitives.ReadInt32LittleEndian(row[offset..]);
        if (value is < short.MinValue or > short.MaxValue)
        {
            throw new InvalidDataException(
                $"Collision node row {nodeIndex} child {childIndex} value {value} exceeds the IW4 short range.");
        }

        return (short)value;
    }

    private static void ValidateMaterialIndex(int index, int count, string description)
    {
        if ((uint)index >= (uint)count)
        {
            throw new InvalidDataException(
                $"{description} references material {index}; the material table has {count} rows.");
        }
    }

    private static byte ToByteOffset(int value, int brushIndex, string description)
    {
        if ((uint)value > byte.MaxValue)
        {
            throw new InvalidDataException(
                $"Collision brush row {brushIndex} {description} adjacency offset {value} exceeds the IW4 byte range.");
        }

        return (byte)value;
    }

    private static void AdvanceEdges(
        int totalEdgeCount,
        int count,
        int brushIndex,
        ref int edgeIndex,
        ref int brushEdgeOffset)
    {
        if (edgeIndex > totalEdgeCount - count)
        {
            throw new InvalidDataException(
                $"Collision brush row {brushIndex} consumes past the {totalEdgeCount}-byte adjacency table.");
        }

        edgeIndex += count;
        brushEdgeOffset = checked(brushEdgeOffset + count);
    }

    private static Bounds DecodeBounds(IReadOnlyList<float> mins, IReadOnlyList<float> maxs)
    {
        Vec3 midpoint = new()
        {
            X = Average(mins[0], maxs[0]),
            Y = Average(mins[1], maxs[1]),
            Z = Average(mins[2], maxs[2])
        };
        return new Bounds
        {
            MidPoint = midpoint,
            // IW4 derives half-size from the rounded midpoint rather than from
            // an independently rounded half-difference.
            HalfSize = new Vec3
            {
                X = midpoint.X - mins[0],
                Y = midpoint.Y - mins[1],
                Z = midpoint.Z - mins[2]
            }
        };
    }

    // Round the computed midpoint once, after averaging the two disk floats.
    private static float Average(float left, float right) =>
        (float)(((double)left + right) * 0.5);

    private static Vec3 ReadVec3(ReadOnlySpan<byte> row, int offset) => new()
    {
        X = ReadSingle(row, offset),
        Y = ReadSingle(row, offset + 4),
        Z = ReadSingle(row, offset + 8)
    };

    private static float ReadSingle(ReadOnlySpan<byte> row, int offset) =>
        BitConverter.Int32BitsToSingle(BinaryPrimitives.ReadInt32LittleEndian(row[offset..]));

    private static void WriteVec3(Span<byte> row, int offset, Vec3 value)
    {
        WriteSingle(row, offset, value.X);
        WriteSingle(row, offset + 4, value.Y);
        WriteSingle(row, offset + 8, value.Z);
    }

    private static void WriteSingle(Span<byte> row, int offset, float value) =>
        BinaryPrimitives.WriteInt32LittleEndian(row[offset..], BitConverter.SingleToInt32Bits(value));
}
