using IW4.FastFiles.Zone;
using IW4.FastFiles.Emitters.Emission;

namespace IW4.FastFiles.Emitters.Assets;

/// <summary>Emitter for the complete loader-visible XAnimParts graph. Dynamic
/// frame tables remain byte/ushort encoded exactly as selected by NumFrames.</summary>
public sealed class XAnimBodyEmitter : IXAssetBodyEmitter
{
    public XAssetType AssetType => XAssetType.XAnim;

    public IReadOnlyList<EmissionError> Validate(IXAssetBuildData buildData, int? rowIndex = null)
    {
        var errors = AssetBodyEmitterHelpers.ValidateIdentity(buildData, AssetType, rowIndex);
        if (buildData is not IXAnimBuildData data) { errors.Add(new("body", "XAnim build data does not implement IXAnimBuildData.", rowIndex, AssetType)); return errors; }
        if (data.Name is { } name && !AssetBodyEmitterHelpers.IsLatin1CString(name)) errors.Add(Error("name", "Name must be a Latin-1 C string.", rowIndex));
        if (data.BoneCounts.Count != 10) errors.Add(Error("boneCounts", "XAnim stores exactly ten bone-count bytes.", rowIndex));
        CheckCount(data.BoneNameCount, data.Names.Count, "boneNameCount", errors, rowIndex); CheckCount(data.NotifyCount, data.Notify.Count, "notifyCount", errors, rowIndex);
        CheckCount(data.DataByteCount, data.DataBytes.Count, "dataByteCount", errors, rowIndex); CheckCount(data.DataShortCount, data.DataShorts.Count, "dataShortCount", errors, rowIndex); CheckCount(data.DataIntCount, data.DataInts.Count, "dataIntCount", errors, rowIndex); CheckCount(data.RandomDataByteCount, data.RandomDataBytes.Count, "randomDataByteCount", errors, rowIndex); CheckCount(data.RandomDataIntCount, data.RandomDataInts.Count, "randomDataIntCount", errors, rowIndex);
        if (data.RandomDataShortCount < 0 || data.RandomDataShortCount != data.RandomDataShorts.Count) errors.Add(Error("randomDataShortCount", "Count must be nonnegative and equal the randomized short stream length.", rowIndex));
        if (data.IndexCount < 0 || data.IndexCount != data.Indices.Count) errors.Add(Error("indexCount", "Count must be nonnegative and equal the index stream length.", rowIndex));
        if (data.NumFrames <= byte.MaxValue && data.Indices.Any(value => value > byte.MaxValue)) errors.Add(Error("indices", "Byte-encoded animations cannot contain an index above 255.", rowIndex));
        if (!float.IsFinite(data.Framerate) || !float.IsFinite(data.Frequency)) errors.Add(Error("rate", "Framerate and frequency must be finite.", rowIndex));
        for (int index = 0; index < data.Notify.Count; index++) if (!float.IsFinite(data.Notify[index].Time)) errors.Add(Error($"notify[{index}].time", "Notify time must be finite.", rowIndex));
        if (data.Delta is { } delta) CheckDelta(delta, data.NumFrames, errors, rowIndex);
        return errors;
    }

    public AssetBodyEmission Plan(IXAssetBuildData buildData, EmissionPlan plan, int? rowIndex = null)
    {
        ArgumentNullException.ThrowIfNull(plan); AssetBodyEmitterHelpers.RequireNoDiagnostics(Validate(buildData, rowIndex)); IXAnimBuildData data = (IXAnimBuildData)buildData;
        var all = new List<EmissionBlockSegment>(); var source = new List<EmissionBlockSegment>();
        plan.Push(XFileBlockType.TEMP); EmissionAddress root = plan.Allocate(0x58, 4); plan.Push(XFileBlockType.LARGE);
        int beforeName = all.Count; PlannedString? name = AssetBodyEmitterHelpers.PlanString(data.Name, plan, all, plan.StringAliases); int afterName = all.Count;
        EmissionBlockSegment? names = PlanUshorts(data.Names, 2, plan, all);
        EmissionBlockSegment? notify = PlanNotify(data.Notify, plan, all);
        StreamPlan? delta = data.Delta is { } value ? PlanDelta(value, data.NumFrames, plan, all) : null;
        EmissionBlockSegment? dataBytes = PlanBytes(data.DataBytes, 1, plan, all); EmissionBlockSegment? dataShorts = PlanShorts(data.DataShorts, 2, plan, all); EmissionBlockSegment? dataInts = PlanInts(data.DataInts, 4, plan, all); EmissionBlockSegment? randomShorts = PlanShorts(data.RandomDataShorts, 2, plan, all); EmissionBlockSegment? randomBytes = PlanBytes(data.RandomDataBytes, 1, plan, all); EmissionBlockSegment? randomInts = PlanInts(data.RandomDataInts, 4, plan, all); EmissionBlockSegment? indices = PlanIndices(data.Indices, data.NumFrames, plan, all);
        plan.Pop(XFileBlockType.LARGE); plan.Pop(XFileBlockType.TEMP);
        var writer = new XSourceWriter(); writer.WriteInt32(AssetBodyEmitterHelpers.SourcePointer(name)); writer.WriteUInt16(data.DataByteCount); writer.WriteUInt16(data.DataShortCount); writer.WriteUInt16(data.DataIntCount); writer.WriteUInt16(data.RandomDataByteCount); writer.WriteUInt16(data.RandomDataIntCount); writer.WriteUInt16(data.NumFrames); writer.WriteByte(data.Flags); writer.WriteByte(data.DeltaFlags); writer.WriteBytes(data.BoneCounts.ToArray()); writer.WriteByte((byte)data.BoneNameCount); writer.WriteByte(data.NotifyCount); writer.WriteByte(data.AssetTypeValue); writer.WriteByte(data.Pad1F); writer.WriteInt32(data.RandomDataShortCount); writer.WriteInt32(data.IndexCount); writer.WriteSingle(data.Framerate); writer.WriteSingle(data.Frequency); writer.WriteInt32(Pointer(names)); writer.WriteInt32(Pointer(dataBytes)); writer.WriteInt32(Pointer(dataShorts)); writer.WriteInt32(Pointer(dataInts)); writer.WriteInt32(Pointer(randomShorts)); writer.WriteInt32(Pointer(randomBytes)); writer.WriteInt32(Pointer(randomInts)); writer.WriteInt32(Pointer(indices)); writer.WriteInt32(Pointer(notify)); writer.WriteInt32(delta is null ? 0 : -1);
        var rootSegment = new EmissionBlockSegment(root, writer.ToArray()); all.Add(rootSegment); source.Add(rootSegment); source.AddRange(all.Skip(beforeName).Take(afterName - beforeName)); AddSource(source, names); AddSource(source, notify); if (delta is not null) source.AddRange(delta.Source); AddSource(source, dataBytes); AddSource(source, dataShorts); AddSource(source, dataInts); AddSource(source, randomShorts); AddSource(source, randomBytes); AddSource(source, randomInts); AddSource(source, indices);
        return new AssetBodyEmission(AssetType, root, all, source);
    }

    private static StreamPlan PlanDelta(XAnimDeltaBuildData data, ushort numFrames, EmissionPlan plan, List<EmissionBlockSegment> all)
    {
        EmissionAddress root = plan.Allocate(12, 4); StreamPlan? trans = data.Trans is { } t ? PlanTrans(t, numFrames, plan, all) : null; StreamPlan? quat2 = data.Quat2 is { } q2 ? PlanQuat2(q2, numFrames, plan, all) : null; StreamPlan? quat = data.Quat is { } q ? PlanQuat(q, numFrames, plan, all) : null;
        var writer = new XSourceWriter(); writer.WriteInt32(trans is null ? 0 : -1); writer.WriteInt32(quat2 is null ? 0 : -1); writer.WriteInt32(quat is null ? 0 : -1); var segment = new EmissionBlockSegment(root, writer.ToArray()); all.Add(segment); var source = new List<EmissionBlockSegment> { segment }; if (trans is not null) source.AddRange(trans.Source); if (quat2 is not null) source.AddRange(quat2.Source); if (quat is not null) source.AddRange(quat.Source); return new StreamPlan(source);
    }

    private static StreamPlan PlanTrans(XAnimPartTransBuildData data, ushort numFrames, EmissionPlan plan, List<EmissionBlockSegment> all)
    {
        EmissionAddress root = plan.Allocate(4, 4); var source = new List<EmissionBlockSegment>(); EmissionBlockSegment? frame0 = null; EmissionBlockSegment? framesRoot = null; EmissionBlockSegment? dynamic = null; EmissionBlockSegment? payload = null;
        if (data.Size == 0) frame0 = PlanFloat3(data.Frame0!.Value, 4, plan, all);
        else { int count = data.Size + 1; XAnimTransFramesBuildData frames = data.Frames!; EmissionAddress address = plan.Allocate(0x1c, 4); dynamic = PlanDynamic(frames.DynamicFrames, numFrames, plan, all); payload = data.SmallTrans == 0 ? PlanLargeFrames(frames.LargeFrames!, plan, all) : PlanSmallFrames(frames.SmallFrames!, plan, all); var fw = new XSourceWriter(); WriteFloat3(fw, frames.Mins); WriteFloat3(fw, frames.Size); fw.WriteInt32(-1); framesRoot = new EmissionBlockSegment(address, fw.ToArray()); all.Add(framesRoot); }
        var writer = new XSourceWriter(); writer.WriteUInt16(data.Size); writer.WriteByte(data.SmallTrans); writer.WriteByte(data.Pad3); var rootSegment = new EmissionBlockSegment(root, writer.ToArray()); all.Add(rootSegment); source.Add(rootSegment); AddSource(source, frame0); if (framesRoot is not null) { source.Add(framesRoot); AddSource(source, dynamic); AddSource(source, payload); } return new StreamPlan(source);
    }

    private static StreamPlan PlanQuat2(XAnimQuat2PartBuildData data, ushort numFrames, EmissionPlan plan, List<EmissionBlockSegment> all)
    {
        EmissionAddress root = plan.Allocate(4, 4); EmissionBlockSegment? frame0 = null; EmissionBlockSegment? framesRoot = null; EmissionBlockSegment? dynamic = null; EmissionBlockSegment? payload = null;
        if (data.Size == 0) frame0 = PlanQuat2Values([data.Frame0!.Value], plan, all);
        else { XAnimQuat2FramesBuildData frames = data.Frames!; EmissionAddress address = plan.Allocate(4, 4); dynamic = PlanDynamic(frames.DynamicFrames, numFrames, plan, all); payload = PlanQuat2Values(frames.Frames, plan, all); var fw = new XSourceWriter(); fw.WriteInt32(-1); framesRoot = new EmissionBlockSegment(address, fw.ToArray()); all.Add(framesRoot); }
        var writer = new XSourceWriter(); writer.WriteUInt16(data.Size); writer.WriteByte(data.Pad2); writer.WriteByte(data.Pad3); var rootSegment = new EmissionBlockSegment(root, writer.ToArray()); all.Add(rootSegment); var source = new List<EmissionBlockSegment> { rootSegment }; AddSource(source, frame0); if (framesRoot is not null) { source.Add(framesRoot); AddSource(source, dynamic); AddSource(source, payload); } return new StreamPlan(source);
    }

    private static StreamPlan PlanQuat(XAnimQuatPartBuildData data, ushort numFrames, EmissionPlan plan, List<EmissionBlockSegment> all)
    {
        EmissionAddress root = plan.Allocate(4, 4); EmissionBlockSegment? frame0 = null; EmissionBlockSegment? framesRoot = null; EmissionBlockSegment? dynamic = null; EmissionBlockSegment? payload = null;
        if (data.Size == 0) frame0 = PlanQuatValues([data.Frame0!.Value], plan, all);
        else { XAnimQuatFramesBuildData frames = data.Frames!; EmissionAddress address = plan.Allocate(4, 4); dynamic = PlanDynamic(frames.DynamicFrames, numFrames, plan, all); payload = PlanQuatValues(frames.Frames, plan, all); var fw = new XSourceWriter(); fw.WriteInt32(-1); framesRoot = new EmissionBlockSegment(address, fw.ToArray()); all.Add(framesRoot); }
        var writer = new XSourceWriter(); writer.WriteUInt16(data.Size); writer.WriteByte(data.Pad2); writer.WriteByte(data.Pad3); var rootSegment = new EmissionBlockSegment(root, writer.ToArray()); all.Add(rootSegment); var source = new List<EmissionBlockSegment> { rootSegment }; AddSource(source, frame0); if (framesRoot is not null) { source.Add(framesRoot); AddSource(source, dynamic); AddSource(source, payload); } return new StreamPlan(source);
    }

    private static EmissionBlockSegment? PlanNotify(IReadOnlyList<XAnimNotifyBuildData> values, EmissionPlan plan, List<EmissionBlockSegment> all) { if (values.Count == 0) return null; EmissionAddress address = plan.Allocate(checked(values.Count * 8), 4); var writer = new XSourceWriter(); foreach (XAnimNotifyBuildData value in values) { writer.WriteUInt16(value.Name); writer.Reserve(2); writer.WriteSingle(value.Time); } return Add(all, new EmissionBlockSegment(address, writer.ToArray())); }
    private static EmissionBlockSegment? PlanBytes(IReadOnlyList<byte> values, int alignment, EmissionPlan plan, List<EmissionBlockSegment> all) { if (values.Count == 0) return null; return Add(all, new EmissionBlockSegment(plan.Allocate(values.Count, alignment), values.ToArray())); }
    private static EmissionBlockSegment? PlanUshorts(IReadOnlyList<ushort> values, int alignment, EmissionPlan plan, List<EmissionBlockSegment> all) { if (values.Count == 0) return null; var writer = new XSourceWriter(); foreach (ushort value in values) writer.WriteUInt16(value); return Add(all, new EmissionBlockSegment(plan.Allocate(checked(values.Count * 2), alignment), writer.ToArray())); }
    private static EmissionBlockSegment? PlanShorts(IReadOnlyList<short> values, int alignment, EmissionPlan plan, List<EmissionBlockSegment> all) { if (values.Count == 0) return null; var writer = new XSourceWriter(); foreach (short value in values) writer.WriteInt16(value); return Add(all, new EmissionBlockSegment(plan.Allocate(checked(values.Count * 2), alignment), writer.ToArray())); }
    private static EmissionBlockSegment? PlanInts(IReadOnlyList<int> values, int alignment, EmissionPlan plan, List<EmissionBlockSegment> all) { if (values.Count == 0) return null; var writer = new XSourceWriter(); foreach (int value in values) writer.WriteInt32(value); return Add(all, new EmissionBlockSegment(plan.Allocate(checked(values.Count * 4), alignment), writer.ToArray())); }
    private static EmissionBlockSegment? PlanIndices(IReadOnlyList<ushort> values, ushort numFrames, EmissionPlan plan, List<EmissionBlockSegment> all) { if (values.Count == 0) return null; if (numFrames <= byte.MaxValue) return Add(all, new EmissionBlockSegment(plan.Allocate(values.Count), values.Select(value => (byte)value).ToArray())); return PlanUshorts(values, 2, plan, all)!; }
    private static EmissionBlockSegment PlanDynamic(IReadOnlyList<ushort> values, ushort numFrames, EmissionPlan plan, List<EmissionBlockSegment> all) => PlanIndices(values, numFrames, plan, all) ?? throw new InvalidDataException("A dynamic frame stream cannot be empty.");
    private static EmissionBlockSegment PlanFloat3(Float3BuildData value, int alignment, EmissionPlan plan, List<EmissionBlockSegment> all) { EmissionAddress address = plan.Allocate(12, alignment); var writer = new XSourceWriter(); WriteFloat3(writer, value); return Add(all, new EmissionBlockSegment(address, writer.ToArray())); }
    private static EmissionBlockSegment PlanSmallFrames(IReadOnlyList<XAnimSmallTransFrameBuildData> values, EmissionPlan plan, List<EmissionBlockSegment> all) { EmissionAddress address = plan.Allocate(checked(values.Count * 3)); var writer = new XSourceWriter(); foreach (var value in values) { writer.WriteByte(value.X); writer.WriteByte(value.Y); writer.WriteByte(value.Z); } return Add(all, new EmissionBlockSegment(address, writer.ToArray())); }
    private static EmissionBlockSegment PlanLargeFrames(IReadOnlyList<XAnimLargeTransFrameBuildData> values, EmissionPlan plan, List<EmissionBlockSegment> all) { EmissionAddress address = plan.Allocate(checked(values.Count * 6), 4); var writer = new XSourceWriter(); foreach (var value in values) { writer.WriteInt16(value.X); writer.WriteInt16(value.Y); writer.WriteInt16(value.Z); } return Add(all, new EmissionBlockSegment(address, writer.ToArray())); }
    private static EmissionBlockSegment PlanQuat2Values(IReadOnlyList<XAnimQuat2BuildData> values, EmissionPlan plan, List<EmissionBlockSegment> all) { EmissionAddress address = plan.Allocate(checked(values.Count * 4), 4); var writer = new XSourceWriter(); foreach (var value in values) { writer.WriteInt16(value.Value0); writer.WriteInt16(value.Value1); } return Add(all, new EmissionBlockSegment(address, writer.ToArray())); }
    private static EmissionBlockSegment PlanQuatValues(IReadOnlyList<XAnimQuatBuildData> values, EmissionPlan plan, List<EmissionBlockSegment> all) { EmissionAddress address = plan.Allocate(checked(values.Count * 8), 4); var writer = new XSourceWriter(); foreach (var value in values) { writer.WriteInt16(value.Value0); writer.WriteInt16(value.Value1); writer.WriteInt16(value.Value2); writer.WriteInt16(value.Value3); } return Add(all, new EmissionBlockSegment(address, writer.ToArray())); }
    private static void WriteFloat3(XSourceWriter writer, Float3BuildData value) { writer.WriteSingle(value.X); writer.WriteSingle(value.Y); writer.WriteSingle(value.Z); }
    private static EmissionBlockSegment Add(List<EmissionBlockSegment> all, EmissionBlockSegment segment) { all.Add(segment); return segment; }
    private static void AddSource(List<EmissionBlockSegment> source, EmissionBlockSegment? segment) { if (segment is not null) source.Add(segment); }
    private static int Pointer(EmissionBlockSegment? segment) => segment is null ? 0 : -1;

    private static void CheckDelta(XAnimDeltaBuildData value, ushort numFrames, List<EmissionError> errors, int? rowIndex) { if (value.Trans is { } trans) CheckTrans(trans, numFrames, errors, rowIndex); if (value.Quat2 is { } quat2) CheckQuat2(quat2, numFrames, errors, rowIndex); if (value.Quat is { } quat) CheckQuat(quat, numFrames, errors, rowIndex); }
    private static void CheckTrans(XAnimPartTransBuildData value, ushort numFrames, List<EmissionError> errors, int? rowIndex) { if (value.Size == 0) { if (value.Frame0 is null || value.Frames is not null) errors.Add(Error("delta.trans", "Size-zero translation requires only a frame-zero vector.", rowIndex)); else CheckFinite(value.Frame0.Value, "delta.trans.frame0", errors, rowIndex); return; } if (value.Frame0 is not null || value.Frames is null) { errors.Add(Error("delta.trans", "Dynamic translation requires frame tables and no frame-zero value.", rowIndex)); return; } XAnimTransFramesBuildData frames = value.Frames; int count = value.Size + 1; CheckFinite(frames.Mins, "delta.trans.mins", errors, rowIndex); CheckFinite(frames.Size, "delta.trans.size", errors, rowIndex); if (frames.DynamicFrames.Count != count || (value.SmallTrans == 0 ? frames.LargeFrames?.Count != count || frames.SmallFrames is not null : frames.SmallFrames?.Count != count || frames.LargeFrames is not null)) errors.Add(Error("delta.trans.frames", "Dynamic translation count and payload arm must equal size + 1.", rowIndex)); CheckDynamic(frames.DynamicFrames, numFrames, "delta.trans.dynamicFrames", errors, rowIndex); }
    private static void CheckQuat2(XAnimQuat2PartBuildData value, ushort numFrames, List<EmissionError> errors, int? rowIndex) { if (value.Size == 0) { if (value.Frame0 is null || value.Frames is not null) errors.Add(Error("delta.quat2", "Size-zero quat2 requires only frame-zero data.", rowIndex)); return; } if (value.Frame0 is not null || value.Frames is null || value.Frames.DynamicFrames.Count != value.Size + 1 || value.Frames.Frames.Count != value.Size + 1) errors.Add(Error("delta.quat2.frames", "Dynamic quat2 count must equal size + 1.", rowIndex)); else CheckDynamic(value.Frames.DynamicFrames, numFrames, "delta.quat2.dynamicFrames", errors, rowIndex); }
    private static void CheckQuat(XAnimQuatPartBuildData value, ushort numFrames, List<EmissionError> errors, int? rowIndex) { if (value.Size == 0) { if (value.Frame0 is null || value.Frames is not null) errors.Add(Error("delta.quat", "Size-zero quat requires only frame-zero data.", rowIndex)); return; } if (value.Frame0 is not null || value.Frames is null || value.Frames.DynamicFrames.Count != value.Size + 1 || value.Frames.Frames.Count != value.Size + 1) errors.Add(Error("delta.quat.frames", "Dynamic quat count must equal size + 1.", rowIndex)); else CheckDynamic(value.Frames.DynamicFrames, numFrames, "delta.quat.dynamicFrames", errors, rowIndex); }
    private static void CheckCount(int expected, int actual, string path, List<EmissionError> errors, int? rowIndex) { if (expected != actual) errors.Add(Error(path, "Serialized count must equal its stream length.", rowIndex)); }
    private static void CheckDynamic(IReadOnlyList<ushort> values, ushort numFrames, string path, List<EmissionError> errors, int? rowIndex) { if (numFrames <= byte.MaxValue && values.Any(value => value > byte.MaxValue)) errors.Add(Error(path, "Byte-encoded dynamic frames cannot exceed 255.", rowIndex)); }
    private static void CheckFinite(Float3BuildData value, string path, List<EmissionError> errors, int? rowIndex) { if (!float.IsFinite(value.X) || !float.IsFinite(value.Y) || !float.IsFinite(value.Z)) errors.Add(Error(path, "Vector values must be finite.", rowIndex)); }
    private static EmissionError Error(string path, string message, int? rowIndex) => new(path, message, rowIndex, XAssetType.XAnim);
    private sealed class StreamPlan(IReadOnlyList<EmissionBlockSegment> source) { public IReadOnlyList<EmissionBlockSegment> Source { get; } = source; }
}
