using IW4.FastFiles.Zone;
using IW4.FastFiles.Emitters.Emission;

namespace IW4.FastFiles.Emitters.Assets;

/// <summary>Emitter for authored XModel roots. Render/runtime cache fields are
/// intentionally zeroed; material and physics links remain external roots.</summary>
public sealed class XModelBodyEmitter : IXAssetBodyEmitter
{
    private static readonly XModelSurfsBodyEmitter SurfsValidator = new();
    public XAssetType AssetType => XAssetType.XModel;
    public IReadOnlyList<EmissionError> Validate(IXAssetBuildData buildData, int? rowIndex = null)
    {
        var errors = AssetBodyEmitterHelpers.ValidateIdentity(buildData, AssetType, rowIndex);
        if (buildData is not IXModelBuildData data) { errors.Add(Error("body", "XModel build data does not implement IXModelBuildData.", rowIndex)); return errors; }
        if (data.Name is { } name && !AssetBodyEmitterHelpers.IsLatin1CString(name)) errors.Add(Error("name", "Name must be a Latin-1 C string.", rowIndex));
        if (data.NumRootBones > data.NumBones) errors.Add(Error("numRootBones", "Root bone count cannot exceed total bones.", rowIndex)); int partCount = data.NumBones - data.NumRootBones;
        CheckCount(data.NoScalePartBits, 6, "noScalePartBits", errors, rowIndex); CheckCount(data.BoneNames, data.NumBones, "boneNames", errors, rowIndex); CheckCount(data.ParentList, partCount, "parentList", errors, rowIndex); CheckCount(data.Quats, partCount * 4, "quats", errors, rowIndex); CheckCount(data.Trans, partCount * 3, "trans", errors, rowIndex); CheckCount(data.PartClassification, data.NumBones, "partClassification", errors, rowIndex); CheckCount(data.BaseMat, data.NumBones, "baseMat", errors, rowIndex); CheckCount(data.MaterialReferences, data.NumSurfs, "materialReferences", errors, rowIndex); if (data.MaterialLinks.Count != 0) CheckCount(data.MaterialLinks, data.NumSurfs, "materialLinks", errors, rowIndex); CheckCount(data.Lods, 4, "lods", errors, rowIndex); CheckCount(data.BoneInfo, data.NumBones, "boneInfo", errors, rowIndex); CheckCount(data.InvHighMipRadius, data.NumSurfs, "invHighMipRadius", errors, rowIndex);
        if (data.NumLods > 4 ||
            (data.MaxLoadedLod > 3 && data.MaxLoadedLod != byte.MaxValue) ||
            (data.CollLod > 3 && data.CollLod != byte.MaxValue))
        {
            errors.Add(Error(
                "lods",
                "LOD indices must address one of four serialized slots or use the native 0xFF no-LOD sentinel.",
                rowIndex));
        }
        CheckFinite(data.Scale, "scale", errors, rowIndex); CheckFinite(data.Radius, "radius", errors, rowIndex); CheckVector(data.BoundsMidpoint, "bounds.midpoint", errors, rowIndex); CheckVector(data.BoundsHalfSize, "bounds.halfSize", errors, rowIndex);
        for (int index = 0; index < data.ParentList.Count; index++) if (data.ParentList[index] >= data.NumBones) errors.Add(Error($"parentList[{index}]", "Parent bone index exceeds NumBones.", rowIndex)); for (int index = 0; index < data.BaseMat.Count; index++) { XModelDObjAnimMatBuildData value = data.BaseMat[index]; CheckFloat4(value.Quat, $"baseMat[{index}].quat", errors, rowIndex); CheckVector(value.Trans, $"baseMat[{index}].trans", errors, rowIndex); CheckFinite(value.TransWeight, $"baseMat[{index}].transWeight", errors, rowIndex); } for (int index = 0; index < data.MaterialReferences.Count; index++) { CheckReference(data.MaterialReferences[index], XAssetType.Material, $"materialReferences[{index}]", errors, rowIndex); if (data.MaterialLinks.Count == data.MaterialReferences.Count) errors.AddRange(NestedXAssetEmission.Validate(data.MaterialLinks[index], XAssetType.Material, $"materialLinks[{index}]", rowIndex, AssetType)); } for (int index = 0; index < data.Lods.Count; index++) CheckLod(data.Lods[index], index, errors, rowIndex); for (int index = 0; index < data.CollSurfs.Count; index++) { XModelCollSurfBuildData value = data.CollSurfs[index]; CheckVector(value.Midpoint, $"collSurfs[{index}].midpoint", errors, rowIndex); CheckVector(value.HalfSize, $"collSurfs[{index}].halfSize", errors, rowIndex); if (value.BoneIdx < 0 || value.BoneIdx >= data.NumBones) errors.Add(Error($"collSurfs[{index}].boneIdx", "Collision surface bone index exceeds NumBones.", rowIndex)); } for (int index = 0; index < data.BoneInfo.Count; index++) { XModelBoneInfoBuildData value = data.BoneInfo[index]; CheckVector(value.Midpoint, $"boneInfo[{index}].midpoint", errors, rowIndex); CheckVector(value.HalfSize, $"boneInfo[{index}].halfSize", errors, rowIndex); CheckFinite(value.RadiusSquared, $"boneInfo[{index}].radiusSquared", errors, rowIndex); } CheckReference(data.PhysPresetReference, XAssetType.PhysPreset, "physPreset", errors, rowIndex); CheckReference(data.PhysCollmapReference, XAssetType.PhysCollmap, "physCollmap", errors, rowIndex); errors.AddRange(NestedXAssetEmission.Validate(data.PhysPresetLink, XAssetType.PhysPreset, "physPresetLink", rowIndex, AssetType)); errors.AddRange(NestedXAssetEmission.Validate(data.PhysCollmapLink, XAssetType.PhysCollmap, "physCollmapLink", rowIndex, AssetType)); return errors;
    }
    public AssetBodyEmission Plan(IXAssetBuildData buildData, EmissionPlan plan, int? rowIndex = null)
    {
        ArgumentNullException.ThrowIfNull(plan); AssetBodyEmitterHelpers.RequireNoDiagnostics(Validate(buildData, rowIndex)); IXModelBuildData data = (IXModelBuildData)buildData; var all = new List<EmissionBlockSegment>(); var source = new List<EmissionBlockSegment>();
        OwnedXModelVertexRuntimeArenaValidator.Reserve(data, plan);
        XModelLinkerProvenance provenance = data.LinkerProvenance;
        plan.Push(XFileBlockType.TEMP); EmissionAddress root = plan.Allocate(0x120, 4); plan.Push(XFileBlockType.LARGE);
        int beforeName = all.Count; PlannedString? name = AssetBodyEmitterHelpers.PlanString(data.Name, plan, all, plan.StringAliases); int afterName = all.Count;
        PlannedRegion boneNames = PlanUshorts(data.BoneNames, 2, provenance.BoneNamesStorage, plan, all); PlannedRegion parents = PlanBytes(data.ParentList, 1, provenance.ParentListStorage, plan, all); PlannedRegion quats = PlanShorts(data.Quats, 2, provenance.QuatsStorage, plan, all); PlannedRegion trans = PlanFloats(data.Trans, 4, provenance.TransStorage, plan, all); PlannedRegion classifications = PlanBytes(data.PartClassification, 1, provenance.PartClassificationStorage, plan, all); PlannedRegion baseMat = PlanBaseMat(data.BaseMat, provenance.BaseMatStorage, plan, all);
        EmissionBlockSegment? materialTable = null; var materialSources = new List<EmissionBlockSegment>(); var materialPlans = new List<ExternalPlan?>(); if (data.MaterialReferences.Count != 0) { EmissionAddress address = plan.Allocate(checked(data.MaterialReferences.Count * 4), 4); foreach ((SymbolicXAssetReference? reference, int index) in data.MaterialReferences.Select((value, index) => (value, index))) { NestedXAssetBuildLink? link = data.MaterialLinks.Count == data.MaterialReferences.Count ? data.MaterialLinks[index] : null; ExternalPlan? external = link is not null ? PlanNestedXAsset(link, Offset(address, index * sizeof(int)), plan, all) : reference is null ? null : PlanExternalReference(reference, XAssetType.Material, 0xa8, Offset(address, index * sizeof(int)), XModelNestedPointerSourceForm.Inline, plan, all); materialPlans.Add(external); if (external is not null) materialSources.AddRange(external.Source); } var table = new XSourceWriter(); foreach (ExternalPlan? external in materialPlans) table.WriteInt32(external?.PointerRaw ?? 0); materialTable = new EmissionBlockSegment(address, table.ToArray()); all.Add(materialTable); }
        var lodSources = new List<EmissionBlockSegment>(); var lodPlans = new NestedSurfsPlan?[data.Lods.Count]; for (int lodIndex = 0; lodIndex < data.Lods.Count; lodIndex++) { XModelLodBuildData lod = data.Lods[lodIndex]; if (lod.ModelSurfs is null && lod.ModelSurfsLink is null) continue; NestedSurfsPlan nested = lod.ModelSurfsLink is not null ? PlanNestedSurfs(lod.ModelSurfsLink, Offset(root, 0x48 + (lodIndex * 0x28)), plan, all) : PlanNestedSurfs(lod.ModelSurfs!, Offset(root, 0x48 + (lodIndex * 0x28)), lod.ModelSurfsSourceForm, plan, all); lodPlans[lodIndex] = nested; lodSources.AddRange(nested.Source); }
        EmissionBlockSegment? collSurfs = PlanCollSurfs(data.CollSurfs, plan, all); EmissionBlockSegment? boneInfo = PlanBoneInfo(data.BoneInfo, plan, all); EmissionBlockSegment? invHigh = PlanUshortsInline(data.InvHighMipRadius, 2, plan, all); ExternalPlan? physPreset = data.PhysPresetLink is not null ? PlanNestedXAsset(data.PhysPresetLink, Offset(root, 0x118), plan, all) : data.PhysPresetReference is null ? null : PlanExternalReference(data.PhysPresetReference, XAssetType.PhysPreset, 0x2c, Offset(root, 0x118), provenance.PhysPresetForm, plan, all); ExternalPlan? physCollmap = data.PhysCollmapLink is not null ? PlanNestedXAsset(data.PhysCollmapLink, Offset(root, 0x11c), plan, all) : data.PhysCollmapReference is null ? null : PlanExternalReference(data.PhysCollmapReference, XAssetType.PhysCollmap, 0x48, Offset(root, 0x11c), provenance.PhysCollmapForm, plan, all);
        plan.Pop(XFileBlockType.LARGE); plan.Pop(XFileBlockType.TEMP);
        var writer = new XSourceWriter(); writer.WriteInt32(AssetBodyEmitterHelpers.SourcePointer(name)); writer.WriteByte(data.NumBones); writer.WriteByte(data.NumRootBones); writer.WriteByte(data.NumSurfs); writer.WriteByte(data.Pad07); writer.WriteSingle(data.Scale); foreach (uint value in data.NoScalePartBits) writer.WriteUInt32(value); writer.WriteInt32(boneNames.PointerRaw); writer.WriteInt32(parents.PointerRaw); writer.WriteInt32(quats.PointerRaw); writer.WriteInt32(trans.PointerRaw); writer.WriteInt32(classifications.PointerRaw); writer.WriteInt32(baseMat.PointerRaw); writer.WriteInt32(Pointer(materialTable)); for (int lodIndex = 0; lodIndex < data.Lods.Count; lodIndex++) { XModelLodBuildData lod = data.Lods[lodIndex]; writer.WriteSingle(lod.Dist); writer.WriteUInt16(lod.NumSurfs); writer.WriteUInt16(lod.SurfIndex); writer.WriteInt32(lodPlans[lodIndex]?.PointerRaw ?? 0); foreach (uint value in lod.PartBits) writer.WriteUInt32(value); writer.WriteInt32(0); } writer.WriteByte(data.MaxLoadedLod); writer.WriteByte(data.NumLods); writer.WriteByte(data.CollLod); writer.WriteByte(data.Flags); writer.WriteInt32(Pointer(collSurfs)); writer.WriteInt32(data.CollSurfs.Count); writer.WriteInt32(data.Contents); writer.WriteInt32(Pointer(boneInfo)); writer.WriteSingle(data.Radius); WriteVector(writer, data.BoundsMidpoint); WriteVector(writer, data.BoundsHalfSize); writer.WriteInt32(Pointer(invHigh)); writer.WriteInt32(data.MemUsage); writer.WriteInt32(physPreset?.PointerRaw ?? 0); writer.WriteInt32(physCollmap?.PointerRaw ?? 0);
        var rootSegment = new EmissionBlockSegment(root, writer.ToArray()); all.Add(rootSegment); source.Add(rootSegment); source.AddRange(all.Skip(beforeName).Take(afterName - beforeName)); source.AddRange(boneNames.Source); source.AddRange(parents.Source); source.AddRange(quats.Source); source.AddRange(trans.Source); source.AddRange(classifications.Source); source.AddRange(baseMat.Source); Add(source, materialTable); source.AddRange(materialSources); source.AddRange(lodSources); Add(source, collSurfs); Add(source, boneInfo); Add(source, invHigh); if (physPreset is not null) source.AddRange(physPreset.Source); if (physCollmap is not null) source.AddRange(physCollmap.Source); return new AssetBodyEmission(AssetType, root, all, source);
    }
    private static ExternalPlan PlanExternalReference(SymbolicXAssetReference reference, XAssetType type, int rootSize, EmissionAddress ownerCell, XModelNestedPointerSourceForm sourceForm, EmissionPlan plan, List<EmissionBlockSegment> all) { string aliasKey = AliasKey(type, reference.OriginalSerializedName); if (plan.PersistentXAssetAliasCells.TryGetValue(aliasKey, out EmissionAddress existing)) return new ExternalPlan(existing.ToPackedPointer(), []); EmissionAddress? insertCell = sourceForm == XModelNestedPointerSourceForm.Insert ? plan.AllocateInsertPointerCell("XModel", $"insert:{type}:{reference.OriginalSerializedName}") : null; plan.Push(XFileBlockType.TEMP); EmissionAddress root = plan.Allocate(rootSize, 4); plan.Push(XFileBlockType.LARGE); int before = all.Count; PlannedString? name = AssetBodyEmitterHelpers.PlanString(reference.OriginalSerializedName, plan, all, plan.StringAliases); EmissionBlockSegment[] strings = all.Skip(before).ToArray(); plan.Pop(XFileBlockType.LARGE); plan.Pop(XFileBlockType.TEMP); var rootWriter = new XSourceWriter(); rootWriter.WriteInt32(AssetBodyEmitterHelpers.SourcePointer(name)); rootWriter.Reserve(rootSize - 4); var rootSegment = new EmissionBlockSegment(root, rootWriter.ToArray()); all.Add(rootSegment); EmissionAddress aliasCell = insertCell ?? ownerCell; if (aliasCell.Block != XFileBlockType.TEMP) plan.PersistentXAssetAliasCells.TryAdd(aliasKey, aliasCell); return new ExternalPlan(sourceForm == XModelNestedPointerSourceForm.Insert ? -2 : -1, [rootSegment, .. strings]); }
    private static ExternalPlan PlanNestedXAsset(NestedXAssetBuildLink link, EmissionAddress ownerCell, EmissionPlan plan, List<EmissionBlockSegment> all) { NestedXAssetPlan nested = NestedXAssetEmission.Plan(link, plan, all, ownerCell, "XModel"); return new ExternalPlan(nested.PointerRaw, nested.Source); }
    private static NestedSurfsPlan PlanNestedSurfs(NestedXAssetBuildLink link, EmissionAddress ownerCell, EmissionPlan plan, List<EmissionBlockSegment> all) { ExternalPlan nested = PlanNestedXAsset(link, ownerCell, plan, all); return new NestedSurfsPlan(nested.PointerRaw, nested.Source); }
    private static NestedSurfsPlan PlanNestedSurfs(IXModelSurfsBuildData data, EmissionAddress ownerCell, XModelNestedPointerSourceForm sourceForm, EmissionPlan plan, List<EmissionBlockSegment> all) { string? aliasKey = data.Name is null ? null : AliasKey(XAssetType.XModelSurfs, data.Name); if (aliasKey is not null && plan.PersistentXAssetAliasCells.TryGetValue(aliasKey, out EmissionAddress existing)) return new NestedSurfsPlan(existing.ToPackedPointer(), []); EmissionAddress? insertCell = sourceForm == XModelNestedPointerSourceForm.Insert ? plan.AllocateInsertPointerCell("XModel", $"insert:XModelSurfs:{data.Name}") : null; AssetBodyEmission nested = XModelSurfsBodyEmitter.PlanNested(data, plan); all.AddRange(nested.Segments); EmissionAddress aliasCell = insertCell ?? ownerCell; if (aliasKey is not null && aliasCell.Block != XFileBlockType.TEMP) plan.PersistentXAssetAliasCells.TryAdd(aliasKey, aliasCell); return new NestedSurfsPlan(sourceForm == XModelNestedPointerSourceForm.Insert ? -2 : -1, nested.SourceSegments); }
    private static PlannedRegion PlanBytes(IReadOnlyList<byte> data, int alignment, XModelReusableStorageToken? storage, EmissionPlan plan, List<EmissionBlockSegment> all) => PlanRegion(data.ToArray(), alignment, storage, plan, all);
    private static PlannedRegion PlanUshorts(IReadOnlyList<ushort> data, int alignment, XModelReusableStorageToken? storage, EmissionPlan plan, List<EmissionBlockSegment> all) { var writer = new XSourceWriter(); foreach (ushort value in data) writer.WriteUInt16(value); return PlanRegion(writer.ToArray(), alignment, storage, plan, all); }
    private static PlannedRegion PlanShorts(IReadOnlyList<short> data, int alignment, XModelReusableStorageToken? storage, EmissionPlan plan, List<EmissionBlockSegment> all) { var writer = new XSourceWriter(); foreach (short value in data) writer.WriteInt16(value); return PlanRegion(writer.ToArray(), alignment, storage, plan, all); }
    private static PlannedRegion PlanFloats(IReadOnlyList<float> data, int alignment, XModelReusableStorageToken? storage, EmissionPlan plan, List<EmissionBlockSegment> all) { var writer = new XSourceWriter(); foreach (float value in data) writer.WriteSingle(value); return PlanRegion(writer.ToArray(), alignment, storage, plan, all); }
    private static PlannedRegion PlanBaseMat(IReadOnlyList<XModelDObjAnimMatBuildData> data, XModelReusableStorageToken? storage, EmissionPlan plan, List<EmissionBlockSegment> all) { var writer = new XSourceWriter(); foreach (XModelDObjAnimMatBuildData value in data) { writer.WriteSingle(value.Quat.X); writer.WriteSingle(value.Quat.Y); writer.WriteSingle(value.Quat.Z); writer.WriteSingle(value.Quat.W); WriteVector(writer, value.Trans); writer.WriteSingle(value.TransWeight); } return PlanRegion(writer.ToArray(), 4, storage, plan, all); }
    private static PlannedRegion PlanRegion(byte[] bytes, int alignment, XModelReusableStorageToken? storage, EmissionPlan plan, List<EmissionBlockSegment> all) { if (bytes.Length == 0) return new PlannedRegion(0, []); if (storage is { } token && plan.TryGetReusableStorage(token.Value, bytes, out EmissionAddress existing)) return new PlannedRegion(existing.ToPackedPointer(), []); EmissionAddress address = plan.Allocate(bytes.Length, alignment); var segment = new EmissionBlockSegment(address, bytes); all.Add(segment); if (storage is { } created) plan.RegisterReusableStorage(created.Value, bytes, address); return new PlannedRegion(-1, [segment]); }
    private static EmissionBlockSegment? PlanUshortsInline(IReadOnlyList<ushort> data, int alignment, EmissionPlan plan, List<EmissionBlockSegment> all) { if (data.Count == 0) return null; var writer = new XSourceWriter(); foreach (ushort value in data) writer.WriteUInt16(value); var segment = new EmissionBlockSegment(plan.Allocate(checked(data.Count * 2), alignment), writer.ToArray()); all.Add(segment); return segment; }
    private static EmissionBlockSegment? PlanCollSurfs(IReadOnlyList<XModelCollSurfBuildData> data, EmissionPlan plan, List<EmissionBlockSegment> all) { if (data.Count == 0) return null; var writer = new XSourceWriter(); foreach (XModelCollSurfBuildData value in data) { WriteVector(writer, value.Midpoint); WriteVector(writer, value.HalfSize); writer.WriteInt32(value.BoneIdx); writer.WriteInt32(value.Contents); writer.WriteInt32(value.SurfFlags); } var segment = new EmissionBlockSegment(plan.Allocate(checked(data.Count * 0x24), 4), writer.ToArray()); all.Add(segment); return segment; }
    private static EmissionBlockSegment? PlanBoneInfo(IReadOnlyList<XModelBoneInfoBuildData> data, EmissionPlan plan, List<EmissionBlockSegment> all) { if (data.Count == 0) return null; var writer = new XSourceWriter(); foreach (XModelBoneInfoBuildData value in data) { WriteVector(writer, value.Midpoint); WriteVector(writer, value.HalfSize); writer.WriteSingle(value.RadiusSquared); } var segment = new EmissionBlockSegment(plan.Allocate(checked(data.Count * 0x1c), 4), writer.ToArray()); all.Add(segment); return segment; }
    private static void CheckLod(XModelLodBuildData value, int index, List<EmissionError> errors, int? rowIndex)
    {
        string path = $"lods[{index}]";
        CheckFinite(value.Dist, $"{path}.dist", errors, rowIndex);
        CheckCount(value.PartBits, 6, $"{path}.partBits", errors, rowIndex);
        bool ownsSerializedSurfs =
            value.ModelSurfsLink?.SourceForm !=
            NestedXAssetPointerSourceForm.PackedAlias;
        if (ownsSerializedSurfs && value.ModelSurfs is not null)
        {
            // A duplicate inserted XModelSurfs header may intentionally carry
            // a null internal surface pointer. DB_AddXAsset then resolves its
            // name to an earlier canonical provider whose surface table owns
            // the LOD payload. A non-empty inline table must still match the
            // owning LOD's load count.
            if (value.ModelSurfs.Surfaces.Count != 0 &&
                value.NumSurfs != value.ModelSurfs.Surfaces.Count)
            {
                errors.Add(Error(
                    $"{path}.numSurfs",
                    "LOD surface count must equal its non-empty inline nested XModelSurfs surface count.",
                    rowIndex));
            }
            errors.AddRange(SurfsValidator.Validate(value.ModelSurfs, rowIndex));
        }
        errors.AddRange(NestedXAssetEmission.Validate(
            value.ModelSurfsLink,
            XAssetType.XModelSurfs,
            $"{path}.modelSurfsLink",
            rowIndex,
            XAssetType.XModel));
    }
    private static void CheckReference(SymbolicXAssetReference? value, XAssetType expected, string path, List<EmissionError> errors, int? rowIndex) { if (value is not null && (value.AssetType != expected || !value.IsExternalReference || !AssetBodyEmitterHelpers.IsLatin1CString(value.OriginalSerializedName))) errors.Add(Error(path, $"Reference must be a comma-prefixed external {expected} identity.", rowIndex)); }
    private static void CheckCount<T>(IReadOnlyList<T> values, int count, string path, List<EmissionError> errors, int? rowIndex) { if (values.Count != count) errors.Add(Error(path, $"Requires exactly {count} values.", rowIndex)); } private static void CheckFinite(float value, string path, List<EmissionError> errors, int? rowIndex) { if (!float.IsFinite(value)) errors.Add(Error(path, "Value must be finite.", rowIndex)); } private static void CheckFloat4(Float4BuildData value, string path, List<EmissionError> errors, int? rowIndex) { CheckFinite(value.X, path, errors, rowIndex); CheckFinite(value.Y, path, errors, rowIndex); CheckFinite(value.Z, path, errors, rowIndex); CheckFinite(value.W, path, errors, rowIndex); } private static void CheckVector(Float3BuildData value, string path, List<EmissionError> errors, int? rowIndex) { CheckFinite(value.X, path, errors, rowIndex); CheckFinite(value.Y, path, errors, rowIndex); CheckFinite(value.Z, path, errors, rowIndex); }
    private static EmissionAddress Offset(EmissionAddress address, int offset) => new(address.Block, checked(address.Offset + offset));
    private static string AliasKey(XAssetType type, string serializedName) => $"{(int)type}\u0000{serializedName.TrimStart(',')}";
    private static int Pointer(EmissionBlockSegment? segment) => segment is null ? 0 : -1; private static void Add(List<EmissionBlockSegment> source, EmissionBlockSegment? segment) { if (segment is not null) source.Add(segment); } private static void WriteVector(XSourceWriter writer, Float3BuildData value) { writer.WriteSingle(value.X); writer.WriteSingle(value.Y); writer.WriteSingle(value.Z); } private static EmissionError Error(string path, string message, int? rowIndex) => new(path, message, rowIndex, XAssetType.XModel);

    private sealed record PlannedRegion(
        int PointerRaw,
        IReadOnlyList<EmissionBlockSegment> Source);

    private sealed record ExternalPlan(
        int PointerRaw,
        IReadOnlyList<EmissionBlockSegment> Source);

    private sealed record NestedSurfsPlan(
        int PointerRaw,
        IReadOnlyList<EmissionBlockSegment> Source);
}
