namespace IW4.Gsc.BuiltIns;

public static partial class Iw4GscBuiltInCatalog
{
    // PS3 TU1.11 Scr_GetFunction / Scr_GetMethod tables, in resolver order.
    private static partial IReadOnlyList<RegistrationGroup> GetRegistrationGroups() =>
    [
        new("Shared global functions", Iw4GscBuiltInKind.Function, Iw4GscBuiltInReceiver.None, SharedFunctions),
        new("Objective functions", Iw4GscBuiltInKind.Function, Iw4GscBuiltInReceiver.None, ObjectiveFunctions),
        new("Multiplayer global functions", Iw4GscBuiltInKind.Function, Iw4GscBuiltInReceiver.None, GlobalFunctions),
        new("Shared entity methods", Iw4GscBuiltInKind.Method, Iw4GscBuiltInReceiver.Entity, SharedMethods),
        new("Client methods", Iw4GscBuiltInKind.Method, Iw4GscBuiltInReceiver.Player, ClientMethods),
        new("Player methods", Iw4GscBuiltInKind.Method, Iw4GscBuiltInReceiver.Player, PlayerMethods),
        new("Script entity/mover methods", Iw4GscBuiltInKind.Method, Iw4GscBuiltInReceiver.ScriptEntity, ScriptEntityMethods),
        new("Vehicle methods", Iw4GscBuiltInKind.Method, Iw4GscBuiltInReceiver.Entity, VehicleMethods),
        new("Helicopter methods", Iw4GscBuiltInKind.Method, Iw4GscBuiltInReceiver.Helicopter, HelicopterMethods),
        new("HUD element methods", Iw4GscBuiltInKind.Method, Iw4GscBuiltInReceiver.HudElement, HudElementMethods),
        new("Multiplayer entity methods", Iw4GscBuiltInKind.Method, Iw4GscBuiltInReceiver.Entity, GenericMethods),
        new("Compiler/VM intrinsics", Iw4GscBuiltInKind.VmIntrinsic, Iw4GscBuiltInReceiver.None, VmIntrinsics)
    ];

    // 0x007182B4: 173 registrations.
    private static readonly Registration[] SharedFunctions =
    [
        new("createprintchannel", "GScr_CreatePrintChannel", true),
        new("setprintchannel", "GScr_printChannelSet", true),
        new("print", "print", true),
        new("println", "println", true),
        new("print3d", "GScr_print3d", true),
        new("line", "GScr_line", true),
        new("precacheturret", "GScr_PrecacheTurret", false),
        new("getweaponarray", "PS3 0x001AAF20", false),
        new("spawnturret", "GScr_SpawnTurret", false),
        new("canspawnturret", "PS3 0x001A7FF0", false),
        new("assert", "assertCmd", true),
        new("assertex", "assertexCmd", true),
        new("assertmsg", "assertmsgCmd", true),
        new("isdefined", "GScr_IsDefined", false),
        new("isstring", "GScr_IsString", false),
        new("setdvar", "GScr_SetDvar", false),
        new("setdvarifuninitialized", "PS3 0x001A7B80", false),
        new("setdevdvar", "PS3 0x001A7D60", true),
        new("setdevdvarifuninitialized", "PS3 0x001A7A90", true),
        new("getdvar", "GScr_GetDvar", false),
        new("getdvarint", "GScr_GetDvarInt", false),
        new("getdvarfloat", "GScr_GetDvarFloat", false),
        new("getdvarvector", "PS3 0x001A7860", false),
        new("gettime", "GScr_GetTime", false),
        new("getentbynum", "Scr_GetEntByNum", true),
        new("getweaponmodel", "Scr_GetWeaponModel", false),
        new("getweaponhidetags", "PS3 0x001A4CF8", false),
        new("getanimlength", "GScr_GetAnimLength", false),
        new("animhasnotetrack", "GScr_AnimHasNotetrack", false),
        new("getnotetracktimes", "GScr_GetNotetrackTimes", false),
        new("spawn", "GScr_Spawn", false),
        new("bullettrace", "Scr_BulletTrace", false),
        new("bullettracepassed", "Scr_BulletTracePassed", false),
        new("sighttracepassed", "Scr_SightTracePassed", false),
        new("physicstrace", "Scr_PhysicsTrace", false),
        new("playerphysicstrace", "Scr_PlayerPhysicsTrace", false),
        new("getgroundposition", "PS3 0x001AC0B0", false),
        new("getmovedelta", "GScr_GetMoveDelta", false),
        new("getangledelta", "GScr_GetAngleDelta", false),
        new("getnorthyaw", "GScr_GetNorthYaw", false),
        new("setnorthyaw", "PS3 0x001AD308", false),
        new("setslowmotion", "PS3 0x001A45E0", false),
        new("randomint", "Scr_RandomInt", false),
        new("randomfloat", "Scr_RandomFloat", false),
        new("randomintrange", "Scr_RandomIntRange", false),
        new("randomfloatrange", "Scr_RandomFloatRange", false),
        new("sin", "GScr_sin", false),
        new("cos", "GScr_cos", false),
        new("tan", "GScr_tan", false),
        new("asin", "GScr_asin", false),
        new("acos", "GScr_acos", false),
        new("atan", "GScr_atan", false),
        new("int", "GScr_CastInt", false),
        new("abs", "GScr_abs", false),
        new("min", "GScr_min", false),
        new("max", "GScr_max", false),
        new("floor", "GScr_floor", false),
        new("ceil", "GScr_ceil", false),
        new("exp", "PS3 0x001A6AC0", false),
        new("log", "PS3 0x001A6A80", false),
        new("sqrt", "GScr_sqrt", false),
        new("squared", "PS3 0x0019F880", false),
        new("clamp", "PS3 0x001AABE8", false),
        new("angleclamp", "PS3 0x001A6A10", false),
        new("angleclamp180", "PS3 0x001A0828", false),
        new("vectorfromlinetopoint", "GScr_VectorFromLineToPoint", false),
        new("pointonsegmentnearesttopoint", "GScr_PointOnSegmentNearestToPoint", false),
        new("distance", "Scr_Distance", false),
        new("distance2d", "Scr_Distance2D", false),
        new("distancesquared", "Scr_DistanceSquared", false),
        new("length", "Scr_Length", false),
        new("lengthsquared", "Scr_LengthSquared", false),
        new("closer", "Scr_Closer", false),
        new("vectordot", "Scr_VectorDot", false),
        new("vectornormalize", "Scr_VectorNormalize", false),
        new("vectortoangles", "Scr_VectorToAngles", false),
        new("vectortoyaw", "PS3 0x001A68A0", false),
        new("vectorlerp", "Scr_VectorLerp", false),
        new("anglestoup", "Scr_AnglesToUp", false),
        new("anglestoright", "Scr_AnglesToRight", false),
        new("anglestoforward", "Scr_AnglesToForward", false),
        new("combineangles", "Scr_CombineAngles", false),
        new("transformmove", "PS3 0x001A64C8", false),
        new("issubstr", "Scr_IsSubStr", false),
        new("getsubstr", "Scr_GetSubStr", false),
        new("tolower", "Scr_ToLower", false),
        new("strtok", "Scr_StrTok", false),
        new("ambientplay", "Scr_AmbientPlay", false),
        new("ambientstop", "Scr_AmbientStop", false),
        new("precachemodel", "Scr_PrecacheModel", false),
        new("precacheshellshock", "Scr_PrecacheShellShock", false),
        new("precacheitem", "Scr_PrecacheItem", false),
        new("precacheshader", "Scr_PrecacheShader", false),
        new("precachestring", "Scr_PrecacheString", false),
        new("precachemenu", "GScr_PrecacheMenu", false),
        new("precacherumble", "NULLSUB", false),
        new("precachelocationselector", "GScr_PrecacheLocationSelector", false),
        new("loadfx", "Scr_LoadFX", false),
        new("playfx", "Scr_PlayFX", false),
        new("playfxontag", "Scr_PlayFXOnTag", false),
        new("stopfxontag", "PS3 0x001A5530", false),
        new("playloopedfx", "Scr_PlayLoopedFX", false),
        new("spawnfx", "Scr_SpawnFX", false),
        new("triggerfx", "Scr_TriggerFX", false),
        new("playfxontagforclients", "PS3 0x001A89F0", false),
        new("physicsexplosionsphere", "Scr_PhysicsExplosionSphere", false),
        new("physicsexplosioncylinder", "Scr_PhysicsExplosionCylinder", false),
        new("physicsjolt", "Scr_PhysicsRadiusJolt", false),
        new("physicsjitter", "Scr_PhysicsRadiusJitter", false),
        new("setexpfog", "Scr_SetExponentialFog", false),
        new("isexplosivedamagemod", "PS3 0x0019ED00", false),
        new("radiusdamage", "GScr_RadiusDamage", false),
        new("setplayerignoreradiusdamage", "GScr_SetPlayerIgnoreRadiusDamage", false),
        new("glassradiusdamage", "PS3 0x001A51B8", false),
        new("earthquake", "GScr_Earthquake", false),
        new("getnumparts", "GScr_GetNumParts", false),
        new("getpartname", "GScr_GetPartName", false),
        new("weaponfiretime", "GScr_WeaponFireTime", false),
        new("weaponclipsize", "GScr_WeaponClipSize", false),
        new("weaponisauto", "PS3 0x001A0EC8", false),
        new("weaponissemiauto", "GScr_WeaponIsSemiAuto", false),
        new("weaponisboltaction", "GScr_WeaponIsBoltAction", false),
        new("weaponinheritsperks", "PS3 0x001A0C48", false),
        new("weaponburstcount", "PS3 0x001A0D58", false),
        new("weapontype", "GScr_WeaponType", false),
        new("weaponclass", "GScr_WeaponClass", false),
        new("weaponinventorytype", "GScr_WeaponInventoryType", false),
        new("weaponstartammo", "GScr_WeaponStartAmmo", false),
        new("weaponmaxammo", "GScr_WeaponMaxAmmo", false),
        new("weaponaltweaponname", "GScr_WeaponAltWeaponName", false),
        new("isweaponcliponly", "GScr_IsWeaponClipOnly", false),
        new("isweapondetonationtimed", "GScr_IsWeaponDetonationTimed", false),
        new("weaponhasthermalscope", "PS3 0x001A0AE8", false),
        new("getvehiclenode", "PS3 0x00338608", false),
        new("getvehiclenodearray", "PS3 0x003384D8", false),
        new("getallvehiclenodes", "PS3 0x00338440", false),
        new("getnumvehicles", "PS3 0x0033F320", false),
        new("precachevehicle", "PS3 0x0033F398", false),
        new("spawnvehicle", "PS3 0x0033F930", false),
        new("vehicle_getarray", "PS3 0x0033F288", false),
        new("vehicle_getspawnerarray", "PS3 0x0033EB80", false),
        new("playrumbleonposition", "NULLSUB", false),
        new("playrumblelooponposition", "NULLSUB", false),
        new("stopallrumbles", "NULLSUB", false),
        new("soundexists", "ScrCmd_SoundExists", false),
        new("openfile", "GScr_OpenFile", true),
        new("closefile", "GScr_CloseFile", true),
        new("fprintln", "GScr_FPrintln", true),
        new("fprintfields", "GScr_FPrintFields", true),
        new("freadln", "GScr_FReadLn", true),
        new("fgetarg", "GScr_FGetArg", true),
        new("setminimap", "GScr_SetMiniMap", false),
        new("setthermalbodymaterial", "PS3 0x001A46E0", false),
        new("getarraykeys", "GScr_GetArrayKeys", false),
        new("getfirstarraykey", "PS3 0x001A8990", false),
        new("getnextarraykey", "PS3 0x001A8940", false),
        new("sortbydistance", "PS3 0x001AD8A8", false),
        new("tablelookup", "Scr_TableLookup", false),
        new("tablelookupbyrow", "PS3 0x001AA9F8", false),
        new("tablelookupistring", "Scr_TableLookupIString", false),
        new("tablelookupistringbyrow", "PS3 0x001AA968", false),
        new("tablelookuprownum", "PS3 0x001AAA88", false),
        new("getmissileowner", "PS3 0x001AB080", false),
        new("magicbullet", "PS3 0x001AB248", false),
        new("getweaponflashtagname", "PS3 0x001A84B0", false),
        new("averagepoint", "PS3 0x001A88B8", false),
        new("averagenormal", "PS3 0x001AF680", false),
        new("getglass", "PS3 0x001A42C8", false),
        new("getglassarray", "PS3 0x001A4380", false),
        new("getglassorigin", "PS3 0x001A4140", false),
        new("isglassdestroyed", "PS3 0x001A41F0", false),
        new("destroyglass", "PS3 0x001AA118", false),
        new("deleteglass", "PS3 0x001A40A8", false),
    ];

    // 0x007117E4: 8 registrations.
    private static readonly Registration[] ObjectiveFunctions =
    [
        new("objective_add", "Scr_Objective_Add", false),
        new("objective_delete", "Scr_Objective_Delete", false),
        new("objective_state", "Scr_Objective_State", false),
        new("objective_icon", "Scr_Objective_Icon", false),
        new("objective_position", "Scr_Objective_Position", false),
        new("objective_current", "Scr_Objective_Current", false),
        new("objective_onentity", "Scr_Objective_OnEntity", false),
        new("objective_team", "GScr_Objective_Team", false),
    ];

    // 0x0075C57C: 104 registrations.
    private static readonly Registration[] GlobalFunctions =
    [
        new("iprintln", "iprintln", false),
        new("iprintlnbold", "iprintlnbold", false),
        new("logstring", "NULLSUB", false),
        new("getent", "Scr_GetEnt", false),
        new("getentarray", "Scr_GetEntArray", false),
        new("spawnplane", "GScr_SpawnPlane", false),
        new("spawnstruct", "Scr_AddStruct", false),
        new("spawnhelicopter", "GScr_SpawnHelicopter", false),
        new("isalive", "GScr_IsAlive", false),
        new("isspawner", "PS3 0x001B2150", false),
        new("getbrushmodelcenter", "GScr_GetBrushModelCenter", false),
        new("missile_createattractorent", "Scr_MissileCreateAttractorEnt", false),
        new("missile_createattractororigin", "Scr_MissileCreateAttractorOrigin", false),
        new("missile_createrepulsorent", "Scr_MissileCreateRepulsorEnt", false),
        new("missile_createrepulsororigin", "Scr_MissileCreateRepulsorOrigin", false),
        new("missile_deleteattractor", "Scr_MissileDeleteAttractor", false),
        new("musicplay", "Scr_MusicPlay", false),
        new("musicstop", "Scr_MusicStop", false),
        new("soundfade", "Scr_SoundFade", false),
        new("playsoundatpos", "PS3 0x001B2990", false),
        new("grenadeexplosioneffect", "Scr_GrenadeExplosionEffect", false),
        new("newhudelem", "GScr_NewHudElem", false),
        new("newclienthudelem", "GScr_NewClientHudElem", false),
        new("newteamhudelem", "GScr_NewTeamHudElem", false),
        new("resettimeout", "Scr_ResetTimeout", false),
        new("precacheleaderboards", "PS3 0x001AFF40", false),
        new("precachefxteamthermal", "PS3 0x001B27B0", false),
        new("isplayer", "GScr_IsPlayer", false),
        new("isplayernumber", "GScr_IsPlayerNumber", false),
        new("setwinningplayer", "GScr_SetWinningPlayer", false),
        new("setwinningteam", "GScr_SetWinningTeam", false),
        new("announcement", "GScr_Announcement", false),
        new("clientannouncement", "GScr_ClientAnnouncement", false),
        new("getteamscore", "GScr_GetTeamScore", false),
        new("setteamscore", "GScr_SetTeamScore", false),
        new("setclientnamemode", "GScr_SetClientNameMode", false),
        new("updateclientnames", "GScr_UpdateClientNames", false),
        new("getteamplayersalive", "GScr_GetTeamPlayersAlive", false),
        new("logprint", "GScr_LogPrint", false),
        new("worldentnumber", "GScr_WorldEntNumber", false),
        new("obituary", "GScr_Obituary", false),
        new("positionwouldtelefrag", "GScr_positionWouldTelefrag", false),
        new("canspawn", "PS3 0x001B1F38", false),
        new("getstarttime", "GScr_getStartTime", false),
        new("precachestatusicon", "GScr_PrecacheStatusIcon", false),
        new("precacheheadicon", "GScr_PrecacheHeadIcon", false),
        new("precacheminimapicon", "PS3 0x001B1E78", false),
        new("precachempanim", "PS3 0x001B1998", false),
        new("map_restart", "GScr_MapRestart", false),
        new("exitlevel", "GScr_ExitLevel", false),
        new("addtestclient", "GScr_AddTestClient", false),
        new("makedvarserverinfo", "GScr_MakeDvarServerInfo", false),
        new("setarchive", "NULLSUB", false),
        new("allclientsprint", "GScr_AllClientsPrint", false),
        new("clientprint", "GScr_ClientPrint", false),
        new("mapexists", "GScr_MapExists", false),
        new("isvalidgametype", "GScr_IsValidGameType", false),
        new("matchend", "NULLSUB", false),
        new("setplayerteamrank", "NULLSUB", false),
        new("sendranks", "NULLSUB", false),
        new("endparty", "NULLSUB", false),
        new("setteamradar", "GScr_SetTeamRadar", false),
        new("getteamradar", "GScr_GetTeamRadar", false),
        new("blockteamradar", "PS3 0x001B74C0", false),
        new("unblockteamradar", "PS3 0x001B7418", false),
        new("isteamradarblocked", "PS3 0x001B7368", false),
        new("getassignedteam", "PlayerCmd_buttonPressedDEVONLY", false),
        new("setmatchdata", "PS3 0x001AF758", false),
        new("getmatchdata", "PS3 0x001B0650", false),
        new("sendmatchdata", "PS3 0x001AF748", false),
        new("clearmatchdata", "PS3 0x001AF750", false),
        new("setmatchdatadef", "PS3 0x001AF760", false),
        new("setclientmatchdata", "PS3 0x001B7030", false),
        new("getclientmatchdata", "PS3 0x001B6658", false),
        new("setclientmatchdatadef", "PS3 0x001B6E18", false),
        new("sendclientmatchdata", "PS3 0x001B0808", false),
        new("getbuildversion", "PS3 0x001AFEB8", false),
        new("getbuildnumber", "PS3 0x001B07D8", false),
        new("getsystemtime", "PS3 0x001B07A8", false),
        new("setvotestring", "GScr_SetVoteString", false),
        new("setvotetime", "GScr_SetVoteTime", false),
        new("setvoteyescount", "GScr_SetVoteYesCount", false),
        new("setvotenocount", "GScr_SetVoteNoCount", false),
        new("kick", "GScr_KickPlayer", false),
        new("ban", "GScr_BanPlayer", false),
        new("map", "GScr_LoadMap", false),
        new("issplitscreen", "PlayerCmd_buttonPressedDEVONLY", false),
        new("setmapcenter", "GScr_SetMapCenter", false),
        new("setgameendtime", "GScr_SetGameEndTime", false),
        new("searchforonlinegames", "NULLSUB", false),
        new("quitlobby", "NULLSUB", false),
        new("quitparty", "NULLSUB", false),
        new("startparty", "NULLSUB", false),
        new("startprivatematch", "NULLSUB", false),
        new("visionsetnaked", "Scr_VisionSetNaked", false),
        new("visionsetnight", "Scr_VisionSetNight", false),
        new("visionsetmissilecam", "PS3 0x001B7D88", false),
        new("visionsetthermal", "PS3 0x001B7D80", false),
        new("visionsetpain", "PS3 0x001B7D78", false),
        new("endlobby", "NULLSUB", false),
        new("setac130ambience", "PS3 0x001B7B08", false),
        new("getmapcustom", "PS3 0x001AFEE0", false),
        new("updateskill", "PS3 0x001B6A78", false),
        new("spawnsighttrace", "PS3 0x001AF798", false),
    ];

    // 0x00717BDC: 146 registrations.
    private static readonly Registration[] SharedMethods =
    [
        new("attach", "ScrCmd_attach", false),
        new("attachshieldmodel", "PS3 0x001A3FB0", false),
        new("detach", "ScrCmd_detach", false),
        new("detachshieldmodel", "PS3 0x001A3D18", false),
        new("moveshieldmodel", "PS3 0x001A3A68", false),
        new("detachall", "ScrCmd_detachAll", false),
        new("getattachsize", "ScrCmd_GetAttachSize", false),
        new("getattachmodelname", "ScrCmd_GetAttachModelName", false),
        new("getattachtagname", "ScrCmd_GetAttachTagName", false),
        new("getattachignorecollision", "ScrCmd_GetAttachIgnoreCollision", false),
        new("hidepart", "ScrCmd_hidepart", false),
        new("hidepart_allinstances", "PS3 0x001ABE80", false),
        new("hideallparts", "PS3 0x001A34E8", false),
        new("showpart", "ScrCmd_showpart", false),
        new("showallparts", "ScrCmd_showallparts", false),
        new("linkto", "ScrCmd_LinkTo", false),
        new("linktoblendtotag", "PS3 0x001A33D8", false),
        new("unlink", "ScrCmd_Unlink", false),
        new("islinked", "PS3 0x001A2EB0", false),
        new("enablelinkto", "ScrCmd_EnableLinkTo", false),
        new("playerlinkto", "PS3 0x001A2DB0", false),
        new("playerlinktodelta", "PS3 0x001A2D88", false),
        new("playerlinkweaponviewtodelta", "PS3 0x001A2D60", false),
        new("playerlinktoabsolute", "PS3 0x001A25A8", false),
        new("playerlinktoblend", "PS3 0x001A97D0", false),
        new("playerlinkedoffsetenable", "PS3 0x0019CDD8", false),
        new("playerlinkedoffsetdisable", "PS3 0x0019CCE8", false),
        new("lerpviewangleclamp", "PS3 0x001AAC68", false),
        new("geteye", "ScrCmd_GetEye", false),
        new("istouching", "ScrCmd_IsTouching", false),
        new("stoploopsound", "ScrCmd_StopLoopSound", false),
        new("stopsounds", "PS3 0x001A1150", false),
        new("playrumbleonentity", "ScrCmd_NULLSUB", false),
        new("playrumblelooponentity", "ScrCmd_NULLSUB", false),
        new("stoprumble", "ScrCmd_NULLSUB", false),
        new("delete", "ScrCmd_Delete", false),
        new("setmodel", "ScrCmd_SetModel", false),
        new("laseron", "ScrCmd_LaserOn", false),
        new("laseroff", "ScrCmd_LaserOff", false),
        new("laseraltviewon", "PS3 0x0019CB28", false),
        new("laseraltviewoff", "PS3 0x0019CA38", false),
        new("thermalvisionon", "PS3 0x0019C950", false),
        new("thermalvisionoff", "PS3 0x0019C860", false),
        new("thermalvisionfofoverlayon", "PS3 0x0019C778", false),
        new("thermalvisionfofoverlayoff", "PS3 0x0019C688", false),
        new("setcontents", "ScrCmd_SetContents", false),
        new("makeusable", "PS3 0x001A1D48", false),
        new("makeunusable", "PS3 0x001A1CD0", false),
        new("setcursorhint", "GScr_SetCursorHint", false),
        new("sethintstring", "GScr_SetHintString", false),
        new("forceusehinton", "PS3 0x001A48D0", false),
        new("forceusehintoff", "PS3 0x0019CC10", false),
        new("makesoft", "PS3 0x0019D3F0", false),
        new("makehard", "PS3 0x0019D3A0", false),
        new("willneverchange", "PS3 0x0019D350", false),
        new("startfiring", "PS3 0x0019DD78", false),
        new("stopfiring", "PS3 0x0019DCB0", false),
        new("isfiringturret", "PS3 0x001A1A00", false),
        new("startbarrelspin", "PS3 0x001A1948", false),
        new("stopbarrelspin", "PS3 0x001A1890", false),
        new("getbarrelspinrate", "PS3 0x001A17D0", false),
        new("shootturret", "PS3 0x001A1720", false),
        new("getturretowner", "PS3 0x001AAFB8", false),
        new("setsentryowner", "PS3 0x001A1628", false),
        new("setsentrycarried", "PS3 0x001A1550", false),
        new("setturretminimapvisible", "PS3 0x001A1480", false),
        new("settargetentity", "PS3 0x001AA008", false),
        new("cleartargetentity", "PS3 0x0019FF20", false),
        new("getturrettarget", "PS3 0x001AB128", false),
        new("setplayerspread", "PS3 0x0019E928", false),
        new("setaispread", "PS3 0x0019C410", false),
        new("setsuppressiontime", "PS3 0x0019C3E0", false),
        new("setconvergencetime", "PS3 0x0019F470", false),
        new("setturretteam", "PS3 0x0019DB90", false),
        new("maketurretsolid", "PS3 0x001A1360", false),
        new("maketurretoperable", "PS3 0x0019DAC8", false),
        new("maketurretinoperable", "PS3 0x0019DA10", false),
        new("setturretaccuracy", "PS3 0x0019FD08", false),
        new("setrightarc", "GScr_SetRightArc", false),
        new("setleftarc", "GScr_SetLeftArc", false),
        new("settoparc", "GScr_SetTopArc", false),
        new("setbottomarc", "GScr_SetBottomArc", false),
        new("setautorotationdelay", "PS3 0x001AC6A0", false),
        new("setdefaultdroppitch", "PS3 0x001A12A0", false),
        new("restoredefaultdroppitch", "PS3 0x001A11E8", false),
        new("turretfiredisable", "PS3 0x0019D958", false),
        new("turretfireenable", "PS3 0x0019D890", false),
        new("setturretmodechangewait", "PS3 0x0019D7B8", false),
        new("usetriggerrequirelookat", "GScr_UseTriggerRequireLookAt", false),
        new("getstance", "ScrCmd_GetStance", false),
        new("setstance", "PS3 0x001A92D0", false),
        new("itemweaponsetammo", "ScrCmd_ItemWeaponSetAmmo", false),
        new("getammocount", "GScr_GetAmmoCount", false),
        new("gettagorigin", "GScr_GetTagOrigin", false),
        new("gettagangles", "GScr_GetTagAngles", false),
        new("shellshock", "GScr_ShellShock", false),
        new("stunplayer", "PS3 0x001ACB48", false),
        new("stopshellshock", "GScr_StopShellShock", false),
        new("fadeoutshellshock", "PS3 0x001A0700", false),
        new("setdepthoffield", "GScr_SetDepthOfField", false),
        new("setviewmodeldepthoffield", "GScr_SetViewModelDepthOfField", false),
        new("setmotionblurmovescale", "PS3 0x0019BFB8", false),
        new("setmotionblurturnscale", "PS3 0x0019BFC0", false),
        new("setmotionblurzoomscale", "PS3 0x0019BFC8", false),
        new("viewkick", "GScr_ViewKick", false),
        new("localtoworldcoords", "GScr_LocalToWorldCoords", false),
        new("getentitynumber", "GScr_GetEntityNumber", false),
        new("enablegrenadetouchdamage", "GScr_EnableGrenadeTouchDamage", false),
        new("disablegrenadetouchdamage", "GScr_DisableGrenadeTouchDamage", false),
        new("enableaimassist", "GScr_EnableAimAssist", false),
        new("disableaimassist", "GScr_DisableAimAssist", false),
        new("radiusdamage", "GScr_EntityRadiusDamage", false),
        new("detonate", "GScr_Detonate", false),
        new("damageconetrace", "GScr_DamageConeTrace", false),
        new("sightconetrace", "GScr_SightConeTrace", false),
        new("missile_settargetent", "PS3 0x001A9EA8", false),
        new("missile_settargetpos", "PS3 0x001A9DA8", false),
        new("missile_cleartarget", "PS3 0x001AA870", false),
        new("missile_setflightmodedirect", "PS3 0x0019D610", false),
        new("missile_setflightmodetop", "PS3 0x0019D5E8", false),
        new("getlightintensity", "PS3 0x0019F7B8", false),
        new("setlightintensity", "PS3 0x001AB790", false),
        new("isragdoll", "GScr_IsRagdoll", false),
        new("setmovespeedscale", "ScrCmd_SetMoveSpeedScale", false),
        new("cameralinkto", "PS3 0x0019FFE8", false),
        new("cameraunlink", "PS3 0x0019DF70", false),
        new("controlslinkto", "PS3 0x0019FE40", false),
        new("controlsunlink", "PS3 0x0019FD38", false),
        new("getplayersetting", "PS3 0x0019FC10", false),
        new("getlocalplayerprofiledata", "PS3 0x0019F948", false),
        new("setlocalplayerprofiledata", "PS3 0x001ABC50", false),
        new("remotecamerasoundscapeon", "PS3 0x0019D130", false),
        new("remotecamerasoundscapeoff", "PS3 0x0019D088", false),
        new("radarjamon", "PS3 0x0019C5A0", false),
        new("radarjamoff", "PS3 0x0019C4B0", false),
        new("setmotiontrackervisible", "PS3 0x0019CFD8", false),
        new("getmotiontrackervisible", "PS3 0x0019EC88", false),
        new("worldpointinreticle_circle", "PS3 0x0019EE68", false),
        new("getpointinbounds", "PS3 0x0019E9F8", false),
        new("transfermarkstonewscriptmodel", "PS3 0x0019E510", false),
        new("alternatescenecameralinkto", "PS3 0x0019C2A0", false),
        new("alternatescenecameraunlink", "PS3 0x0019C270", false),
        new("setwatersheeting", "PS3 0x001A8538", false),
        new("setweaponhudiconoverride", "PS3 0x0019E3A0", false),
        new("getweaponhudiconoverride", "PS3 0x0019E238", false),
        new("setempjammed", "PS3 0x0019CF20", false),
    ];

    // 0x00717A38: 35 registrations.
    private static readonly Registration[] ClientMethods =
    [
        new("pingplayer", "PlayerCmd_pingPlayer", false),
        new("buttonpressed", "PlayerCmd_buttonPressedDEVONLY", false),
        new("sayall", "PlayerCmd_SayAll", false),
        new("sayteam", "PlayerCmd_SayTeam", false),
        new("showscoreboard", "PlayerCmd_showScoreboard", false),
        new("setspawnweapon", "PlayerCmd_setSpawnWeapon", false),
        new("dropitem", "PlayerCmd_dropItem", false),
        new("dropscavengerbag", "PS3 0x0017C120", false),
        new("finishplayerdamage", "PlayerCmd_finishPlayerDamage", false),
        new("suicide", "PlayerCmd_Suicide", false),
        new("closeingamemenu", "PlayerCmd_CloseInGameMenu", false),
        new("iprintln", "iclientprintln", false),
        new("iprintlnbold", "iclientprintlnbold", false),
        new("spawn", "PlayerCmd_spawn", false),
        new("setentertime", "PlayerCmd_setEnterTime", false),
        new("cloneplayer", "PlayerCmd_ClonePlayer", false),
        new("istalking", "PlayerCmd_IsTalking", false),
        new("allowspectateteam", "PlayerCmd_AllowSpectateTeam", false),
        new("getguid", "PlayerCmd_GetGuid", false),
        new("getxuid", "PlayerCmd_GetXuid", false),
        new("ishost", "PS3 0x0017B7B0", false),
        new("getspectatingplayer", "PS3 0x0017B6B0", false),
        new("predictstreampos", "PS3 0x0017B568", false),
        new("updatescores", "PlayerCmd_UpdateScores", false),
        new("updatedmscores", "PlayerCmd_UpdateDMScores", false),
        new("setrank", "PlayerCmd_SetRank", false),
        new("setcardtitle", "PS3 0x0017B470", false),
        new("setcardicon", "PS3 0x0017B378", false),
        new("setcardnameplate", "PS3 0x0017B280", false),
        new("setcarddisplayslot", "PS3 0x0017AC80", false),
        new("kc_regweaponforfxremoval", "PS3 0x0017AB80", false),
        new("laststandrevive", "PS3 0x0017A3F0", false),
        new("showhudsplash", "PS3 0x0017A9F0", false),
        new("setspectatedefaults", "PS3 0x0017A6E0", false),
        new("getthirdpersoncrosshairoffset", "PS3 0x0017A600", false),
    ];

    // 0x00710E88: 107 registrations.
    private static readonly Registration[] PlayerMethods =
    [
        new("getviewmodel", "PlayerCmd_GetViewmodel", false),
        new("fragbuttonpressed", "PlayerCmd_fragButtonPressed", false),
        new("secondaryoffhandbuttonpressed", "PlayerCmd_secondaryOffhandButtonPressed", false),
        new("getcurrentweaponclipammo", "PS3 0x00178BC8", false),
        new("setvelocity", "PS3 0x00172DA8", false),
        new("getplayerviewheight", "PS3 0x001767F0", false),
        new("getnormalizedmovement", "PS3 0x001737A0", false),
        new("giveweapon", "PlayerCmd_giveWeapon", false),
        new("takeweapon", "PlayerCmd_takeWeapon", false),
        new("takeallweapons", "PlayerCmd_takeAllWeapons", false),
        new("getcurrentweapon", "PlayerCmd_getCurrentWeapon", false),
        new("getcurrentprimaryweapon", "PS3 0x00176E70", false),
        new("getcurrentoffhand", "PlayerCmd_getCurrentOffhand", false),
        new("hasweapon", "PlayerCmd_hasWeapon", false),
        new("switchtoweapon", "PlayerCmd_switchToWeapon", false),
        new("switchtoweaponimmediate", "PS3 0x00176BE0", false),
        new("switchtooffhand", "PlayerCmd_switchToOffhand", false),
        new("givestartammo", "PlayerCmd_giveStartAmmo", false),
        new("givemaxammo", "PlayerCmd_giveMaxAmmo", false),
        new("getfractionstartammo", "PlayerCmd_getFractionStartAmmo", false),
        new("getfractionmaxammo", "PlayerCmd_getFractionMaxAmmo", false),
        new("isdualwielding", "PS3 0x00175768", false),
        new("isreloading", "PS3 0x00175658", false),
        new("isswitchingweapon", "PS3 0x00175570", false),
        new("setorigin", "PlayerCmd_setOrigin", false),
        new("getvelocity", "PlayerCmd_GetVelocity", false),
        new("setplayerangles", "PlayerCmd_setAngles", false),
        new("getplayerangles", "PlayerCmd_getAngles", false),
        new("usebuttonpressed", "PlayerCmd_useButtonPressed", false),
        new("attackbuttonpressed", "PlayerCmd_attackButtonPressed", false),
        new("adsbuttonpressed", "PlayerCmd_adsButtonPressed", false),
        new("meleebuttonpressed", "PlayerCmd_meleeButtonPressed", false),
        new("playerads", "PlayerCmd_playerADS", false),
        new("isonground", "PlayerCmd_isOnGround", false),
        new("isusingturret", "PS3 0x00174F48", false),
        new("setviewmodel", "PlayerCmd_SetViewmodel", false),
        new("setoffhandprimaryclass", "PS3 0x001740A8", false),
        new("getoffhandprimaryclass", "PS3 0x00176500", false),
        new("setoffhandsecondaryclass", "PlayerCmd_setOffhandSecondaryClass", false),
        new("getoffhandsecondaryclass", "PlayerCmd_getOffhandSecondaryClass", false),
        new("beginlocationselection", "PlayerCmd_BeginLocationSelection", false),
        new("endlocationselection", "PlayerCmd_EndLocationSelection", false),
        new("disableweapons", "PlayerCmd_DisableWeapons", false),
        new("enableweapons", "PlayerCmd_EnableWeapons", false),
        new("disableoffhandweapons", "PS3 0x00171A98", false),
        new("enableoffhandweapons", "PS3 0x001719A8", false),
        new("disableweaponswitch", "PS3 0x001718C0", false),
        new("enableweaponswitch", "PS3 0x001717D0", false),
        new("openpopupmenu", "PS3 0x001760D0", false),
        new("openpopupmenunomouse", "PS3 0x00175F88", false),
        new("closepopupmenu", "PS3 0x00175A50", false),
        new("openmenu", "PlayerCmd_OpenMenu", false),
        new("closemenu", "PlayerCmd_CloseMenu", false),
        new("freezecontrols", "PlayerCmd_FreezeControls", false),
        new("disableusability", "PS3 0x00171E48", false),
        new("enableusability", "PS3 0x00171D58", false),
        new("setreverb", "PlayerCmd_SetReverb", false),
        new("deactivatereverb", "PlayerCmd_DeactivateReverb", false),
        new("setchannelvolumes", "PlayerCmd_SetChannelVolumes", false),
        new("deactivatechannelvolumes", "PlayerCmd_DeactivateChannelVolumes", false),
        new("playlocalsound", "ScrCmd_PlayLocalSound", false),
        new("stoplocalsound", "ScrCmd_StopLocalSound", false),
        new("setweaponammoclip", "PlayerCmd_SetWeaponAmmoClip", false),
        new("setweaponammostock", "PlayerCmd_SetWeaponAmmoStock", false),
        new("getweaponammoclip", "PlayerCmd_GetWeaponAmmoClip", false),
        new("getweaponammostock", "PlayerCmd_GetWeaponAmmoStock", false),
        new("anyammoforweaponmodes", "PlayerCmd_AnyAmmoForWeaponModes", false),
        new("setclientdvar", "PlayerCmd_SetClientDvar", false),
        new("setclientdvars", "PlayerCmd_SetClientDvars", false),
        new("allowads", "PlayerCmd_AllowADS", false),
        new("allowjump", "PlayerCmd_AllowJump", false),
        new("allowsprint", "PlayerCmd_AllowSprint", false),
        new("setspreadoverride", "PlayerCmd_SetSpreadOverride", false),
        new("resetspreadoverride", "PlayerCmd_ResetSpreadOverride", false),
        new("setactionslot", "PlayerCmd_SetActionSlot", false),
        new("getweaponslistall", "PS3 0x001777D8", false),
        new("getweaponslistprimaries", "PlayerCmd_GetWeaponsListPrimaries", false),
        new("getweaponslistoffhands", "PS3 0x001744A0", false),
        new("getweaponslistitems", "PS3 0x00174478", false),
        new("getweaponslistexclusives", "PS3 0x00174450", false),
        new("getweaponslist", "PlayerCmd_GetWeaponsList", false),
        new("canplayerplacesentry", "PS3 0x00173680", false),
        new("visionsetnakedforplayer", "PS3 0x00178A30", false),
        new("visionsetnightforplayer", "PS3 0x00178A08", false),
        new("visionsetmissilecamforplayer", "PS3 0x001789E0", false),
        new("visionsetthermalforplayer", "PS3 0x001789B8", false),
        new("visionsetpainforplayer", "PS3 0x00178990", false),
        new("setblurforplayer", "PS3 0x001734E8", false),
        new("getplayerweaponmodel", "PS3 0x00173378", false),
        new("getplayerknifemodel", "PS3 0x00173348", false),
        new("notifyonplayercommand", "PS3 0x00173260", false),
        new("canmantle", "PS3 0x00173190", false),
        new("forcemantle", "PS3 0x001730B8", false),
        new("ismantling", "PS3 0x001726F0", false),
        new("playfx", "PS3 0x00172E70", false),
        new("player_recoilscaleon", "PS3 0x001721E8", false),
        new("player_recoilscaleoff", "PS3 0x00171608", false),
        new("weaponlockstart", "PS3 0x00172BE0", false),
        new("weaponlockfinalize", "PS3 0x001729B8", false),
        new("weaponlockfree", "PS3 0x00171518", false),
        new("weaponlocktargettooclose", "PS3 0x00172108", false),
        new("weaponlocknoclearance", "PS3 0x00172028", false),
        new("setrearviewrenderenabled", "PS3 0x00171F30", false),
        new("setperk", "PlayerCmd_SetPerk", false),
        new("hasperk", "PlayerCmd_HasPerk", false),
        new("clearperks", "PlayerCmd_ClearPerks", false),
        new("unsetperk", "PlayerCmd_UnsetPerk", false),
    ];

    // 0x00718CA4: 25 registrations.
    private static readonly Registration[] ScriptEntityMethods =
    [
        new("moveto", "ScriptEntCmd_MoveTo", false),
        new("movex", "ScriptEntCmd_MoveX", false),
        new("movey", "ScriptEntCmd_MoveY", false),
        new("movez", "ScriptEntCmd_MoveZ", false),
        new("movegravity", "ScriptEntCmd_GravityMove", false),
        new("moveslide", "PS3 0x001BA7D8", false),
        new("stopmoveslide", "PS3 0x001B85A8", false),
        new("rotateto", "ScriptEntCmd_RotateTo", false),
        new("rotatepitch", "ScriptEntCmd_RotatePitch", false),
        new("rotateyaw", "ScriptEntCmd_RotateYaw", false),
        new("rotateroll", "ScriptEntCmd_RotateRoll", false),
        new("addpitch", "PS3 0x001BA248", false),
        new("addyaw", "PS3 0x001BA220", false),
        new("addroll", "PS3 0x001BA1F8", false),
        new("vibrate", "ScriptEntCmd_Vibrate", false),
        new("rotatevelocity", "ScriptEntCmd_RotateVelocity", false),
        new("solid", "ScriptEntCmd_Solid", false),
        new("notsolid", "ScriptEntCmd_NotSolid", false),
        new("setcandamage", "ScriptEntCmd_SetCanDamage", false),
        new("setcanradiusdamage", "PS3 0x001B8DF0", false),
        new("physicslaunchclient", "PS3 0x001BAE68", false),
        new("physicslaunchserver", "PS3 0x001BABD8", false),
        new("clonebrushmodeltoscriptmodel", "PS3 0x001B8C20", false),
        new("scriptmodelplayanim", "PS3 0x001B8A88", false),
        new("scriptmodelclearanim", "PS3 0x001B8970", false),
    ];

    // 0x00719588: 59 registrations.
    private static readonly Registration[] VehicleMethods =
    [
        new("vehicle_teleport", "PS3 0x0033FF70", false),
        new("attachpath", "PS3 0x0033FDF8", false),
        new("getattachpos", "PS3 0x0033FC30", false),
        new("startpath", "PS3 0x0033FA90", false),
        new("setswitchnode", "PS3 0x0033EA40", false),
        new("setwaitspeed", "PS3 0x0033D9E8", false),
        new("vehicle_finishdamage", "PS3 0x0033E788", false),
        new("vehicle_setspeed", "PS3 0x0033E738", false),
        new("vehicle_setspeedimmediate", "PS3 0x00340468", false),
        new("vehicle_rotateyaw", "PS3 0x0033F7D8", false),
        new("vehicle_getspeed", "PS3 0x0033E4C8", false),
        new("vehicle_getvelocity", "PS3 0x0033EB28", false),
        new("vehicle_getbodyvelocity", "PS3 0x0033EAD0", false),
        new("vehicle_getsteering", "PS3 0x0033E440", false),
        new("vehicle_getthrottle", "PS3 0x0033E3E8", false),
        new("vehicle_turnengineoff", "PS3 0x0033D990", false),
        new("vehicle_turnengineon", "PS3 0x0033D930", false),
        new("getgoalspeedmph", "PS3 0x0033E388", false),
        new("setacceleration", "PS3 0x0033D8C8", false),
        new("setdeceleration", "PS3 0x0033D860", false),
        new("resumespeed", "CMD_VEH_ResumeSpeed", false),
        new("setyawspeed", "CMD_VEH_SetYawSpeed", false),
        new("setmaxpitchroll", "CMD_VEH_SetMaxPitchRoll", false),
        new("setairresistance", "CMD_VEH_SetAirResitance", false),
        new("setturningability", "CMD_VEH_SetTurningAbility", false),
        new("setjitterparams", "PS3 0x0033D3C0", false),
        new("sethoverparams", "CMD_VEH_SetHoverParams", false),
        new("joltbody", "PS3 0x0033E1E0", false),
        new("freevehicle", "PS3 0x0033F208", false),
        new("getwheelsurface", "PS3 0x0033E008", false),
        new("getvehicleowner", "PS3 0x003403F0", false),
        new("setvehiclelookattext", "PS3 0x0033DF68", false),
        new("setvehicleteam", "CMD_VEH_SetVehicleTeam", false),
        new("setneargoalnotifydist", "CMD_VEH_NearGoalNotifyDist", false),
        new("setvehgoalpos", "CMD_VEH_SetGoalPos", false),
        new("setgoalyaw", "CMD_VEH_SetGoalYaw", false),
        new("cleargoalyaw", "CMD_VEH_ClearGoalYaw", false),
        new("settargetyaw", "CMD_VEH_SetTargetYaw", false),
        new("cleartargetyaw", "CMD_VEH_ClearTargetYaw", false),
        new("setturrettargetvec", "CMD_VEH_SetTurretTargetVec", false),
        new("setturrettargetent", "CMD_VEH_SetTurretTargetEnt", false),
        new("clearturrettarget", "CMD_VEH_ClearTurretTargetEnt", false),
        new("vehicle_canturrettargetpoint", "PS3 0x00340DB0", false),
        new("setlookatent", "CMD_VEH_SetLookAtEnt", false),
        new("clearlookatent", "CMD_VEH_ClearLookAtEnt", false),
        new("setvehweapon", "CMD_VEH_SetWeapon", false),
        new("fireweapon", "CMD_VEH_FireWeapon", false),
        new("vehicleturretcontrolon", "PS3 0x0033EEF0", false),
        new("vehicleturretcontroloff", "PS3 0x0033EE88", false),
        new("isturretready", "PS3 0x0033DED8", false),
        new("vehicledriveto", "PS3 0x0033CF38", false),
        new("vehicle_dospawn", "PS3 0x0033C550", false),
        new("vehicle_isphysveh", "PS3 0x0033CEC8", false),
        new("vehphys_crash", "PS3 0x0033CDC0", false),
        new("vehphys_launch", "PS3 0x0033CC70", false),
        new("vehphys_disablecrashing", "PS3 0x0033CBD0", false),
        new("vehphys_enablecrashing", "PS3 0x0033CB38", false),
        new("vehphys_setspeed", "PS3 0x0033CA58", false),
        new("vehphys_setconveyorbelt", "PS3 0x0033C940", false),
    ];

    // 0x00719450: 26 registrations.
    private static readonly Registration[] HelicopterMethods =
    [
        new("freehelicopter", "CMD_Heli_FreeHelicopter", false),
        new("vehicle_setspeed", "PS3 0x0033E738", false),
        new("vehicle_getspeed", "PS3 0x0033E4C8", false),
        new("resumespeed", "CMD_VEH_ResumeSpeed", false),
        new("setyawspeed", "CMD_VEH_SetYawSpeed", false),
        new("setmaxpitchroll", "CMD_VEH_SetMaxPitchRoll", false),
        new("setturningability", "CMD_VEH_SetTurningAbility", false),
        new("setairresistance", "CMD_VEH_SetAirResitance", false),
        new("sethoverparams", "CMD_VEH_SetHoverParams", false),
        new("setneargoalnotifydist", "CMD_VEH_NearGoalNotifyDist", false),
        new("setvehgoalpos", "CMD_VEH_SetGoalPos", false),
        new("setgoalyaw", "CMD_VEH_SetGoalYaw", false),
        new("cleargoalyaw", "CMD_VEH_ClearGoalYaw", false),
        new("settargetyaw", "CMD_VEH_SetTargetYaw", false),
        new("cleartargetyaw", "CMD_VEH_ClearTargetYaw", false),
        new("setlookatent", "CMD_VEH_SetLookAtEnt", false),
        new("clearlookatent", "CMD_VEH_ClearLookAtEnt", false),
        new("setvehweapon", "CMD_VEH_SetWeapon", false),
        new("fireweapon", "CMD_VEH_FireWeapon", false),
        new("setturrettargetvec", "CMD_VEH_SetTurretTargetVec", false),
        new("setturrettargetent", "CMD_VEH_SetTurretTargetEnt", false),
        new("clearturrettarget", "CMD_VEH_ClearTurretTargetEnt", false),
        new("setvehicleteam", "CMD_VEH_SetVehicleTeam", false),
        new("setdamagestage", "CMD_Heli_SetDamageStage", false),
        new("vehicleturretcontrolon", "PS3 0x0033EEF0", false),
        new("vehicleturretcontroloff", "PS3 0x0033EE88", false),
    ];

    // 0x007113DC: 28 registrations.
    private static readonly Registration[] HudElementMethods =
    [
        new("settext", "HECmd_SetText", false),
        new("clearalltextafterhudelem", "HECmd_ClearAllTextAfterHudElem", false),
        new("setshader", "HECmd_SetMaterial", false),
        new("settargetent", "HECmd_SetTargetEnt", false),
        new("cleartargetent", "HECmd_ClearTargetEnt", false),
        new("settimer", "HECmd_SetTimer", false),
        new("settimerup", "HECmd_SetTimerUp", false),
        new("settimerstatic", "PS3 0x00186C98", false),
        new("settenthstimer", "HECmd_SetTenthsTimer", false),
        new("settenthstimerup", "HECmd_SetTenthsTimerUp", false),
        new("settenthstimerstatic", "PS3 0x00186C08", false),
        new("setclock", "HECmd_SetClock", false),
        new("setclockup", "HECmd_SetClockUp", false),
        new("setvalue", "HECmd_SetValue", false),
        new("setwaypoint", "HECmd_SetWaypoint", false),
        new("setwaypointedgestyle_rotatingicon", "PS3 0x001853D0", false),
        new("setwaypointedgestyle_secondaryarrow", "PS3 0x00185358", false),
        new("setwaypointiconoffscreenonly", "PS3 0x001852E8", false),
        new("fadeovertime", "HECmd_FadeOverTime", false),
        new("scaleovertime", "HECmd_ScaleOverTime", false),
        new("moveovertime", "HECmd_MoveOverTime", false),
        new("reset", "HECmd_Reset", false),
        new("destroy", "HECmd_Destroy", false),
        new("setpulsefx", "HECmd_SetPulseFX", false),
        new("setplayernamestring", "PS3 0x00185190", false),
        new("setmapnamestring", "PS3 0x00184FD8", false),
        new("setgametypestring", "PS3 0x00185088", false),
        new("changefontscaleovertime", "HECmd_ChangeFontScaleOverTime", false),
    ];

    // 0x00718AD0: 39 registrations.
    private static readonly Registration[] GenericMethods =
    [
        new("getorigin", "ScrCmd_GetOrigin", false),
        new("useby", "ScrCmd_UseBy", false),
        new("setstablemissile", "Scr_SetStableMissile", false),
        new("playsound", "ScrCmd_PlaySound", false),
        new("playsoundasmaster", "ScrCmd_PlaySoundAsMaster", false),
        new("playsoundtoteam", "ScrCmd_PlaySoundToTeam", false),
        new("playsoundtoplayer", "ScrCmd_PlaySoundToPlayer", false),
        new("playloopsound", "ScrCmd_PlayLoopSound", false),
        new("getnormalhealth", "ScrCmd_GetNormalHealth", false),
        new("setnormalhealth", "ScrCmd_SetNormalHealth", false),
        new("show", "ScrCmd_Show", false),
        new("hide", "ScrCmd_Hide", false),
        new("playerhide", "PS3 0x001B4938", false),
        new("showtoplayer", "ScrCmd_ShowToPlayer", false),
        new("enableplayeruse", "PS3 0x001B5A30", false),
        new("disableplayeruse", "PS3 0x001B5998", false),
        new("setmode", "PS3 0x001B5468", false),
        new("getmode", "PS3 0x001B4648", false),
        new("placespawnpoint", "GScr_PlaceSpawnPoint", false),
        new("setteamfortrigger", "GScr_SetTeamForTrigger", false),
        new("clientclaimtrigger", "GScr_ClientClaimTrigger", false),
        new("clientreleasetrigger", "GScr_ClientReleaseTrigger", false),
        new("releaseclaimedtrigger", "GScr_ReleaseClaimedTrigger", false),
        new("getplayerdata", "PS3 0x001B44B8", false),
        new("setplayerdata", "PS3 0x001B6F40", false),
        new("isusingonlinedataoffline", "PS3 0x001B53B0", false),
        new("isitemunlocked", "PS3 0x001B6950", false),
        new("getrandomloot", "PS3 0x001B67F0", false),
        new("createlootmail", "PS3 0x001B66D0", false),
        new("getrestedtime", "PS3 0x001B52A0", false),
        new("sendleaderboards", "ScrCmd_NULLSUB", false),
        new("logstring", "ScrCmd_NULLSUB", false),
        new("isonladder", "GScr_IsOnLadder", false),
        new("ismantling", "GScr_IsMantling", false),
        new("startragdoll", "GScr_StartRagdoll", false),
        new("getcorpseanim", "GScr_GetCorpseAnim", false),
        new("playerforcedeathanim", "PS3 0x001B5780", false),
        new("startac130", "PS3 0x001B3CC8", false),
        new("stopac130", "PS3 0x001B3C20", false),
    ];

    private static readonly Registration[] VmIntrinsics =
    [
        new("wait", "OP_wait", false),
        new("waittillframeend", "OP_waittillFrameEnd", false),
        new("waittill", "OP_waittill", false),
        new("waittillmatch", "OP_waittillmatch", false),
        new("notify", "OP_notify", false),
        new("endon", "OP_endon", false),
    ];
}
